### ISSUE TITLE
Question about breseq gdtools COMPARE output

### ISSUE THREAD

**Issue by pohlcath** [barricklab/breseq#100]
This should be an easy question, but I can't fine the answer anywhere.  In a COMPARE output table file, what does a question mark in a column for a particular genome mean?  I figured in meant that the mutation was in a region of low coverage for that sample maybe, but don't see evidence for that in the other output files.  Can you explain this for me?

**Comment by jeffreybarrick** [comment]
You're right, "?" is put in the COMPARE table when coverage at that position in that genome was too low to call that mutation. This happens when a "small" mutation (<50 bp) overlaps a "missing coverage" (MC) region (you can see the MC coverage regions in the output.gd file).
