### ISSUE TITLE
mutation reported by older version and visible using IGV, but not included in output.gd

### ISSUE THREAD

**Issue by wmoebius** [barricklab/breseq#104]
This problem is harder to describe and would probably require supplying the fasta and/or bam file:

In breseq 0.28.1 in polymorphism mode a mutation is not included in output.gd at all (i.e., not just rejected), but was reported by 0.25c and is visible in IGV.

**Comment by jeffreybarrick** [comment]
Another user reported what I believe is this issue, and it has been fixed in 0.28.2rc5 available at http://barricklab.org/release/breseq. It will be included in the next official release (probably 0.29.0), which will hopefully be happening within a few weeks.
