### ISSUE TITLE
v.0.27.1 Different % mapped for completely unpaired vs. paired+unpaired reads

### ISSUE THREAD

**Issue by yeemey** [barricklab/breseq#105]
Hi,

I get markedly different mapping success depending on whether I only use the original unpaired forward and reverse reads, or paired reads plus the reads that failed to pair. My thought is that the length of the paired reads allows them to meet the similarity threshold for mapping to the reference, and thus more success, but I'm not certain if this is true. Is this something you've noticed before?

I've attached the BRESEQ summaries for my results, but please let me know if you need more info.

Thank you,
Yee Mey Seah
Hillesland Lab

[BRESEQ -- Summary Statistics_assembled.pdf](https://github.com/barricklab/breseq/files/567365/BRESEQ.--.Summary.Statistics_assembled.pdf)
[BRESEQ -- Summary Statistics_unassembled.pdf](https://github.com/barricklab/breseq/files/567364/BRESEQ.--.Summary.Statistics_unassembled.pdf)

**Comment by jeffreybarrick** [comment]
When you look at your single read alignments in the _breseq_ html output do they often have mismatches or N's at the end? One explanation may be that the assembled read pairs are better at exceeding requirement that >90% of the length of the read matches. Trimming their ends would improve the mapping in that case (<= that's the best solution, but you can also reduce the 90% requirement using the `--require-match-fraction` option).

**Comment by yeemey** [comment]
I should've mentioned that these reads have already been trimmed and adapters removed with sickle/scythe before assembly or breseq analyses. If I understand your question correctly, I don't often see N's or mismatches at the ends when I look at the html output for RA evidence for predicted mutations in the single reads. 

We agree that the longer lengths of assembled read pairs may help in exceeding the read match requirements. I don't think lowering the 90% threshold will be appropriate for our data (but now I know how to do that if need be, thank you) so I suppose the best course of action is to only feed breseq assembled reads.

**Comment by jeffreybarrick** [comment]
I would say that there's probably no harm in feeding the unassembled reads to _breseq_ alongside the assembled ones. The unassembled ones that map are mapping well and the ones that have problems are probably just not mapping and being ignored. It may not make much difference if your coverage is >40x either way (including them or not including them).
