### ISSUE TITLE
Error with version 0.28.1

### ISSUE THREAD

**Issue by krfarle2** [barricklab/breseq#106]
Hi I just tried to use breseq version 0.28.1 and received this error

[system] R --vanilla < /usr/local/archive/breseq/breseq-0.28.1/src/c/breseq/../share/breseq//coverage_distribution.r > ./03_candidate_junctions/0.unique_only_coverage_distribution.tab.r.log distribution_file=./03_candidate_junctions/0.unique_only_coverage_distribution.tab plot_file=./03_candidate_junctions/0.coverage.pdf deletion_propagation_pr_cutoff=3.67294e-05
sh: 1: cannot open /usr/local/archive/breseq/breseq-0.28.1/src/c/breseq/../share/breseq//coverage_distribution.r: No such file
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error running command:
[system] R --vanilla < /usr/local/archive/breseq/breseq-0.28.1/src/c/breseq/../share/breseq//coverage_distribution.r > ./03_candidate_junctions/0.unique_only_coverage_distribution.tab.r.log distribution_file=./03_candidate_junctions/0.unique_only_coverage_distribution.tab plot_file=./03_candidate_junctions/0.coverage.pdf deletion_propagation_pr_cutoff=3.67294e-05
Result code: 512
FILE: libbreseq/common.h   LINE: 1378
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Any suggestions? Thank you!

**Comment by jeffreybarrick** [comment]
Hi, it looks like you are compiling from the source and didn't do a `make install` step to copy the built executable and support files into their appropriate locations.

Check this out:
http://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/installation.html#method-2-source-code-package

If those instructions don't work, let me know.
