### ISSUE TITLE
lower case bases in fasta

### ISSUE THREAD

**Issue by cfblaeb** [barricklab/breseq#109]
I'm getting the following error when running with yeast S288C NCBI refseq as reference fasta file:
+++   NOW PROCESSING Tabulating error counts
  REFERENCE: NC_001133.9
  LENGTH: 230218
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Unrecognized base char
FILE: libbreseq/common.h   LINE: 166
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I have checked the fasta and it only contains A, T, C and G's.
However its using a mix of upper and lower case bases which I think denotes repeats or otherwise attention worthy sequences.
I will try to re-run with the bases all changed to uppercase and report back.

**Comment by jeffreybarrick** [comment]
Thanks for the bug report.

I don't think it's uppercase/lowercase that is causing the problem. breseq converts the input reference when it encounters things like lowercase characters in the first step. It should then output a new file under data/reference.fna that includes only the characters: A, T, C, G, N, and . (period) and uses this for the rest of the pipeline.

If you can share your exact input files (GBK and FASTQ), I'll take a loo and try to figure out what is happening. You can email me at the address in the breseq header, and I will send you info for a shared location to copy them to.

Thanks!

**Comment by cfblaeb** [comment]
Have you had any luck in figuring out what the issue is?

**Comment by jeffreybarrick** [comment]
I think both issues are now fixed in v0.30.0. Let me know if not.
https://github.com/barricklab/breseq/releases/tag/v0.30.0
