### ISSUE TITLE
Error loading VCF files into IGV

### ISSUE THREAD

**Issue by jeffreybarrick** [barricklab/breseq#110]
From user: “The provided VCF file is malformed at approximately line number 4685: BUG: log10PError cannot be > 0 : 1.0”

**Comment by jakubjulian** [comment]
I had the same problem. For me it was a negative score for some variants

**Comment by jeffreybarrick** [comment]
Can you confirm: did you experience the problem with the current version of _breseq_ (v0.35.0) or with a previous version?

**Comment by jakubjulian** [comment]
Not related to _breseq_, but the issue refers to IGV and my answer can help someone, because for me the same message from IGV was caused by a negative score, and this issue was closed without answering what the error was caused

**Comment by jeffreybarrick** [comment]
OK. Just wanted to make sure that the error was not a malformed VCF file generated by _breseq_.
