### ISSUE TITLE
out_of_range error when merging gd files

### ISSUE THREAD

**Issue by vscooper** [barricklab/breseq#111]
Hi Jeff, seen this error previously? It seems to be unique to this analysis on our server (ie other runs complete successfully) but I'd like to diagnose. I've already tried to "polish" the reference genome and looked for but not found a permissions error. Thanks!

`+++   NOW PROCESSING Output
Creating merged genome diff evidence file...
Predicting mutations from evidence...
Annotating mutations...
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 3080)
Aborted (core dumped)`

**Comment by jeffreybarrick** [comment]
Hi Vaughn,
Not aware of this particular issue, it must have to do with a mutation in that particular sample. I'll email you info so you can upload things for me to reproduce and fix.
Thanks!

**Comment by jeffreybarrick** [comment]
User reported work-around. Bug may still exist.
