### ISSUE TITLE
Some mutations rejected despite being predicted above cutoff threshold

### ISSUE THREAD

**Issue by vr1087** [barricklab/breseq#112]
Hi Jeff, I'm seeing some mutations listed as marginal despite having a frequency above the cutoff threshold. Out of 286 data sets I found 296 marginal predictions rejected due to 'Frequency below cutoff threshold' even though their predicted frequency was above the cutoff. The _same_ breseq parameters were used for all data sets and have been listed below. These mutations often seem to be in homopolymers and are indeed predicted as 100% in other samples from time-course experiments. 

Any idea why this is happening? Bug maybe?

```
breseq 
--polymorphism-prediction 
--max-displayed-reads 300 
--polymorphism-frequency-cutoff 0.1 
--polymorphism-reject-indel-homopolymer-length 0 
--polymorphism-reject-surrounding-homopolymer-length 0 
-r reference.gb 
-o breseq_out
read1.fastq.gz
read2.fastq.gz

```
An example evidence page has been attached.
[BRESEQ _Evidence.pdf](https://github.com/barricklab/breseq/files/751955/BRESEQ._Evidence.pdf)

**Comment by jeffreybarrick** [comment]
Which version of _breseq_ are you using?

**Comment by vr1087** [comment]
I am using breseq 0.28.1

**Comment by jeffreybarrick** [comment]
Please, try to re-run one of the problem data sets with v0.29.0 and see if the problem persists. There were some relevant changes in the code in that update.

**Comment by vr1087** [comment]
It's been a few months, but I've reanalyzed all data with breseq v0.30.0 using the same parameters as above. I now have ~450 samples and out of those I found zero marginal predictions that were above the frequency cutoff. I'm convinced this bug was fixed. Thank you!

**Comment by jeffreybarrick** [comment]
Great. Thanks for the update!
