### ISSUE TITLE
breseq 0.30 Linux binary is not compatible with HPCC running gcc 4.8.5

### ISSUE THREAD

**Issue by rohanmaddamsetti** [barricklab/breseq#114]
I asked the research computing people to add breseq 0.30 as a module to our HPCC. However I get the following error message:

breseq: /opt/gcc/4.8.5/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by breseq)

gcc 4.8.5 is the current version on our system (also the default bundled with anaconda), and I'm guessing is the compiler used to build the 0.30 Linux binary is later. I asked the computing staff to install breseq from source to resolve this issue, so I mainly want to give a heads up that the default 0.30 Linux binary doesn't run on our HPCC.

**Comment by jeffreybarrick** [comment]
Hi Rohan - Thanks for the info. I found an older version of GCC and compiled a new binary with that – on a system where I'd previously seen this incompatibility myself. Hopefully this can be useful in the future or to others.
