### ISSUE TITLE
Mutation counts are less in COUNT compared to the counts in Predicted mutations or gd

### ISSUE THREAD

**Issue by lilitto** [barricklab/breseq#115]
Hi Jeffrey,

I used the polymorphism mode to predict mutations in "metagenomic" populations. I have a long list of mutations for each population in output html and gd files, as well as gdtools COMPARE table, though the gdtools COUNT is resulting in a very little number of total mutations per each population. Could you please explain this for me?

Thanks in advance

**Comment by jeffreybarrick** [comment]
By default gdtools COUNT only counts consensus (100%) mutations. Pass the -p flag and it should count the polymorphic mutations as well. This isn't an option that we use a lot, so let me know if you experience any other weirdness.

**Comment by lilitto** [comment]
Thanks a mill, it worked like magic!
Regards
