### ISSUE TITLE
Fatal error Result code: 256, LINE: 1384 - installed with conda

### ISSUE THREAD

**Issue by parkerdj** [barricklab/breseq#117]
Hi Jeff,

Installed all components: bowtie2 (2.2.8), r (3.3.1), breseq (0.29.0) with conda/bioconda.

I ran breseq with the --no-junction-prediction option. I am stuck on this error message:

+++   NOW PROCESSING Output
Creating merged genome diff evidence file...
Predicting mutations from evidence...
Annotating mutations...
Drawing coverage plots...
Creating coverage plot for region: CP007800:1-4188369
Error in bitmap(out_file, height = 6, width = 11, type = "png16m", res = 72,  : 
  GhostScript was not found
Execution halted
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error running command:
[system] R --vanilla in_file=AG174_2.gb/output/evidence/7985.coverage.tab out_file=AG174_2.gb/output/evidence/CP007800.overview.png pdf_output=0 total_only=0 window_start=1 window_end=4188369 avg_coverage=0.0 fixed_coverage_scale=0 < /Users/darrenparker/anaconda/bin/../share/breseq//plot_coverage.r > AG174_2.gb/output/evidence/7985.r.log
Result code: 256
FILE: ./libbreseq/common.h   LINE: 1384
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Thinking this is a install location error, or a version issue with R 3.3.1?

**Comment by jeffreybarrick** [comment]
This seems like a problem with your R install. 

It looks like it is not installing some–apparently optional for R–dependency (ghostscript) that is needed, probably for plotting to PDF output. I'd try installing that directly, R in a different way, or maybe a different version of the R package.

**Comment by DevikaBhave** [comment]
Any suggestions with this error? Trying to run the demo files.
I am using Breseq 0.30.1 , bowtie2  :: version 2.3.2, R :: version 3.3.2 
================================================================================
breseq 0.30.1     http://barricklab.org/breseq

Active Developers: Barrick JE, Deatherage DE
Contact:           <jeffrey.e.barrick@gmail.com>

breseq is free software; you can redistribute it and/or modify it under the
terms the GNU General Public License as published by the Free Software 
Foundation; either version 2, or (at your option) any later version.

Copyright (c) 2008-2010 Michigan State University
Copyright (c) 2011-2016 The University of Texas at Austin

If you use breseq in your research, please cite:

  Deatherage, D.E., Barrick, J.E. (2014) Identification of mutations
  in laboratory-evolved microbes from next-generation sequencing
  data using breseq. Methods Mol. Biol. 1151: 165–188.

If you use structural variation (junction) predictions, please cite:

  Barrick, J.E., Colburn, G., Deatherage D.E., Traverse, C.C.,
  Strand, M.D., Borges, J.J., Knoester, D.B., Reba, A., Meyer, A.G. 
  (2014) Identifying structural variation in haploid microbial genomes 
  from short-read resequencing data using breseq. BMC Genomics 15:1039.
================================================================================
---> bowtie2  :: version 2.3.2 [/home/bhave/.linuxbrew/bin/bowtie2]
---> R        :: version 3.3.2 [/data/modules/R/3.3.2/bin/R]
+++   NOW PROCESSING Read and reference sequence file input
  READ FILE::SRR030257_1
    Converting/filtering FASTQ file...
    Original base quality format: SANGER New format: SANGER
    Original reads: 3800180 bases: 136806480
    Filtered reads:      19 bases:       684 (≥50.0% bases N)
    Filtered reads:   60951 bases:   2194236 (≥90.0% same base)
    Analyzed reads: 3739210 bases: 134611560
  READ FILE::SRR030257_2
    Converting/filtering FASTQ file...
    Original base quality format: SANGER New format: SANGER
    Original reads: 3800180 bases: 136806480
    Filtered reads:     369 bases:     13284 (≥50.0% bases N)
    Filtered reads:   47630 bases:   1714680 (≥90.0% same base)
    Analyzed reads: 3752181 bases: 135078516
  ::TOTAL::
    Original reads: 7600360 bases: 273612960
    Analyzed reads: 7491391 bases: 269690076
[samtools] faidx Clonal_Output2/data/reference.fasta
  REFERENCE: REL606
  LENGTH: 4629812
+++   NOW PROCESSING Read alignment to reference genome
[system] bowtie2-build -q Clonal_Output2/data/reference.fasta Clonal_Output2/02_reference_alignment/reference
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error running command:
[system] bowtie2-build -q Clonal_Output2/data/reference.fasta Clonal_Output2/02_reference_alignment/reference
Result code: 132
FILE: libbreseq/common.h   LINE: 1384
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jeffreybarrick** [comment]
Try running the command that is failing in your terminal (from the same path from which you were running _breseq_):

`bowtie2-build -q Clonal_Output2/data/reference.fasta Clonal_Output2/02_reference_alignment/reference`

This will let us know if the problem is in _breseq_, with some part of your _bowtie2_ install, or with the input files, hopefully.

**Comment by jeffreybarrick** [comment]
Hope you resolved this. If not, feel free to follow up.
