### ISSUE TITLE
failed to generate html files

### ISSUE THREAD

**Issue by pchienUMASS** [barricklab/breseq#118]
I apologize if this is a trivial issue, but after running what looks like a successful breseq run, there are no html files in the output directory.  There's an output.gd, a log.txt file and two folders.  Any thoughts?

**Comment by shenwei356** [comment]
Please paste the content of  log.txt on http://gist.github.com to provide more details.

**Comment by pchienUMASS** [comment]
the log.txt file only contains the breseq command line call (single line).  I pasted the output content on gist (https://gist.github.com/pchienUMASS/eb882c2adf03190126dcae6a1f7178b3.js")  

I'm running breseq on a linux cluster and the systems administrator used breseq-0.30.0-Linux-x86-64.tar.gz compiled binary for installing.  I ran the breseq job as a batch job, does it need to be run in an interactive mode?

**Comment by shenwei356** [comment]
The link should be https://gist.github.com/pchienUMASS/eb882c2adf03190126dcae6a1f7178b3

It said

```
+++   NOW PROCESSING Polymorphism statistics
[system] R --vanilla total_length=4042929 in_file=./08_mutation_identification/polymorphism_statistics_input.tab out_file=./08_mutation_identification/polymorphism_statistics_output.tab qual_file=./08_mutation_identification/error_counts.tab < /share/pkg/breseq/0.30.0/bin/../share/breseq//polymorphism_statistics.r > ./08_mutation_identification/polymorphism_statistics_output.log
+++   NOW PROCESSING Output
Creating merged genome diff evidence file...
Predicting mutations from evidence...
Annotating mutations...
Drawing coverage plots...
Creating coverage plot for region: NC_011916:1-4042929
Error in .External2(C_X11, paste("png::", filename, sep = ""), g$width,  : 
 unable to start device PNG
Calls: png
In addition: Warning message:
In png(out_file, height = 6, width = 11, units = "in", res = 72,  :
 unable to open connection to X11 display ''
Execution halted
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error running command:
[system] R --vanilla in_file=./output/evidence/12459.coverage.tab out_file=./output/evidence/NC_011916.overview.png pdf_output=0 total_only=0 window_start=1 window_end=4042929 avg_coverage=0.0 fixed_coverage_scale=0 < /share/pkg/breseq/0.30.0/bin/../share/breseq//plot_coverage.r > ./output/evidence/12459.r.log
Result code: 256
FILE: libbreseq/common.h   LINE: 1384
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

It seems that your cluster node does not have `X`. Please ask the system administrator to install it.
Some other pakcage like `libpng-devel` may also need to be installed.

**Comment by pchienUMASS** [comment]
Many thanks - I'll see what we can do.

**Comment by pchienUMASS** [comment]
working well now.  solution was to go into interactive mode after doing processing in batch mode with x11 forwarding on

Thanks!

**Comment by jeffreybarrick** [comment]
Thanks for the help troubleshooting, Wei!

Glad it's working, Peter. If doing things this way is annoying, it should be possible to change the R install so that it will work without being in interactive mode.

**Comment by ytalhatamer** [comment]
I have the same problem. I do the processing in batch in our cluster and it fails at the same stage. Do you think is it possible to do X11 requiring steps separately? (if so how?). Or is there any flag that can be given to prevent process from failing at the last step. (--brief-html-output didn't work) Sth like --no-X11. 

Thanks

**Comment by pchienUMASS** [comment]
we were able to fix this by logging in after the batch fails using ssh -X (to enable X11 forwarding), running breseq again (the batch job) but making sure to keep the session active, it would start at the failure point and sailed right past.. good luck!

**Comment by jeffreybarrick** [comment]
Hi everyone. I'd like to take a try at resolving this so that _breseq_ works with R that has been installed with whatever combination of graphics capabilities. If you could post the output of the R command `capabilities()` on your systems under the relevant run conditions, that would help me make sure I am taking care of all cases.

So, far I will test these two R environments:
```
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
       TRUE        TRUE       FALSE        TRUE       FALSE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE       FALSE        TRUE        TRUE        TRUE        TRUE
```
or
```
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
      FALSE       FALSE       FALSE        TRUE       FALSE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE       FALSE       FALSE        TRUE        TRUE        TRUE 
```

**Comment by jeffreybarrick** [comment]
I believe I've fixed this issue in commit https://github.com/barricklab/breseq/commit/a1cbf95ffc42dbafb1289c78dfc456cc71c39a1d.

If anyone on this thread who was having a problem can test it on their system, that would be great. If you'd like me to create and post a temporary source package for testing, let me know.

**Comment by dannagifford** [comment]
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
       TRUE        TRUE       FALSE       FALSE       FALSE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE        TRUE        TRUE       FALSE        TRUE        TRUE

Note tcltx = FALSE

With this setup I do get no-display-related X11 problems, but I was able to work around them by emulating a virtual X server with xvfb-run

**Comment by cyrusmallon** [comment]
Hi Jeffrey,
Thank you very much for issuing a commit and tackling the X11 problem. Might it indeed also be possible to post a temporary source package? I have the same X11 problem, as it's not installed on our cluster's nodes. I don't have expertise in C++, so I'm quite hesitant to start changing the source code, even with the recent commit you issued. If your able to post a new temp source package I could test it right away.
Thank you and best wishes,
Cyrus

**Comment by jeffreybarrick** [comment]
Here's the temporary source package:
https://barricklab.org/release/breseq/breseq-0.34.1a-Source.tar.gz
Let me know if it solves your issue.

**Comment by cyrusmallon** [comment]
Wow, thanks for the quick response! I'll give it a try right now!

**Comment by cyrusmallon** [comment]
The temporary source package is working! I ran a job last night without any errors. Thank you very much for the fix!
