### ISSUE TITLE
out_of_range error while Creating merged genome diff evidence file...

### ISSUE THREAD

**Issue by MuntasirAli** [barricklab/breseq#119]
Predicting mutations from evidence...
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted (core dumped)

**Comment by jeffreybarrick** [comment]
I need more info to help.

If you email me at the address in the _breseq_ header I can arrange for you to upload the data files that are failing to a shared folder. I'll need the command line that you used and the version of _breseq_ as well.

Thanks!

**Comment by jeffreybarrick** [comment]
We have fixed a number of similar issues since this was reported. I hope they help with the problem, but please follow up if not.
