### ISSUE TITLE
Fatal error in breseq: error in writing GenomeDiff output?

### ISSUE THREAD

**Issue by rohanmaddamsetti** [barricklab/breseq#122]
Any idea what's happening here?

Command I run: 
breseq -p -j 12 --cnv -r ../../../references/REL606.7.gbk -o . ../../../data/20160120_DNASeq_PE/RM3-130-8_AGTTCC_L001_R1_001.fastq ../../../data/20160120_DNASeq_PE/RM3-130-8_AGTTCC_L001_R2_001.fastq

*end of log file follows*
...
    POSITION:4610000
    POSITION:4620000
+++   NOW PROCESSING Polymorphism statistics
[system] R --vanilla total_length=4629812 in_file=./08_mutation_identification/polymorphism_statistics_input.tab out_file=./08_mutation_identification/polymorphism_statistics_output.tab qual_file=./08_mutation_identification/error_counts.tab < /opt/breseq-0.30.0/bin/../share/breseq//polymorphism_statistics.r > ./08_mutation_identification/polymorphism_statistics_output.log
+++   NOW PROCESSING Predicting copy number variation
Performing tiling...
  1: Identification tile size       500 bp
  2: Edge optimization tile size     10 bp
Smoothing significant regions...
+++   NOW PROCESSING Output
Creating merged genome diff evidence file...
Predicting mutations from evidence...

>>> Error(s) in GenomeDiff format. FILE:  <<<
>>ERROR: Attempt to add duplicate of this existing entry from line NA:
INS<tab>9<tab>4335<tab>REL606<tab>607327<tab>G<tab>frequency=2.24141598e-01<tab>insert_position=1
Add a 'unique' tag to one if this is intentional.
>>LINE:     0
INS<tab>10<tab>4336<tab>REL606<tab>607327<tab>G<tab>frequency=2.24139214e-01<tab>insert_position=1

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Fatal formatting error in GD file being written: ./output/output.gd
FILE: genome_diff.cpp   LINE: 2338
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jeffreybarrick** [comment]
Yes: --cnv mode is not operational yet. Don't use it.

**Comment by rohanmaddamsetti** [comment]
Hi Jeff, I still get the same error without the --cnv flag.

I ran: breseq -p -j 12 -r ../../../references/REL606.7.gbk -o . ../../../data/20160120_DNASeq_PE/RM3-130-8_AGTTCC_L001_R1_001.fastq ../../../data/20160120_DNASeq_PE/RM3-130-8_AGTTCC_L001_R2_001.fastq

and I get this:
...
+++   NOW PROCESSING Output
Creating merged genome diff evidence file...
Predicting mutations from evidence...

>>> Error(s) in GenomeDiff format. FILE:  <<<
>>ERROR: Attempt to add duplicate of this existing entry from line NA:
INS<tab>9<tab>4335<tab>REL606<tab>607327<tab>G<tab>frequency=2.24141598e-01<tab>insert_position=1
Add a 'unique' tag to one if this is intentional.
>>LINE:     0
INS<tab>10<tab>4336<tab>REL606<tab>607327<tab>G<tab>frequency=2.24139214e-01<tab>insert_position=1

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Fatal formatting error in GD file being written: ./output/output.gd
FILE: genome_diff.cpp   LINE: 2338
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jeffreybarrick** [comment]
Hi Rohan,

This duplicate INS problem is fixed in the current repository version with some commits past v0.30.0. (Output using this version with your data on REL606.6 was fine.) I will roll a new v0.30.1 release in a day or two that will include that updated code.

Cheers,
--Jeff
