### ISSUE TITLE
breseq breaks on N. gonorrhoeae data

### ISSUE THREAD

**Issue by rohanmaddamsetti** [barricklab/breseq#123]
Hi Jeff,

I ran breseq on a clinical isolate of N. gonorrhoeae (SRR3361307 in the SRA archive) for variant calling. breseq calls the entire genome as a deletion. I attached the log file from the run. On line 68, 94% of reads align > 1 time. On line 98, most reads have split alignments. Perhaps that's where things start to get weird? Is this genome simply too diverged from the FA1090 reference genome, and so I should use a different tool?
 
[gonorrhoeae-breseq-fail.txt](https://github.com/barricklab/breseq/files/1030716/gonorrhoeae-breseq-fail.txt)

**Comment by jeffreybarrick** [comment]
I don't have any problems running SRR3361307 data against the reference cited for that data in the SRA record: Neisseria gonorrhoeae NCCP11945 (GenBank:CP001050). It looks like there is something very wrong with your choice of reference sequence. Reads should always align in the first pass run of bowtie2 and you have 0% of reads aligning there. The split reads aligning in the second step with very relaxed matching parameters are surely spurious. I get 96% of reads mapping with the correct reference.

**Comment by rohanmaddamsetti** [comment]
OK--thanks Jeff!

**Comment by rohanmaddamsetti** [comment]
Hi Jeff, 

I'm still having problems with running breseq on the SRR3361307 data, even with the reference sequence you suggested. Is my genbank file in a format breseq doesn't like (full genbank file including sequence) ? I've attached the log file and the reference genbank file. 

I've run breseq on E. coli data on this cluster without problems, but I haven't run reads in *.fastq.gz format before. I feel like it's unlikely this is the issue though.

Cheers,
Rohan

log file: 
[gonorrhea-breseq-fail2.txt](https://github.com/barricklab/breseq/files/1039321/gonorrhea-breseq-fail2.txt)

reference:
[gonorrhoeae-NCCP11945.gb.txt](https://github.com/barricklab/breseq/files/1039322/gonorrhoeae-NCCP11945.gb.txt)

**Comment by jeffreybarrick** [comment]
There is no problem with the GenBank file.

How are you downloading data from the SRA?

I am downloading the FASTQ files from the ENA, here:
http://www.ebi.ac.uk/ena/data/view/SRR3361307

**Comment by rohanmaddamsetti** [comment]
I used the sratoolkit:


fastq-dump --gzip --outdir ./data SRR3361307


I'll try on the FASTQ files from the ENA to see if the issue is with the
data download method.

**Comment by rohanmaddamsetti** [comment]
Yep, looks like the issue isn't with breseq, but with the fastq files downloaded with this fastq-dump command. breseq worked fine for me with the ENA download. Thanks for the help, and I'll continue this thread if this issue continues.

**Comment by rohanmaddamsetti** [comment]
I got breseq working on these SRA data. Basically the problem is that it's hard to use fastq-dump unless you already know how to use it. In case others have similar problems when using sratoolkit, I used this command to get the read data for breseq:

fastq-dump --outdir fastq --gzip --skip-technical  --readids --read-filter pass --dumpbase --split-files --clip SRR_ID

from this blog post: https://edwards.sdsu.edu/research/fastq-dump/

**Comment by jeffreybarrick** [comment]
Good to know!
