### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by abrozzi** [barricklab/breseq#126]
breseq -r stLMTB11381.fasta -j 8 DNA-4_S4_L001_R1_001.fastq DNA-4_S4_L001_R2_001.fastq 
================================================================================
breseq 0.27.1  revision 87c22d663cc3   http://barricklab.org/breseq

Active Developers: Barrick JE, Deatherage DE
Contact:           <jeffrey.e.barrick@gmail.com>

breseq is free software; you can redistribute it and/or modify it under the
terms the GNU General Public License as published by the Free Software 
Foundation; either version 2, or (at your option) any later version.

Copyright (c) 2008-2010 Michigan State University
Copyright (c) 2011-2015 The University of Texas at Austin

If you use breseq in your research, please cite:

  Deatherage, D.E., Barrick, J.E. (2014) Identification of mutations
  in laboratory-evolved microbes from next-generation sequencing
  data using breseq. Methods Mol. Biol. 1151: 165–188.

If you use structural variation (junction) predictions, please cite:

  Barrick, J.E., Colburn, G., Deatherage D.E., Traverse, C.C.,
  Strand, M.D., Borges, J.J., Knoester, D.B., Reba, A., Meyer, A.G. 
  (2014) Identifying structural variation in haploid microbial genomes 
  from short-read resequencing data using breseq. BMC Genomics 15:1039.
================================================================================
---> bowtie2  :: version 2.2.4 [/home/ab552791/apps/bowtie2-2.2.4/bowtie2]
---> R        :: version 3.2.2 [/projects/GENOMICS/APPLICATIONS/R-3.2.2/bin/R]
--- ALREADY COMPLETE Read and reference sequence file input
Segmentation fault

Where shall I look at to find what's wrong?

-A

**Comment by jeffreybarrick** [comment]
I assume this also occurs if you start the output in a clean folder, so that it doesn't have any ALREADY COMPLETE messages?

Can you paste the first few lines of your FASTQ file and reference file you are using so that we can take a look? Something must be unexpected about them.

**Comment by jeffreybarrick** [comment]
Closing issue. Not enough detail provided to reproduce problem.
