### ISSUE TITLE
Segmentation Fault, Result code 35584

### ISSUE THREAD

**Issue by lauj8** [barricklab/breseq#127]
Hi, I've encountered the error below by calling breseq (version breseq-0.30.0-Linux-x86_64) as:

breseq -r JLA4_ordered_PROKKA.gbk -j 5 -o JLA4_breseq/ -p HV04-10_001_1P.fastq HV04-10_001_2P.fastq

+++   NOW PROCESSING Re-alignment to junction candidates
[system] bowtie2-build -q JLA4_breseq//03_candidate_junctions/candidate_junction.fasta JLA4_breseq//04_candidate_junction_alignment/candidate_junction
Building a SMALL index
Segmentation fault (core dumped)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error running command:
[system] bowtie2-build -q JLA4_breseq//03_candidate_junctions/candidate_junction.fasta JLA4_breseq//04_candidate_junction_alignment/candidate_junction
Result code: 35584
FILE: libbreseq/common.h   LINE: 1384
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I'm not sure what this means, or if there is a way to fix it. Any insight would be appreciated!

**Comment by jeffreybarrick** [comment]
Hi, can you send to the email address in the _breseq_ header (or post here) a copy of the file: breseq//03_candidate_junctions/candidate_junction.fasta ?

**Comment by jeffreybarrick** [comment]
Closing issue. No input files provided to reproduce crash.
