### ISSUE TITLE
breseq 0.30.2 dies on F-plasmid reference sequence

### ISSUE THREAD

**Issue by rohanmaddamsetti** [barricklab/breseq#128]
Hi Jeff, 

breseq 0.30.2 doesn't like the F-plasmid reference sequence. How should I handle this? Is there an easy way to edit the gbk file?

Thanks,
Rohan

....
[samtools] faidx ../breseq-assemblies/F-plasmid-ref-runs/donors/REL288/data/reference.fasta
  REFERENCE: NC_002483
  LENGTH: 99159
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Repeat feature must have only one location: D616_p97104
FILE: reference_sequence.cpp   LINE: 684
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Backtrace with 7 stack frames.
breseq() [0x4300d6]
breseq() [0x5a839f]
breseq() [0x5b6d21]
breseq() [0x41e294]
breseq() [0x447e38]
/lib64/libc.so.6(__libc_start_main+0xfd) [0x2b3d14ae9d1d]
breseq() [0x40fb75]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

[F-plasmid.gbk.txt](https://github.com/barricklab/breseq/files/1166719/F-plasmid.gbk.txt)

**Comment by jeffreybarrick** [comment]
Please rename the duplicates so that they have unique locus_tags & names, e.g., gene_1 and gene_2

For example, change this secone one:
```
     repeat_region   1259..1261
                     /gene="finO"
                     /locus_tag="D616_p97104"
                     /old_locus_tag="Fpla003"
                     /note="duplicated sequence by insertion of IS3"
```

to this:
```
     repeat_region   1259..1261
                     /gene="finO_2"
                     /locus_tag="D616_p97104_2"
                     /old_locus_tag="Fpla003"
                     /note="duplicated sequence by insertion of IS3"
```

I think there's a third one to also change, but you get the idea. If two features have the same locus_tag, then they need to have the same coordinates as well.

**Comment by rohanmaddamsetti** [comment]
Great, thanks Jeff!
