### ISSUE TITLE
gdtool error

### ISSUE THREAD

**Issue by roshanbernard** [barricklab/breseq#129]
Hi,

I am not able to run the gdtools. I got the below error msg. Any solutions?...

thanks

Rosh

> $ gdtools COMPARE -o compare.html -r GCF_000240185.1_ASM24018v2_genomic.gbff Ctrl.gd Sample.gd
============================================================================
breseq 0.30.2     http://barricklab.org/breseq

Active Developers: Barrick JE, Deatherage DE
Contact:           <jeffrey.e.barrick@gmail.com>

breseq is free software; you can redistribute it and/or modify it under the
terms the GNU General Public License as published by the Free Software 
Foundation; either version 2, or (at your option) any later version.

Copyright (c) 2008-2010 Michigan State University
Copyright (c) 2011-2016 The University of Texas at Austin

If you use breseq in your research, please cite:

  Deatherage, D.E., Barrick, J.E. (2014) Identification of mutations
  in laboratory-evolved microbes from next-generation sequencing
  data using breseq. Methods Mol. Biol. 1151: 165–188.

If you use structural variation (junction) predictions, please cite

  Barrick, J.E., Colburn, G., Deatherage D.E., Traverse, C.C.,
  Strand, M.D., Borges, J.J., Knoester, D.B., Reba, A., Meyer, A.G. 
  (2014) Identifying structural variation in haploid microbial genomes 
  from short-read resequencing data using breseq. BMC Genomics 15:1039.

***** Begin ANNOTATE/COMPARE ***

    Reading input reference sequence files
        GCF_000240185.1_ASM24018v2_genomic.gbff

    Reading input GD file: Ctrl.gd

>>> Error(s) in GenomeDiff format. FILE: Ctrl.gd <<<
>>ERROR: Expected positive integral value for field 5: [position] instead of [-32177].
>>LINE:    15
DEL<tab>3<tab>208<tab>NC_016839<tab>-32177<tab>105974
>>ERROR: Expected positive integral value for field 5: [position] instead of [-4087851].
>>LINE:    19
DEL<tab>7<tab>211<tab>NC_016845<tab>-4087851<tab>5333942

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Parse errors in loading GenomeDiff File. Not safe to continue
FILE: genome_diff.cpp   LINE: 1851
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Backtrace with 8 stack frames.
gdtools() [0x457bfe]
gdtools() [0x4b86a8]
gdtools() [0x4b8edf]
gdtools() [0x4439a1]
gdtools() [0x445f8c]
gdtools() [0x408994]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f7d2a775830]
gdtools() [0x4161d9]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**

**Comment by jeffreybarrick** [comment]
Hi, thanks for the bug report,

This command is failing because one of the lines in your input GenomeDiff file has a negative position in the genome which shouldn't be allowed. Was that GenomeDiff file generated by a _breseq_ run or manually edited?

If it's from _breseq_ I will probably need to look at your reference file or know how it was downloaded/generated to figure out what is going on. My first thought is that something is off with some of the features there. You can email me at the address in the _breseq_ header if you want to followup by sending a file.

Thanks!

**Comment by rohanmaddamsetti** [comment]
Hi Jeff,

I'm now getting a similar error in one of my breseq runs.

breseq now erroneously calls the entire F plasmid as a deletion, and assigns a negative start position to the deletion (something like –50000). I've run these data before without problems, in the past breseq has correctly called the presence of the F plasmid in this Hfr K-12 strain.

Can you take a look when you get the chance? I've uploaded the read data to the same Box folder as before. 

Thanks for your help!
Rohan

**Comment by jeffreybarrick** [comment]
Are you using the most up-to-date code? I fixed this particular issue.

**Comment by rohanmaddamsetti** [comment]
I got this message running breseq/0.30.2 with the coverage_distribution.R
bug fix on our computing cluster.

I see that this fix is described in the ChangeLog, but that 0.30.3 is not
yet listed in the Releases on github.

Should I wait for 0.30.3 to go live or should I ask IT to install breseq on
the cluster from the master branch?

**Comment by jeffreybarrick** [comment]
Let me verify that it runs your current data and then I can release a v0.30.3.

**Comment by rohanmaddamsetti** [comment]
Awesome, thanks!

**Comment by jeffreybarrick** [comment]
Released v0.31.0 fixes.
