### ISSUE TITLE
R coverage distribution

### ISSUE THREAD

**Issue by rbonnet** [barricklab/breseq#133]
Dear all,

I used breseq with illumina data against a close related E. coli reference genome assembled from Illumina data with spades and then annotated by RAST. Something bad occured during preliminary analysis of coverage distribution with NA values in R: 

"../..
  REFERENCE: ctg_99
  LENGTH: 897
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/0.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/0.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/0.coverage.pdf deletion_propagation_pr_cutoff=0.00140971
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/1.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/1.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/1.coverage.pdf deletion_propagation_pr_cutoff=0.00136437
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/2.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/2.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/2.coverage.pdf deletion_propagation_pr_cutoff=0.00074182
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/3.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/3.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/3.coverage.pdf deletion_propagation_pr_cutoff=0.000140407
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/4.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/4.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/4.coverage.pdf deletion_propagation_pr_cutoff=0.001001
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/5.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/5.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/5.coverage.pdf deletion_propagation_pr_cutoff=9.88401e-05
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/6.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/6.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/6.coverage.pdf deletion_propagation_pr_cutoff=7.5295e-05
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/7.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/7.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/7.coverage.pdf deletion_propagation_pr_cutoff=0.000215216
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/8.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/8.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/8.coverage.pdf deletion_propagation_pr_cutoff=0.000167585
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/9.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/9.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/9.coverage.pdf deletion_propagation_pr_cutoff=0.0011317
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/10.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/10.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/10.coverage.pdf deletion_propagation_pr_cutoff=0.000508644
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/11.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/11.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/11.coverage.pdf deletion_propagation_pr_cutoff=0.00190209
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/12.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/12.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/12.coverage.pdf deletion_propagation_pr_cutoff=0.00119694
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/13.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/13.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/13.coverage.pdf deletion_propagation_pr_cutoff=0.000740517
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/14.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/14.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/14.coverage.pdf deletion_propagation_pr_cutoff=0.000154386
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/15.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/15.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/15.coverage.pdf deletion_propagation_pr_cutoff=0.000870784
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/16.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/16.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/16.coverage.pdf deletion_propagation_pr_cutoff=0.000950014
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/17.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/17.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/17.coverage.pdf deletion_propagation_pr_cutoff=0.00123655
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/18.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/18.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/18.coverage.pdf deletion_propagation_pr_cutoff=0.000815519
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/19.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/19.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/19.coverage.pdf deletion_propagation_pr_cutoff=0.000770966
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/20.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/20.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/20.coverage.pdf deletion_propagation_pr_cutoff=0.000255571
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/21.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/21.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/21.coverage.pdf deletion_propagation_pr_cutoff=0.000233337
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/22.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/22.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/22.coverage.pdf deletion_propagation_pr_cutoff=0.000618463
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/23.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/23.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/23.coverage.pdf deletion_propagation_pr_cutoff=0.000244403
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/24.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/24.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/24.coverage.pdf deletion_propagation_pr_cutoff=0.00188847
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/25.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/25.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/25.coverage.pdf deletion_propagation_pr_cutoff=0.000635873
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/26.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/26.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/26.coverage.pdf deletion_propagation_pr_cutoff=0.00136386
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/27.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/27.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/27.coverage.pdf deletion_propagation_pr_cutoff=0.00100565
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/28.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/28.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/28.coverage.pdf deletion_propagation_pr_cutoff=0.00171701
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/29.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/29.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/29.coverage.pdf deletion_propagation_pr_cutoff=0.000201069
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/30.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/30.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/30.coverage.pdf deletion_propagation_pr_cutoff=0.00179721
Warning message:
In nlm(f_nb, c(try_mean, try_size), iterlim = 1000, print.level = this.print.level) :
  NA / Inf remplacé par la valeur maximale positive
Warning message:
In qnbinom(deletion_propagation_pr_cutoff, size = size_estimate,  :
  production de NaN
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/31.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/31.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/31.coverage.pdf deletion_propagation_pr_cutoff=0.00202444
Warning message:
In qnbinom(deletion_propagation_pr_cutoff, size = size_estimate,  :
  production de NaN
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/32.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/32.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/32.coverage.pdf deletion_propagation_pr_cutoff=0.00166945
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/33.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/33.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/33.coverage.pdf deletion_propagation_pr_cutoff=0.00194331
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/34.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/34.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/34.coverage.pdf deletion_propagation_pr_cutoff=0.000195857
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/35.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/35.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/35.coverage.pdf deletion_propagation_pr_cutoff=0.00178571
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/36.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/36.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/36.coverage.pdf deletion_propagation_pr_cutoff=0.000148052
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/37.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/37.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/37.coverage.pdf deletion_propagation_pr_cutoff=0.000197681
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/38.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/38.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/38.coverage.pdf deletion_propagation_pr_cutoff=0.000789288
Warning messages:
1: In nlm(f_nb, c(try_mean, try_size), iterlim = 1000, print.level = this.print.level) :
  NA / Inf remplacé par la valeur maximale positive
2: In nlm(f_nb, c(try_mean, try_size), iterlim = 1000, print.level = this.print.level) :
  NA / Inf remplacé par la valeur maximale positive
3: In nlm(f_nb, c(try_mean, try_size), iterlim = 1000, print.level = this.print.level) :
  NA / Inf remplacé par la valeur maximale positive
4: In nlm(f_nb, c(try_mean, try_size), iterlim = 1000, print.level = this.print.level) :
  NA / Inf remplacé par la valeur maximale positive
5: In nlm(f_nb, c(try_mean, try_size), iterlim = 1000, print.level = this.print.level) :
  NA / Inf remplacé par la valeur maximale positive
Warning messages:
1: In nlm(f_p, c(m), print.level = this.print.level) :
  NA / Inf remplacé par la valeur maximale positive
2: In nlm(f_p, c(m), print.level = this.print.level) :
  NA / Inf remplacé par la valeur maximale positive
3: In nlm(f_p, c(m), print.level = this.print.level) :
  NA / Inf remplacé par la valeur maximale positive
4: In nlm(f_p, c(m), print.level = this.print.level) :
  NA / Inf remplacé par la valeur maximale positive
5: In nlm(f_p, c(m), print.level = this.print.level) :
  NA / Inf remplacé par la valeur maximale positive
Error in if (is.nan(deletion_propagation_coverage) || (deletion_propagation_coverage <  : 
  valeur manquante là où TRUE / FALSE est requis
Exécution arrêtée
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error running command:
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 37922_gbk/03_candidate_junctions/38.unique_only_coverage_distribution.tab.r.log distribution_file=37922_gbk/03_candidate_junctions/38.unique_only_coverage_distribution.tab plot_file=37922_gbk/03_candidate_junctions/38.coverage.pdf deletion_propagation_pr_cutoff=0.000789288
Result code: 256
FILE: libbreseq/common.h   LINE: 1477
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
0x00000000004291f7 _ZN6breseq6SYSTEMESsbbb
0x00000000004a1860 _ZN6breseq20CoverageDistribution3fitERNS_8SettingsESsSsd
0x00000000004a2092 _ZN6breseq20CoverageDistribution36analyze_unique_coverage_distr
0x00000000004a2b13 _ZN6breseq20CoverageDistribution37analyze_unique_coverage_distr
0x0000000000420504 _Z21breseq_default_actioniPPc
0x0000000000427155 main
0x00007f28d173af45 __libc_start_main
0x0000000000409eed _start
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

 Have you an idea? How can I fix the problem?

Thanks a lot for help,

Richard

**Comment by jeffreybarrick** [comment]
Hi Richard,

Are you using the newest version of _breseq_ (v0.31.0)? There have been some recent changes to make this coverage-fitting step more robust.

If you are still having the problem with the newest version of _breseq_, can you share some input files that are causing the problem? If you contact me at the email address in the _breseq_ header, I can give you access to a place to upload them.

Thanks!

**Comment by jeffreybarrick** [comment]
Assuming problem is resolved with newer versions. Let me know if not.
