### ISSUE TITLE
Similar to issue 133: Error with coverage_distribution.r

### ISSUE THREAD

**Issue by nickp60** [barricklab/breseq#135]
Hi,
I am getting an error similar to the one mentioned earlier (133):

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error running command:
[system] R --vanilla < /home/cob/breseq-0.31.0-Linux-x86_64/bin/../share/breseq    ```
//coverage_distribution.r > Results/Breseq-20170928/CM9//03_candidate_junctions/27.unique_only_coverage_distribution.tab.r.log distribution_file=Results/Breseq-20170928/CM9//03_candidate_junctions/27.unique_only_coverage_distribution.tab plot_file=Results/Breseq-20170928/CM9//03_candidate_junctions/27.coverage.pdf deletion_propagation_pr_cutoff=0.00300965
Result code: 256
FILE: libbreseq/common.h   LINE: 1477
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
0x00000000004291f7 _ZN6breseq6SYSTEMESsbbb
0x00000000004a1860 _ZN6breseq20CoverageDistribution3fitERNS_8SettingsESsSsd
0x00000000004a2092 _ZN6breseq20CoverageDistribution36analyze_unique_coverage_distr
0x00000000004a2b13 _ZN6breseq20CoverageDistribution37analyze_unique_coverage_distr
0x0000000000420504 _Z21breseq_default_actioniPPc
0x0000000000427155 main
0x00007f8253c1f830 __libc_start_main
0x0000000000409eed _start
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Attached is the stderr and stdout log.  I am using version 0.31.0, on Ubuntu.

Any tips?

[CM9.log](https://github.com/barricklab/breseq/files/1341321/CM9.log)

**Comment by jeffreybarrick** [comment]
Looks like there is an edge case we are not catching:

I think it will be fixed if you change line 467 of `coverage_distribution.r` (under `share/breseq`) from

`  if (is.nan(deletion_propagation_coverage) || (deletion_propagation_coverage < 1)) {`

to

`  if (is.na(deletion_propagation_coverage) || is.nan(deletion_propagation_coverage) || (deletion_propagation_coverage < 1)) {`

Be sure to change the `coverage_distribution.r` file in your install location or re-install from the source after changing the one there.

Let me know if that works.

**Comment by nickp60** [comment]
That did it!  Thanks so much for all your work, and thanks for a great software!

**Comment by jeffreybarrick** [comment]
Fantastic! Fix will be included in the next release.
