### ISSUE TITLE
Error creating coverage plots, Result code: 256

### ISSUE THREAD

**Issue by jlebov** [barricklab/breseq#136]
Hi, I am trying to run Breseq/0.31.0 on some evolved bacterial isolate Illumina data (resulting from experimental evolution) which I am trying to compare to its ancestral strain via consensus mode, and while Breseq/0.31.0 nearly completes this comparison, it fails right at the end, leaving me without an index.html file to view my results. I have pasted my command and results below. I'm not sure why my Breseq/0.31.0 run fails. Can someone please help me resolve this issue?

Thank you very much, Jarrett.

[jlebov@ln1 SeqResults_Isolates]$ breseq -o ./BreseqResults/Consensus_L3_20B-a_q_vs_ancMR1pilon-r -r pilon-based-Prokka_ancMR1wtPacBio-ancMR1tagIllreads/ancMR1pilon_07142017.gff 3_20B_isolate_a.fastq 
================================================================================
breseq 0.31.0     http://barricklab.org/breseq

Active Developers: Barrick JE, Deatherage DE
Contact:           <jeffrey.e.barrick@gmail.com>

breseq is free software; you can redistribute it and/or modify it under the
terms the GNU General Public License as published by the Free Software 
Foundation; either version 2, or (at your option) any later version.

Copyright (c) 2008-2010 Michigan State University
Copyright (c) 2011-2017 The University of Texas at Austin

If you use breseq in your research, please cite:

  Deatherage, D.E., Barrick, J.E. (2014) Identification of mutations
  in laboratory-evolved microbes from next-generation sequencing
  data using breseq. Methods Mol. Biol. 1151: 165–188.

If you use structural variation (junction) predictions, please cite:

  Barrick, J.E., Colburn, G., Deatherage D.E., Traverse, C.C.,
  Strand, M.D., Borges, J.J., Knoester, D.B., Reba, A., Meyer, A.G. 
  (2014) Identifying structural variation in haploid microbial genomes 
  from short-read resequencing data using breseq. BMC Genomics 15:1039.
================================================================================
---> bowtie2  :: version 2.3.3 [/packages/bowtie2/2-2.3.3/bin/bowtie2]
---> R        :: version 3.3.3 [/packages/R/3.3.3_intel-17/bin/R]
--- ALREADY COMPLETE Read and reference sequence file input
--- ALREADY COMPLETE Read alignment to reference genome
--- ALREADY COMPLETE Preprocessing alignments for candidate junction identification
--- ALREADY COMPLETE Preliminary analysis of coverage distribution
--- ALREADY COMPLETE Identifying junction candidates
--- ALREADY COMPLETE Re-alignment to junction candidates
--- ALREADY COMPLETE Resolving alignments with junction candidates
--- ALREADY COMPLETE Creating BAM files
--- ALREADY COMPLETE Tabulating error counts
--- ALREADY COMPLETE Re-calibrating base error rates
--- ALREADY COMPLETE Examining read alignment evidence
--- ALREADY COMPLETE Polymorphism statistics
+++   NOW PROCESSING Output
Creating merged genome diff evidence file...
Predicting mutations from evidence...
  Preparing junctions...
  Predicting mobile element insertions...
  Predicting large deletions...
  Predicting small indels and substitutions from junctions...
  Predicting small indels and substitutions from alignments...
  Making final adjustments to mutations...
  Writing final GD file...
  Writing final VCF file...
Annotating mutations...
Drawing coverage plots...
Creating coverage plot for region: scf7180000000010_quiver_pilon:1-4516729
Error in .External2(C_X11, paste("png::", filename, sep = ""), g$width,  : 
  unable to start device PNG
Calls: png
In addition: Warning message:
In png(out_file, height = 6, width = 11, units = "in", res = 72,  :
  unable to open connection to X11 display ''
Execution halted
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error running command:
[system] R --vanilla in_file=./BreseqResults/Consensus_L3_20B-a_q_vs_ancMR1pilon-r/output/evidence/112191.coverage.tab out_file=./BreseqResults/Consensus_L3_20B-a_q_vs_ancMR1pilon-r/output/evidence/scf7180000000010_quiver_pilon.overview.png pdf_output=0 total_only=0 window_start=1 window_end=4516729 avg_coverage=0.0 fixed_coverage_scale=0 < /gpfs/packages/breseq/0.31.0/bin/../share/breseq//plot_coverage.r > ./BreseqResults/Consensus_L3_20B-a_q_vs_ancMR1pilon-r/output/evidence/112191.r.log
Result code: 256
FILE: libbreseq/common.h   LINE: 1477
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Backtrace with 7 stack frames.
breseq() [0x482f86]
breseq() [0x4841b4]
breseq() [0x539b5a]
breseq() [0x42fd20]
breseq() [0x4097f7]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x2aaaab942c05]
breseq() [0x41af47]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jeffreybarrick** [comment]
Hi Jarrett,

It looks like your installation of R is not typical/complete. It lacks support for producing PNG image output, which is usually present in the base install. Try re-installing or updating R on your machine and let us know if that doesn't help with the issue.

**Comment by jlebov** [comment]
Thanks for the reply. I was running Breseq on a Ubuntu virtual machine that apparently didn't have the required fonts installed. I ran the following command in the terminal on my virtual machine based on some advice found here(https://askubuntu.com/questions/449578/x11-font-adobe-helvetica-s-s-d-face-2-at-size-11-could-no):
"sudo apt-get install t1-xfree86-nonfree ttf-xfree86-nonfree ttf-xfree86-nonfree-syriac xfonts-75dpi xfonts-100dpi"

This command seemed to do the trick. I am now able to complete the run I initially posted about. Thank you very much for your help.

- Jarrett

**Comment by jeffreybarrick** [comment]
Thanks for posting your solution!
