### ISSUE TITLE
tests failing in v0.31.0 on Ubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by flamholz** [barricklab/breseq#137]
I downloaded breseq-0.31.0-Linux-x86_64.tar.gz from the release page, decompressed it, entered the directory and ran "$ ./run_tests.sh". I got the following error.

tests/lambda_mult_ref_read/../common.sh: line 125:  8985 Illegal instruction     (core dumped) ${TESTCMD}
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Failed check
Non-zero error code returned.
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Elapsed time for 'make test': 00:00

**Comment by jeffreybarrick** [comment]
Hi, the precompiled executable for _breseq_ doesn't seem to be compatible with your system, unfortunately.

Please try installing from the source code if you're able:
http://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/installation.html#method-2-source-code-package

I'm hoping to improve the compatibility of the binary at some point in the future. If you'd like to help with that, it would be great to know the output of `uname -a` and `ldd bin/breseq` on your system.

**Comment by flamholz** [comment]
Jeff - I managed to install from source no problem.

here are the results of uname -a 
Linux savage-Studio-XPS-435T 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Since I now have a functioning breseq install, I'm not sure that the results of ldd on that are interesting. But here they are 

$ ldd /usr/local/bin/breseq
	linux-vdso.so.1 =>  (0x00007ffc635f2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fea62fb6000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fea62d9c000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fea62a1a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fea62711000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fea624fb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fea62131000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fea631d3000)

**Comment by jeffreybarrick** [comment]
Thanks!
