### ISSUE TITLE
home-brew install issue

### ISSUE THREAD

**Issue by plasmid02** [barricklab/breseq#138]
Installed breseq using home-brew on my Mac.
Got the following error on my first try

```
breseq 0.30.0     http://barricklab.org/breseq
...
...
---> ERROR Required executable "bowtie2" version 2.0.0-beta7 or later not found.
---> Your version is 2.3.3.1.
---> See http://bowtie-bio.sourceforge.net/bowtie2
---> R        :: version 3.4.1 [/usr/local/bin/R]
```

Appears that my bowtie2 and R versions are later than necessary.  Am I missing something obvious here ?
thanks

tim

**Comment by jeffreybarrick** [comment]
The latest release of Bowtie2 changed the format of its version string in a way that confused _breseq_ (added another decimal place). I released a fix yesterday in _breseq_ v0.31.1. You could also downgrade bowtie2 to a previous version. Sorry for the inconvenience!

**Comment by plasmid02** [comment]
Jeff - Thanks for the super-fast response!  Are you planning to push breseq v0.31.1. to homebrew soon?  (Not planning got run analysis immediately, so I can wait a bit)

**Comment by jeffreybarrick** [comment]
I don't currently maintain the homebrew install... but I'll see if I can submit a pull request for that since this is a major block.

**Comment by jeffreybarrick** [comment]
OK. That was easy – homebrew version is now updated.

**Comment by plasmid02** [comment]
Thanks Jeff!  Up and running again!
