### ISSUE TITLE
Feature request: gdtools SIMULATE-MUTATIONS with mutation spectrum?

### ISSUE THREAD

**Issue by ramiroricardo** [barricklab/breseq#139]
I was considering carrying some simulations using gdtools SIMULATE-MUTATIONS, but I would like to simulate specific numbers of each type of SNP (e.g. 100 A:T, 50 C:G, etc). I do not think this is possible in the current version of the function, but just wanted to check I am correct? and if so, would it be possible to add something this in the future? In the best possible scenario, it would even be possible to simulate based on a gd file of observed mutations.

Thanks,

Ramiro

**Comment by jeffreybarrick** [comment]
Hi Ramiro,

We'll keep it in mind, but we're unlikely to have time to add to the gdtools SIMULATE-MUTATIONS functionality of _breseq_ anytime soon. If you'd like this functionality, I'd suggest that you might be able to write your own script that generates a GD file of the desired random mutations – then use gdtools APPLY to generate the mutated reference genome.

**Comment by jeffreybarrick** [comment]
Closing this old request. This functionality will not be added to core _breseq_, but could be implemented in some kind of extension that generates GD files.
