### ISSUE TITLE
Shared libraries error

### ISSUE THREAD

**Issue by rynguyen2018** [barricklab/breseq#140]
Hi, 
Sorry if this is a dumb question, but, when I try to run breseq, I get this error: 
./breseq: error while loading shared libraries: libunwind-x86_64.so.8: cannot open shared object file: No such file or directory

Any help is appreciated thanks!

**Comment by jeffreybarrick** [comment]
Hello, 

This is the Linux precompiled binary? If so, please try to compile and install _breseq_ from the source code. Unfortunately, we have not yet made the Linux binary very compatible.

**Comment by rynguyen2018** [comment]
Hi, 
I tried doing that and got this error message while running "make": 
make[1]: *** [coverage_distribution.lo] Error 1
make[1]: Leaving directory `/global/home/users/rnguyen2018/Bailey/breseq/breseq-0.31.1/src/c/breseq'
make: *** [all-recursive] Error 1

**Comment by jeffreybarrick** [comment]
Did you follow all of the instructions in the manual?
http://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/installation.html#method-2-source-code-package
