### ISSUE TITLE
mutation on overlapping genes

### ISSUE THREAD

**Issue by ruipspereira** [barricklab/breseq#141]
When a mutation happens in a genome region where two genes overlap, breseq only annotates the mutation for one of them. Would it be possible to make breseq annotate that mutation for all the genes that span the mutated location?

**Comment by meono** [comment]
thanks for the report @ruipspereira. I went back and checked previous results and, to my surprise, there were many missing mutation annotations. It would be great to have them all reported.

**Comment by jeffreybarrick** [comment]
Yes, we'll work on adding this when we have some time.

What types of genomes with so many overlapping genes/features are you working on? Phage?

**Comment by meono** [comment]
Just regular E.coli. I should have made it a bit more clear though: I went over all strains we sequenced over the past 3-4 years. Close to 40 overlap sites were affected, but on several strains. We also had polymorphism setup on several analysis, which compounded it.

**Comment by jeffreybarrick** [comment]
I think I have managed to implement this.

I've put up a pre-release version for testing here:

Mac:
http://barricklab.org/release/breseq/breseq-0.32.0e-MacOSX-10.9+.tar.gz

Source:
http://barricklab.org/release/breseq/breseq-0.32.0e-Source.tar.gz

If you have a chance, it would be great to verify that it's working as expected and not leading to any unexpected issues that are not caught by the standard tests.

**Comment by meono** [comment]
Thanks for the quick update. 
I just checked with a few clonal and a few pool samples we had. For both types, I can see some of the overlap mutations annotated for both genes on the same row on the html output - haven't check how they are on gd files yet. I don't see mutations on overlaps with non-protein-coding RNA features - which might be default behavior for breseq though (please correct me if I'm wrong).

**Comment by jeffreybarrick** [comment]
Thanks for the test runs.

_Breseq_ should pay attention to CDS, RNA, tRNA, and rRNA features. Do you know how your RNA features are annotated in the reference file?

**Comment by meono** [comment]
Right, rRNA and tRNA are always there. I have "ncRNA" features that didn't get picked.

**Comment by jeffreybarrick** [comment]
I'll add "ncRNA" as another type that gets picked up. Cheers.

**Comment by meono** [comment]
Great! thanks a lot :)
