### ISSUE TITLE
segmentation fault during candidate junctions phase

### ISSUE THREAD

**Issue by OwenLeiser** [barricklab/breseq#142]
I've started running into an issue in 0.30.0 (latest available update from Homebrew), during the candidate junction phase. Samtools imports, sorts, and indexes just fine, but after that I get:

[system] R --vanilla < /usr/local/bin//../share/breseq//coverage_distribution.r > ./03_candidate_junctions/0.unique_only_coverage_distribution.tab.r.log distribution_file=./03_candidate_junctions/0.unique_only_coverage_distribution.tab plot_file=./03_candidate_junctions/0.coverage.pdf deletion_propagation_pr_cutoff=2.31777e-05
[system] R --vanilla < /usr/local/bin//../share/breseq//coverage_distribution.r > ./03_candidate_junctions/1.unique_only_coverage_distribution.tab.r.log distribution_file=./03_candidate_junctions/1.unique_only_coverage_distribution.tab plot_file=./03_candidate_junctions/1.coverage.pdf deletion_propagation_pr_cutoff=0.000161198
/Users/leis515/Documents/Bioinformatics/Shell_Scripts/run_breseq.sh: line 64: 66602 Segmentation fault: 11  breseq -r YpCO92_complete_gsq.gbk -j 2 -p $i $i2

A couple of considerations: First, the error copied above is from a run where I've scripted some preprocessing steps (trimmomatic and seqtk for read QA and downsampling) for multiple read pairs, but the same error occurs if I run a read pair individually/manually. Second, the segfault doesn't *always* occur (50-60%) - but when it does, it occurs there. Sometimes I can reduce the number of threads to 1 and get past it, but not always.

Any thoughts?

**Comment by OwenLeiser** [comment]
Forgot to add: thanks for taking the time to troubleshoot these issues with all of us. I really like this program and want it to work every time :)

**Comment by jeffreybarrick** [comment]
Hi Owen! This resembles some issues we fixed in recent versions. [Version 0.31.1 should now be available through Homebrew](http://braumeister.org/repos/Homebrew/homebrew-science/formula/breseq). Can you give that a try and see if this is resolved?

**Comment by OwenLeiser** [comment]
Hey Jeff, it does seem to be working better - although now I'm getting an R error (which I suspect has more to do with my system than the software).

Annotating mutations...
Drawing coverage plots...
Creating coverage plot for region: NC_003143:1-4653728
Error in bitmap(out_file, height = 6, width = 11, type = "png16m", res = 72,  : 
  GhostScript was not found
Execution halted
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error running command:
[system] R --vanilla in_file=./output/evidence/94918.coverage.tab out_file=./output/evidence/NC_003143.overview.png pdf_output=0 total_only=0 window_start=1 window_end=4653728 avg_coverage=0.0 fixed_coverage_scale=0 < /usr/local/bin/../share/breseq//plot_coverage.r > ./output/evidence/94918.r.log
Result code: 256
FILE: ./libbreseq/common.h   LINE: 1479
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
0x000000010557533b _ZN6breseq6SYSTEMENSt3__112basic_stringIcNS0_11char_traitsIcEEN
0x000000010557185a _ZN6breseq15coverage_output4plotERKNSt3__112basic_stringIcNS1_1
0x000000010566e7e1 _ZN6breseq6output13draw_coverageERNS_8SettingsERNS_19cReference
0x000000010552fd3b _Z21breseq_default_actioniPPc
0x0000000105533255 main
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


I'm going to take a crack at re-running some more of the read pairs that seg faulted with 0.30.0 once I get this sorted out. If there's still a problem I'll let you know. Thanks for the help.

**Comment by OwenLeiser** [comment]
Update: it was definitely something with my system. Used brew to just install ghostscript and it works now. Possibly not linked in the brew download as a dependency? Shrug. Like I said I'll test drive 0.31.1 on some of the others and see if it keeps kicking the segfault.

**Comment by jeffreybarrick** [comment]
Thanks for updates and info about the ghostscript dependency. Fingers crossed as far as the seg faults. Breseq only requires the most baseline R install that you would get directly from the R download site, but others have also reported that their versions of R installed through package managers are sometimes missing some of the prereqs for basic graphing/image output.

**Comment by OwenLeiser** [comment]
It seems to be working as advertised now - installing the additional R package through brew wasn't difficult. Thanks for the help.

**Comment by jeffreybarrick** [comment]
Great!
