### ISSUE TITLE
Issue in Source compilation breseq-0.31.1

### ISSUE THREAD

**Issue by Jobeg** [barricklab/breseq#143]
Hello,

I tried to install the new version of breseq (0.31.1).
The configure worked correctly.
When I run the make command I got these errors:

`alignment.cpp: In member function ‘void breseq::tam_file::write_moved_alignment(const breseq::alignment_wrapper&, const string&, uint32_t, const string&, int32_t, int32_t, int32_t, uint32_t, int32_t, int32_t, const breseq::alignment_list&, const breseq::Trims*)’:
alignment.cpp:1037:78: error: no matching function for call to ‘make_pair<char, uint16_t>(char&, int32_t&)’
      pair<char,uint16_t> new_element = make_pair<char,uint16_t>(op, overshoot);
                                                                              ^
In file included from /usr/include/c++/7/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/7/list:60,
                 from libbreseq/common.h:48,
                 from libbreseq/alignment.h:22,
                 from alignment.cpp:19:
/usr/include/c++/7/bits/stl_pair.h:519:5: note: candidate: template<class _T1, class _T2> constexpr std::pair<typename std::__decay_and_strip<_Tp>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
     make_pair(_T1&& __x, _T2&& __y)
     ^~~~~~~~~
/usr/include/c++/7/bits/stl_pair.h:519:5: note:   template argument deduction/substitution failed:
alignment.cpp:1037:78: note:   cannot convert ‘op’ (type ‘char’) to type ‘char&&’
      pair<char,uint16_t> new_element = make_pair<char,uint16_t>(op, overshoot);
                                                                              ^
alignment.cpp:1046:68: error: no matching function for call to ‘make_pair<char, uint16_t>(char&, uint16_t&)’
    pair<char,uint16_t> new_element = make_pair<char,uint16_t>(op, n);
                                                                    ^
In file included from /usr/include/c++/7/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/7/list:60,
                 from libbreseq/common.h:48,
                 from libbreseq/alignment.h:22,
                 from alignment.cpp:19:
`
I am on Ubuntu 17.10 . gcc is in version 7.2.0

I also noticed there is no bin for Linux distributions in this version of breseq.

Many thanks,

**Comment by jeffreybarrick** [comment]
Hi,

I believe I've fixed the compilation error in this pre-release version:
http://barricklab.org/release/breseq/breseq-0.32.0c-Source.tar.gz
If you could check to see if that compiles in your setup, I'd be grateful.

Also, I've posted a Linux version of 0.31.1 if that is more helpful:
https://github.com/barricklab/breseq/releases/tag/v0.31.1
(There are some significant changes in the code in 0.32.0c, which is why it's still pre-release).

**Comment by Jobeg** [comment]
Hi,

The Linux version of 0.31.1 works fine for me now, thanks you!

I also tried to compile the 0.32.0c but I got the following error:
`./libbreseq/json.hpp: In function ‘bool nlohmann::operator<(nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::const_reference, nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::const_reference)’:
./libbreseq/json.hpp:6057:62: error: wrong number of template arguments (1, should be 2)
                     return *lhs.m_value.array < *rhs.m_value.array;
`

**Comment by jeffreybarrick** [comment]
Thanks for the info about the compile problem.

Looks like this was related to something in the newest GCC version (7.2.0) related to json.hpp. Anyway, I've just checked in a fix so that the next release version should compile.
