### ISSUE TITLE
gdtools merge takes very long time

### ISSUE THREAD

**Issue by durrantmm** [barricklab/breseq#147]
I am running gdtools MERGE with the -e flag on 20 different samples, and it is taking a very long time. It seems to be stuck on reading in the second GD file. What is so computationally intensive about this particular tool? I'm using breseq v0.31.1.

Thank you,
- Matt Durrant

**Comment by durrantmm** [comment]
On average, these samples contain ~50000 lines.

**Comment by jeffreybarrick** [comment]
Hi Matt. This step can be slow, but it should still work within at least a few minutes. Is sounds like there may be a bug that is getting things stuck in your case. If you could send those first two files to reproduce the problem (to the email address in the _breseq_ header) that would be helpful.

**Comment by jeffreybarrick** [comment]
Hi Matt, I've checked in code that makes this much quicker:

I've also posted a pre-release version for download here (v0.32.1a):
http://barricklab.org/release/breseq/

Give it a try and let me know if it works better!
