### ISSUE TITLE
gdtools ANNOTATE/COMPARE column names

### ISSUE THREAD

**Issue by plasmid02** [barricklab/breseq#148]
This should be quick but I can't find how to do this in the documentation/ issues

I am using ANNOTATE to make a summary table of multiple gd files.  How can I set the column names to match the individual gd files?    

thanks!

**Comment by jeffreybarrick** [comment]
The column names are taken from two different sources with this priority:

1) If there is a #=TITLE metadata line in the input GD, then that value is used. 
2) Otherwise the GD file name is used (removing the *.gd suffix).

Does that help?

**Comment by plasmid02** [comment]
doh.  Realized the problem was that all my files have the default name: '
output.gd'.  Just needed to rename based on the input strain name.  Thanks!
