### ISSUE TITLE
Question: Is skew still used as a criteria for support in JC prediction?

### ISSUE THREAD

**Issue by yeemey** [barricklab/breseq#149]
The [criteria listed in the documentation](http://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/methods.html#scoring-and-accepting-junctions) doesn't include skew, though it's reported in my results from breseq v0.27.1.

If skew still matters, what does skew = NT mean?

Thank you!

**Comment by jeffreybarrick** [comment]
The word "skew" is not used in the documentation (I should fix this), but it is -log10 of the probability of observing the given position-hash score for a junction given the coverage distribution of the genome as a whole. So when it is <2.0 (same as 0.01 tail probability mentioned in the docs), then the junction is accepted. This assumes coverage across the junction is the same as the rest of the genome (**consensus mode**).

However, in **polymorphism mode** it may be a real junction with lower coverage (if it was only in 10% of the sample, for example), so it doesn't make sense to calculate this score. Instead, it is left as "NT" (Not Tested). Skew is not used as a criterion, and any junction that meets the --junction-minimum-pos-hash-score setting is accepted.
