### ISSUE TITLE
Question Regarding Read Alignment Option: --require-match-fraction

### ISSUE THREAD

**Issue by vr1087** [barricklab/breseq#150]
Does this option take into account the soft-clipped portion of an alignment? If it is supposed to, I think I am seeing evidence for a bug. I set this parameter to 0.95 but I am still seeing variant calls that are only supported by read alignments in which ~half the read is soft-clipped. I am using breseq v0.32.0 and I double check the parameter setting.

![image](https://user-images.githubusercontent.com/7674836/37114269-763af586-220d-11e8-9f58-4689f6f89ed9.png)

**Comment by vr1087** [comment]
This does make sense. Thank you. I found the junction candidate in the output and 95% of each read is, indeed, aligned to the new junction. Both sides are riddled with mismatches, however. I can see why one would want to allow for this, but for some data sets I do not. I want do not want junctions predicted that have mismatches on either side and I do not want polymorphic variants called from those specific mismatches. Would I be able to can control for this by adjusting the --bowtie2-junction parameter alone?

**Comment by jeffreybarrick** [comment]
I'd say the main options are:
1) Turn off junction prediction entirely
2) (As you suggest) adjust the --bowtie2-junction parameter. You could make it resemble the default --bowtie2-stage1 option, for example.
