### ISSUE TITLE
Issue while compilation/installation

### ISSUE THREAD

**Issue by MuntasirAli** [barricklab/breseq#153]
When using the precompiled version:
/opt/breseq-0.32.0-Linux-x86_64/bin]# ./breseq 
./breseq: error while loading shared libraries: libunwind-x86_64.so.8: cannot open shared object file: No such file or directory
When trying to compile the source code (running the make command):
cc1plus: error: unrecognized command line option "-std=c++11"
make[1]: *** [alignment.lo] Error 1
make[1]: Leaving directory `/opt/breseq-0.32.0/src/c/breseq'
make: *** [all-recursive] Error 1

**Comment by jeffreybarrick** [comment]
The Linux precompiled binary is not very compatible at this point for technical reasons.

The compile should work. Based on the error, it is possible that you need to update to a newer version of the compiler that supports C++11. Can you check to see what compiler/version you are using? gcc --version

**Comment by MuntasirAli** [comment]
Apparently requires an upgrade in the GCC from V4.4.7 to GCC V11.3. Our system administrator of the server strongly recommended not to do that. Therefore, is there any other option do I have to use the latest version?

**Comment by jeffreybarrick** [comment]
You don't need the very latest GCC version. There are much earlier GCC versions that support C++11. It looks like GCC 4.8 or later should be sufficient. Your system package manager should let you safely install a different GCC version and temporarily use it before swapping the default back if you are worried about consequences for your system.

**Comment by MuntasirAli** [comment]
Actually I was talking about the server that I use to run the programs. Is it possible to install with the current GCC version? I am going to use it on a server and there they have the above mentioned version of GCC which they told not to change.

**Comment by jeffreybarrick** [comment]
Sorry, we can't support compiling with older versions of GCC. We will work on making the Linux binary more compatible at some point in the future. I hope you were able to solve this.
