### ISSUE TITLE
Total_cov in the RA section of output.gd represents the ratio of forward & reverse reads?

### ISSUE THREAD

**Issue by dixonfitzhume** [barricklab/breseq#155]
Hello, 

Is the coverage of the forward and reverse strands what is being represented in the numerator and denominator, respectively, of total_cov in the RA section of the output.gd file? I'm not sure how else to interpret a ratio of total coverage, so I'm assuming that's it (example below). 

RA | 206 | . | 1 | 1542318 | 0 | C | T | consensus_score=162.8 | frequency=1 | major_base=T | major_cov=41/28 | major_frequency=1.000e+00 | minor_base=N | minor_cov=0/0 | new_cov=41/28 | polymorphism_frequency=1.000e+00 | polymorphism_score=NA | prediction=consensus | ref_cov=0/0 | total_cov=41/28 

Thanks.

**Comment by jeffreybarrick** [comment]
That's correct. Top strand / bottom strand coverage.
