### ISSUE TITLE
Duplicated reads

### ISSUE THREAD

**Issue by phbrito** [barricklab/breseq#156]
Hello,
I can´t find information on how Breseq deals with duplicated reads. From analyzing output bam file it doesn´t seem that breseq eliminates those reads. Is it expected that we provide fastq files filtered for duplicated reads (e.g. optical and PCR duplicated reads) or does the algorithm applied for SNP calling deals with this?
Thanks very much for your help.

**Comment by jeffreybarrick** [comment]
You should filter out identical reads on your own before running _breseq_ if it is important that you eliminate optical or PCR duplicates from your dataset. For many datasets, it will probably not matter (e.g., consensus mutation calling) or you may not want to eliminate apparent PCR duplicates (e.g., when you have very deep coverage of a mixed population).

**Comment by tseemann** [comment]
@phbrito something like `fastUniq` might work:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3527383/

**Comment by phbrito** [comment]
@jeffreybarrick @tseemann many thanks for your suggestions. I will check fastUniq. I was under the impression that removing duplicates was considered mandatory for SNP calling, specially for detection of rare alleles. If you know of a reference that discuss this please let me know. Thanks!

**Comment by tseemann** [comment]
@phbrito we have sequenced tens of thousands of bacterial genomes on GAIIx, HiSeq, MiSeq and NextSeq.  If everything went fine with the library, then the optical duplicate level is usually << 5% and won't affect SNP calling at typical sequencing levels of 40-100x.

If you use Homebrew, you can now `brew install brewsci/bio/fastuniq` too.

**Comment by phbrito** [comment]
@tseemann thanks so much! your comments are helpful
