### ISSUE TITLE
./configure: line 17113: [: ==: unary operator expected + libunwind

### ISSUE THREAD

**Issue by tseemann** [barricklab/breseq#157]
```
checking libunwind.h presence... no
checking for libunwind.h... no
checking for library containing unw_getcontext... -lunwind
./configure: line 17113: [: ==: unary operator expected
```

And I have `libunwind 1.2` installed.

Also fails to build 

```
/home/linuxbrew/.linuxbrew/lib/libunwind.a(libunwind.cpp.o): In function `libunwind::LocalAddressSpace::findFunctionName(unsigned long, char*, unsigned long, unsigned long*)':
(.text._ZN9libunwind17LocalAddressSpace16findFunctionNameEmPcmPm[_ZN9libunwind17LocalAddressSpace16findFunctionNameEmPcmPm]+0x2b): undefined reference to `dladdr'
```

```
gcc version 5.5.0 (Homebrew gcc 5.5.0_4)
autoconf (GNU Autoconf) 2.69
```

**Comment by tseemann** [comment]
```
checking for library containing deflateSetHeader... -lz
checking for library containing acosf... -lm
checking for library containing pthread_create... -lpthread
checking libunwind.h usability... no
checking libunwind.h presence... no
checking for libunwind.h... no
checking for library containing unw_getcontext... -lunwind
./configure: line 17113: [: ==: unary operator expected
**Using execinfo.h for backtrace.**
checking for .git/refs/heads/master... no
checking for .git/refs/heads/master... (cached) no
checking that generated files are newer than configure... done
```

**Comment by jeffreybarrick** [comment]
If you are using the GitHub repository version, try updating to the latest revision (cc99e170082298a5323b2c788c3ef805cea97d29). Then, rerun:
`./bootstrap.sh`
`./configure`
`make clean`
`make`

If it still gives a linking error related to `libunwind`, please upload the file `aux_build/config.h` so I can inspect it to be sure that some compiler flags are being set correctly by `configure`.

If you are using one of the source code packages, let me know and I will roll this change into a download for you to test.

Thanks for the help figuring this out!

**Comment by jeffreybarrick** [comment]
The configure script now has a `--no-lib-unwind` option in v0.33.0 and tries to do a better job of detecting things by default. Hopefully one of these solves this issue.

**Comment by tseemann** [comment]
I'll give it a go and let you know.

**Comment by tseemann** [comment]
```
configure: error: unrecognized option: `--no-lib-unwind'
```

**Comment by jeffreybarrick** [comment]
Sorry, it's `--without-libunwind`

**Comment by tseemann** [comment]
Ok, giving it another try,

**Comment by tseemann** [comment]
A year later - it worked. And i'm now updating brew pkg to 0.33.2 :)

**Comment by jeffreybarrick** [comment]
Awesome!
