### ISSUE TITLE
breseq: FATAL ERROR due to "Unrecognized base char"

### ISSUE THREAD

**Issue by justinshaffer** [barricklab/breseq#161]
I am using a customized version of breseq v0.26 referred to as breseq-lite. This version was used in Good et al. 2017 (doi:10.1038/nature24287), however I believe that the issue is related to my specific data rather than this customized version of the program.

When attempting to run breseq for a second round incorporating candidate junctions from the first round (i.e., after running breseq and merging candidate junctions from the first round of breseq, within populations), I encounter the following error message:

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Unrecognized base char
FILE: libbreseq/common.h   LINE: 162
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
breseq: libbreseq/common.h:92: void breseq::my_assertion_handler(bool, const char*, const char*, int, const string&): Assertion `false' failed.

Not all populations fail, of those that do fail, this error message appears when tabulating error counts, but in unique positions of the genome (e.g., after chrIII for one population and after chrVI for another). This leads me to think that the "Unrecognized base char" issues are in the merged candidate junction files for the populations that fail, but I can't seem to find any in those files. I have attached one example error file along with the corresponding merged candidate junctions file.
[Archive.zip](https://github.com/barricklab/breseq/files/1993230/Archive.zip)

Further, when I manually truncate the merged candidate junction file and attempt to reproduce the issue, the same error occurs but pointing to line 233 of common.h rather than line 162. The error occurs earlier in the tabulating error process, but not at the genomic position to which I manually truncated the merged candidate junction file. 

I do not believe the issue is with my raw/trimmed sequence data, or my reference genome, as the first run of breseq completes without error for all populations.

This issue is related to issue#109: lower case bases in fasta, but unique in that I believe I am restricted to using breseq-lite and cannot use a newer version to resolve the issue, thus would prefer to resolve this issue in the version I'm using (i.e., breseq-lite), if possible.

I would be happy to provide more information if needed. Please let me know if you have any suggestions.

Thank you in advance and best wishes.

**Comment by jeffreybarrick** [comment]
Hi Jason,

I'm not able to provide much guidance about `breseq-lite`. I took a look to see if it would be possible to merge in the later `breseq` commits that have happened since v0.26.0 with those changes (which likely fix the issue), but there were some conflicts with the `breseq-lite` code that I'm not exactly sure how to resolve correctly. They seem to have to do with how some of the Genome Diff fields are defined. We would have to consult Ben Good about what modifications are needed in `breseq-lite` to not break his pipeline in updating the code.

I think you might have an easier time trying to "fix" your reference sequence by making sure that it only includes uppercase letters in the set {A, T, C, G, N} using a find/replace/grep/etc. approach. Is it  possible for you to try that?

**Comment by justinshaffer** [comment]
Thanks for your note.

I understand the issue you encountered when attempting to merge the later version of breseq with Ben Good's pipeline. I will contact him to see if perhaps he is able to update breseq in the pipeline, and will let you know if we need any assistance with the merge. Thanks for your willingness to help.

I was able to try my reference genome with the bases replaced with uppercased ones, as well as another more well-curated reference also with uppercase bases, but the problem persists. Given that the problem is likely fixed in newer versions of breseq as you mention, I will work with Ben Good to see if together we can resolve this issue; if we are not able to I will open a new issue thread focused on merging a newer version of breseq with his pipeline, unless you prefer to keep this one open and discuss that here, potentially.

Thanks again and best wishes,
