### ISSUE TITLE
breseq:0.27.1

### ISSUE THREAD

**Issue by UWBCoevolution** [barricklab/breseq#162]
Hi, I am using breseq 0.27.1 (I am having some problem installing the latest version)
I am using bacterial genome sequence reads to detect mutations. 
I ran breseq with the following two different settings. 
1. breseq with all default options
2. breseq with --aligned-sam option. The sam file is obtained using bowtie2 with default options.
But I got very different results. Both results do not have any common mutations predicted.
I was wondering if breseq uses some additional options to align reads.
Please let me know.
Thank you.

**Comment by jeffreybarrick** [comment]
Are you using non-Illumina reads?

The `--aligned-sam` option is not something that should be used lightly; `breseq` uses certain `bowtie2` alignment and reporting options for a reason. More specifically, `breseq` expects some things to be true of your SAM files, and it will give inconsistent results if these are not true. In addition to the warnings in the help, it does best will a certain reporting options that include suboptimal alignments.

```
--aligned-sam           Input files are aligned SAM files, rather
                                   than FASTQ files. Junction prediction steps
                                   will be skipped. Be aware that breseq
                                   assumes: (1) Your SAM file is sorted such
                                   that all alignments for a given read are on
                                   consecutive lines. You can use 'samtools sort
                                   -n' if you are not sure that this is true for
                                   the output of your alignment program. (2) You
                                   EITHER have alignment scores as additional
                                   SAM fields with the form 'AS:i:n', where n is
                                   a positive integer and higher values indicate
                                   a better alignment OR it defaults to
                                   calculating an alignment score that is equal
                                   to the number of bases in the read minus the
                                   number of inserted bases, deleted bases, and
                                   soft clipped bases in the alignment to the
                                   reference. The default highly penalizes
                                   split-read matches (with CIGAR strings such
                                   as M35D303M65).

```

You can see the options that `breseq` uses for its `bowtie2` command printed to `stdout` during a normal run. If you want to experiment with changing the parameters, I'd modify those.

**Comment by UWBCoevolution** [comment]
Thank you for your quick response. Here are following questions.
1. It seems like breseq use some filtering to filter bad reads to get ..converted.fastq files. What options are used to produce ..converted.fastq files, and what options we can control?
2. You are running bowtie2 initially twice for each file. First stage provides .stage1.sam file. And run bowtie2 again to unmatched reads (unmatched.fastq) to provide ..stage2.matched.sam file. Do you merge the two sam files before variant calling?
3. For paired-end file, why you do not call bowtie2 with paired-end option? 
Please let me know.
Thank you.

**Comment by jeffreybarrick** [comment]
1. These options from `breseq -h ` explain all of the filtering that goes on.

```
Read File Options
...
  --read-min-length <arg>          Reads in the input FASTQ file that are
                                   shorter than this length will be ignored. (0
                                   = OFF) (DEFAULT=18)
  --read-max-same-base-fraction <arg>                                           
                                   Reads in the input FASTQ file in which this
                                   fraction or more of the bases are the same
                                   will be ignored. (0 = OFF) (DEFAULT=0.9)
  --read-max-N-fraction <arg>      Reads in the input FASTQ file in which this
                                   fraction or more of the bases are uncalled as
                                   N will be ignored. (0 = OFF) (DEFAULT=0.5)
```

2. Yes, they are merged. Running `bowtie2` in this staged way is to improve the speed of mapping since we keep track of many read matches.

3. http://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/faq.html
