### ISSUE TITLE
Segmentation Fault @ PROCESSING Output with -p

### ISSUE THREAD

**Issue by hosodakazufumi** [barricklab/breseq#163]
Dear barricklab,
#First I really appreciate your contribution by sharing this great tools in a very useful way and I am sorry for taking your precious time now.
I analyzed 32 samples and I got an error (below) for 3 samples (29 were fine), only when I used polymorphic option (fine without -p). The three samples were mixed-population sample from the same experimental-evolution line. Because something should be wrong in my fastq file, I tried cleaned fastq (by trimmomatic) and reproduced fastq from BAM (once created by BWA and then re-converted by samtools), but both gave me the same error. I would be grateful if you could help me. Sincerely, _Kazu

# I used >
breseq 0.32.1
bowtie2  :: version 2.3.4.1 [/usr/bin/bowtie2]
R        :: version 3.4.4 [/usr/bin/R]

# The error >
+++   NOW PROCESSING Output
Creating merged genome diff evidence file...
Predicting mutations from evidence...
  Preparing junctions...
  Predicting mobile element insertions...
  Predicting large deletions...
  Predicting small indels and substitutions from junctions...
  Predicting small indels and substitutions from alignments...
  Making final adjustments to mutations...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Segmentation Fault
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
0x000000000043f764 _ZN6breseq17seg_fault_handlerEi
0x00007f6fa7eb4f20 killpg
0x000000000054a570 _ZN6breseq17MutationPredictor46normalize_and_annotate_tandem_re
0x000000000055ea3a _ZN6breseq17MutationPredictor7predictERNS_8SettingsERNS_7Summar
0x000000000042ec39 _Z21breseq_default_actioniPPc
0x000000000040accd main
0x00007f6fa7e97b97 __libc_start_main
0x000000000041aff9 _start
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by hosodakazufumi** [comment]
Hi Dr. Jeffrey Barrick or a member of barricklab,
Thank you very much for your quick and kind reply. I sent you my data via email. I really appreciate your kind help and providing the application itself. _Kazu

**Comment by jeffreybarrick** [comment]
Thanks for the test data! This was an easy fix. I've committed the change to GitHub. I can also create a pre-release version of the distribution for you to download and use if that is helpful. Just let me know if you use the MacOSX or Linux binary or the source code distribution.

**Comment by hosodakazufumi** [comment]
The three files were successfully analyzed by breseq-master! Sorry for my late response. Thank you so much and I truly appreciate your kind help!!!

**Comment by jeffreybarrick** [comment]
Great!
