### ISSUE TITLE
gdtools set operation bug

### ISSUE THREAD

**Issue by vr1087** [barricklab/breseq#164]
I am trying to use the gdtools 'subtract' function, but it is failing to correctly equate some mutations.

I ran this command:
`gdtools SUBTRACT -o subtract_failure.gd positives.gd predicted.gd`

But I still see mutations in 'subtract_failure.gd' that are in both input gd files. I've attached the genome Diff files. I can provide all the data if needed, however. 

I am using breseq 0.32.1 and 
`---> bowtie2  :: version 2.3.2 [/usr/local/bin/bowtie2] `
`---> R        :: version 3.2.3 [/usr/bin/R]`

[gd_files.zip](https://github.com/barricklab/breseq/files/2070011/gd_files.zip)

**Comment by jeffreybarrick** [comment]
I think there are two issues here:
(1) The default behavior of SUBTRACT is to take the frequency of a mutation in file1 and subtract the frequency in file 2 and then remove the mutation from the results if the resulting frequency is 0 or less.
(2) There is a floating point error that makes subtracting 1 from 1 not give the expected result.

I'd like to change the _default_ behavior to be removing the mutation in file1 if it is present with *any* frequency in file2 (essentially throwing out all frequency information in the input and output files). But, I think I'll add an option to preserve the frequency subtraction version with the floating point fix.

Does this make sense? Is that the default behavior you'd expect – only keeping track of entries not frequencies? Or would you expect it to pay attention to the frequencies of the mutations by default?

**Comment by vr1087** [comment]
Yes, that does make sense. I didn't know SUBTRACT used the mutation frequencies. I assume that INTERSECT and UNION do not use mutation frequency, correct? 

I was, indeed, expecting the set operations to only keep track of entries and not frequencies. I think 'attention to frequencies' should be an optional flag. Currently, I only care about the entries, but I will need to account for the frequencies later on.

**Comment by vr1087** [comment]
I see some commits have been pushed related to this issue. I'm wondering how long before an updated breseq version is available. If it's a few weeks off, and if this issue is already resolved in the recent comments, is it possible for me to get those fixes ahead of time?

**Comment by jeffreybarrick** [comment]
Yes, I believe it's been fixed and I just released v0.33.0 with the new code.

**Comment by vr1087** [comment]
Hi Jeff. Quick question. Did this fix affect how the INTERSECT function works? Regardless of the answer, am I right in assuming that variant frequencies are _not_ considered during INTERSECT and UNION operations?

**Comment by jeffreybarrick** [comment]
You are correct: variant frequencies are NOT considered by gdtools INTERSECT and UNION.

PS: I just noticed a bug was introduced in v0.33.0 related to other changes that causes some _breseq_ runs to crash during the last step of generating output, so update to v0.33.1 when I get it online in another day or so.
