### ISSUE TITLE
Breseq output mutations from output.gd

### ISSUE THREAD

**Issue by Kimw6** [barricklab/breseq#166]
Hi, thank you for sharing breseq tool. It is very helpful for my research.
Currently, I am comparing variant calling tools including breseq. I have simulated clonal sequencing reads (paired-end) with true mutations (around 50 of mutations). When I ran breseq with default option, it only provides 4 predicted mutations and 20 marginal mutations. However, the output.gd file contains all 50 mutations. The 26 mutations that are not shown in output.html, but in the output.gd file, are all prediction=polymorphism mutations. It seems like the output.html shows only consensus mode. I tried to run with -p option to see if that will provide all 50 mutations, but it provide more than 20,000 mutations. 
Here are my questions:
1. Breseq default option is consensus mode. Why does it still provide polymorphism mutations in the output.gd file? Can these polymorphism mutations be counted as true mutations as well?
2. I thought clonal samples should be run with consensus mode. But in the breseq option, you can also change polymorphism options for the consensus mode. What affects these options have on the results for clonal samples?
3. If the polymorphism mutations are strong except "prediction=polymorphism", how can I include them to output.html?
4. I understand breseq applies several alignments including junction predictions, then merge the alignment files. I want to use the final alignment file to other variant calling tools. What is the final bam file I can use? 

Thank you!

**Comment by vr1087** [comment]
The 20 K mutations predicted -- are they all very low frequency? Did you simulate clonal sequencing reads with error? Is there a chance that you are using the wrong reference / reads generated form a different reference? What version of breseq are you using? -- Just some questions I had while reading your post. 

You can find the answers to your questions in breseq's documentation. 

The final bam file is under OUTPUT_FOLDER/data/reference.bam
