### ISSUE TITLE
Phylogeny analysis

### ISSUE THREAD

**Issue by Pilarel** [barricklab/breseq#167]
Hello Jeffrey. 

I am using Breseq to compare several genomes from the same species (Ralstonia).. (they are supposed to be clonal but I want to proof this wrong) . I have already run breseq in all 17 genomes and obtained the .gd files from the output folder.  My final aim is to create a phylogenetic tree with all the 17 strains and i thought i can use the .gd files for it.

After this, I put the .gd files in one folder together with the .gbk files (chromosome and plasmid) and I run the command  > gdtools compare -o output  -r genome.gbk -r plasmid.gbk outputstrain1.gd outputstrain2.gd  ... etc.  I only tried using few of the strains .gd files and I dont get any result. I only get an empty output file (there are 2 zeros inside) . 

What am i doing wrong? is curation of the data necessary for this step ? i also tried > gdtools phylogeny command with the same specifications and didnt work. 

Thanks for the help!! awesome tool!

**Comment by vr1087** [comment]
Are there mutations predicted? If there are none, then it would not make sense to make a phylogeny or generate a comparison table.

**Comment by Pilarel** [comment]
Thanks for the answer! :) Yes there are several ones, as RA or MC JC, i see them in the index.html file. I am happy to see them and also when i compare the clones manually I see there are differences between them, which is suggestive of evolution. What can be wrong then? I am not getting an empty output file when i run the gdtools COMPARE  command line with all the .gd files ?

**Comment by jeffreybarrick** [comment]
A couple of questions:

1) Did you run breseq in polymorphism mode (-p), in which case it will try to look for mutations present at intermediate frequencies in a mixed population?

2) Are there any entries in the GenomeDiff files with three-letter codes? Only those (INS, SNP, DEL, etc.) are mutation predictions that will be used by gdtools compate. The entries with two-letter codes (RA, MC, JC) are "evidence" that it may not have been able to predict a mutation from. Those are not used in gdtools compare of for making phylogenies.

**Comment by Pilarel** [comment]
Thanks a lot! I got it. I am now using the gdtools interesect and subtract options to analyse to find out the mutations responsable for some of the branches in the tree.

**Comment by jeffreybarrick** [comment]
Great! That should work. If you see a mutation missing in one genome where it doesn't agree with the tree, you might need to look more closely for it using `breseq bam2aln` or `breseq bam2cov` if the area is not detailed in the HTML output for that particular genome.
