### ISSUE TITLE
FATAL ERROR: Incorrect junction sequence length: 80

### ISSUE THREAD

**Issue by mnrusimh** [barricklab/breseq#171]
Breseq run terminates with a FATAL ERROR for a specific read library against a specific genome reference. There were other fastq read libraries for which breseq jobs completed successfully. I wasn't sure what the error message meant and any help would be greatly appreciated. I am willing to provide any additional information. 
Thanks.

Breseq ver: breseq-0.33.1

Command line: 

`$BIN/breseq-0.33.1/bin/breseq -r LY1_T0_reference.fna -r LY1_T0_reference.gff -n wt_18C_T20 -j 16 -o breseq_out/wt_18C_T20 wt_18C_T20_R1.fastq wt_18C_T20_R2.fastq`

Last few lines from the error log:
```
+++   NOW PROCESSING Identifying junction candidates
  READ FILE::wt_18C_T20_R1
    ALIGNED READ:10000 CANDIDATE JUNCTIONS:33608
  READ FILE::wt_18C_T20_R2
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
JC              .       X       745718  1       III     150     1       29
Incorrect junction sequence length: 80
FILE: candidate_junctions.cpp   LINE: 2059
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/home/mnrusimh/bin/breseq-0.33.1/bin/breseq() [0x43893e]
/home/mnrusimh/bin/breseq-0.33.1/bin/breseq() [0x476edd]
/home/mnrusimh/bin/breseq-0.33.1/bin/breseq() [0x479f9b]
/home/mnrusimh/bin/breseq-0.33.1/bin/breseq() [0x47bbd8]
/home/mnrusimh/bin/breseq-0.33.1/bin/breseq() [0x47c8a2]
/home/mnrusimh/bin/breseq-0.33.1/bin/breseq() [0x42c4c5]
/home/mnrusimh/bin/breseq-0.33.1/bin/breseq() [0x409ed9]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f54533ff830]
/home/mnrusimh/bin/breseq-0.33.1/bin/breseq() [0x417389]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

**Comment by jeffreybarrick** [comment]
Thanks for reporting the error.

If you're able to share the read and reference files causing the error so that I can investigate what is going wrong, please email me at the address in the _breseq_ header to arrange a way to transfer the files.

**Comment by jeffreybarrick** [comment]
Closing this as inactive or no longer an issue in newer versions. Re-open if this is not the case.
