### ISSUE TITLE
gdtools NORMALIZE throws 'std::out_of_range'

### ISSUE THREAD

**Issue by vr1087** [barricklab/breseq#172]
I am trying to normalize (with gdtools from breseq 0.33.1) a genomeDiff file made with breseq 0.30.0.

While:
`Using APPLY to check that normalization didn't change the mutated sequence.`

This error is thrown:
`terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 4) >= this->size() (which is 2)
 Aborted (core dumped)`

Any idea why?

**Comment by jeffreybarrick** [comment]
It seems like there must be a mutation that is doing something outside of the start-end bounds of the sequence. Any chance you can isolate the line that is causing the problem by chopping lines out of the file to see which one is giving the problem?
