### ISSUE TITLE
Meaning of fields bias_e_value and bias_p_value in output.gd

### ISSUE THREAD

**Issue by Ramya1000** [barricklab/breseq#175]
Hello,

It may be straight forward but I really cannot find the exact meaning of the fields bias_e_value and bias_p_value given as part of RA evidence in output.gd file despite extensively searching through the documentation. On the basis of manually going through example alignments for low and high values of the two fields, I have come to conclude that they capture the base quality and strand distribution (forward vs reverse) of the major-base. Thus, it seems to me that bias_e_value and bias_p_value capture information for the major-base whereas fisher_strand_p_value and ks_quality_p_value capture how the minor-base compares to major-base in terms of quality and strand distribution.

I will highly appreciate if someone can point me towards a precise explanation for the fields.

Thank you,
Ramya

**Comment by jeffreybarrick** [comment]
Here's an explanation:

`bias_p_value` is the -log10  of the combined p_value (using Fisher's combination method) of `ks_quality_p_value` and `fisher_strand_p_value`. Those test for biases in the reads/bases supporting the variant versus the reference base using: (1) a Kolmogorov-Smirnov test on the base qualities being different for the variant and (2) Fisher's exact test on the strands of reads supporting the variant versus the reference base being different.

`bias_e_value` is the `bias_p_value` with a simple correction for multiple testing. The value is multiplied by the number of positions in the reference genome (L). So, `bias_e_value = bias_p_value + log10(L).`

Currently, neither of these combined bias test values is used by _breseq_ to filter predictions.

Instead, the `--polymorphism-bias-cutoff` command-line option sets whether predictions are rejected by comparing to each bias test p-value separately. This filter is off by default. To pass this test, `fisher_strand_p_value` and `ks_quality_p_value` must both be greater than or equal to `--polymorphism-bias-cutoff`.
