### ISSUE TITLE
FATAL ERROR while annotating mutations

### ISSUE THREAD

**Issue by annesicard** [barricklab/breseq#176]
while running this command (breseq 0.33.0, macOS High Sierra 10.13.6):
breseq -j 4 -o path_to_output -r path_to_reference path_to_fastq1 path_to_fastq2

I get the following error message:

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Segmentation Fault
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
0x000000010ed93ced _ZN6breseq17seg_fault_handlerEi
0x00007fff61c6bf5a _sigtramp
0x000000010ef49790 _ZN6breseq6output27add_html_fields_to_mutationERNS_10cDiffEntry
0x000000010ef53c66 _ZN6breseq6output26Html_Mutation_Table_String10Item_LinesEv
0x000000010ef500de _ZN6breseq6output26Html_Mutation_Table_StringC2ERKNS_8SettingsE
0x000000010ef41197 _ZN6breseq6output34html_genome_diff_item_table_stringERKNS_8Set
0x000000010ef60ccd _ZN6breseq6output20cOutputEvidenceFiles18html_evidence_fileERKN
0x000000010ef5dd0d _ZN6breseq6output20cOutputEvidenceFilesC2ERKNS_8SettingsERNS_11
0x000000010ed8ef45 _Z21breseq_default_actioniPPc
0x000000010ed93aa2 main
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jeffreybarrick** [comment]
Are you able to provide the file `output/output.gd` and your reference sequence file for me to reproduce the crash? If so, please contact me at the email in the _breseq_ header.

**Comment by jeffreybarrick** [comment]
Please update to _breseq_ v0.33.1. This is a bug that was fixed in that version. Cheers!
