### ISSUE TITLE
Can gd2circos be applied on polymorphic population?

### ISSUE THREAD

**Issue by lilitto** [barricklab/breseq#177]
Hi Jeffrey,

I used the polymorphism mode to predict mutations in "metagenomic" populations. I was wondering if it is possible to compare these "metagenomic" populations using gd2circos and have all the SNPs on the rings? Or the gd2circos tool can be applied only to clonal data? Could you please help!

Thanks in advance

**Comment by jeffreybarrick** [comment]
Unfortunately, we haven't been able to maintain the functionality or documentation of the `gd2circos` subcommand of `gdtools`, and we don't have plans to update it. I know that it stopped working with newer versions of `circos` a couple of years ago. You'll have to experiment with what you can get it to do on your own. Sorry!
