### ISSUE TITLE
gdtools COMPARE -f PHYLIP giving file with only 0 0

### ISSUE THREAD

**Issue by Ramya1000** [barricklab/breseq#178]
Hello,
I am trying to use gdtools COMPARE tool to make a phylogenetic tree for my clonal samples. Thus, I used the following command
gdtools COMPARE -f PHYLIP -r ref.fa sample1.gd sample2.gd sample3.gd sample4.gd
but got a nearly empty output.phylip file instead with a single line 0 0. I suspect that it is not reading the input gd files for some reason. However, the COMPARE command seems to be working for I am able to get HTML and GD output file formats, just not phylip. I am at a loss on how to proceed and would appreciate any help.
Thanks,
Ramya
PS: I do not see any lines beginning with Reading input GD file: sample1.gd etc when trying to get the output in phylip format which I do see when I output in other formats. This leads me to think that the gd files are not being read for some reason.

**Comment by Ramya1000** [comment]
I should mention that the gd files do not contain read information (they are not output.gd files generated by running breseq). They were made by converting vcf files into gd files using the tool gdtools vcf2gd. The files have information like this:
#=GENOME_DIFF   1.0
SNP     1       .       chr01   96033   A       AC=1    AF=1.00 AN=1    DP=4    FS=0.000        MLEAC=1 MLEAF=1.00      MQ=60.00        QD=17.25        SOR=0.693

**Comment by Ramya1000** [comment]
I figured it out: It works in breseq 0.26.0 but not in 0.31 or 0.33. Sharing it for anyone else who may have the same problem.
Best-Ramya

**Comment by jeffreybarrick** [comment]
Hi Ramya, thanks for reporting this regression in the code. I will take a look when I have a chance at what has changed.
