### ISSUE TITLE
Request: ref_seq column analogous to codon_ref_seq or aa_ref_seq

### ISSUE THREAD

**Issue by dannagifford** [barricklab/breseq#180]
Super minor, but I think it would be useful to have a "ref_seq" column to match the "new_seq" column in gdtools output, analogous to the "codon_ref_seq" / "codon_new_seq" and "aa_ref_seq" / "aa_new_seq" pairs.

**Comment by spleonard1** [comment]
I was about to post this separately, but I'll jump on here instead. I'm trying to plot some intergenic mutations based on the .tsv output on gdtools COMPARE on a bunch of genome diff files. As stated above, there is no "reference base" column containing the original nucleotide in the tsv file. This makes it difficult to programmatically label these mutations. Thanks! I love breseq.

**Comment by jeffreybarrick** [comment]
In the current repository version, I've added a `ref_seq` column/tag to the output of `gdtools COMPARE/ANNOTATE`. If the `ref_seq` state is longer than 20 base pairs, for example for a large deletion, then it will output `X-bp` instead of the actual bases for this field.

**Comment by dannagifford** [comment]
Amazing thank you!
