### ISSUE TITLE
FATAL ERROR, Result code: 6400

### ISSUE THREAD

**Issue by jlebov** [barricklab/breseq#183]
Hi, I'm trying to run breseq comparing a single end Illumina library against a SPAdes assembled reference genome (sequenced using paired-end 150 Illumina libraries). For some reason my run won't finish. Any help resolving this would be greatly appreciated.

My run produces the following:

breseq -o ./Consensus_L5b_20B-q_vs_SPADESancMR1gfp_-r -r ../../SeqResults_ancMR-1tag/spadesAssembTest1/scaffolds.fasta ../Pass20_isolates/5_20B_isolate_b.fastq
================================================================================
breseq 0.31.0     http://barricklab.org/breseq

Active Developers: Barrick JE, Deatherage DE
Contact:           <jeffrey.e.barrick@gmail.com>

breseq is free software; you can redistribute it and/or modify it under the
terms the GNU General Public License as published by the Free Software
Foundation; either version 2, or (at your option) any later version.

Copyright (c) 2008-2010 Michigan State University
Copyright (c) 2011-2017 The University of Texas at Austin

If you use breseq in your research, please cite:

  Deatherage, D.E., Barrick, J.E. (2014) Identification of mutations
  in laboratory-evolved microbes from next-generation sequencing
  data using breseq. Methods Mol. Biol. 1151: 165–188.

If you use structural variation (junction) predictions, please cite:

  Barrick, J.E., Colburn, G., Deatherage D.E., Traverse, C.C.,
  Strand, M.D., Borges, J.J., Knoester, D.B., Reba, A., Meyer, A.G.
  (2014) Identifying structural variation in haploid microbial genomes
  from short-read resequencing data using breseq. BMC Genomics 15:1039.
================================================================================
---> bowtie2  :: version 2.3.3 [/packages/bowtie2/2-2.3.3/bin/bowtie2]
---> R        :: version 3.5.1 [/packages/R/3.5.1/bin/R]
--- ALREADY COMPLETE Read and reference sequence file input
+++   NOW PROCESSING Read alignment to reference genome
[system] bowtie2-build -q ./Consensus_L5b_20B-q_vs_SPADESancMR1gfp_-r/data/reference.fasta ./Consensus_L5b_20B-q_vs_SPADESancMR1gfp_-r/02_reference_alignment/reference
[system] bowtie2 -t -p 1 --local  -L 31 --ma 1 --mp 3 --np 0 --rdg 2,3 --rfg 2,3 --ignore-quals  -k 2000 -i S,1,0.25 --score-min L,1,0.9  --reorder -x ./Consensus_L5b_20B-q_vs_SPADESancMR1gfp_-r/02_reference_alignment/reference -U ./Consensus_L5b_20B-q_vs_SPADESancMR1gfp_-r/01_sequence_conversion/5_20B_isolate_b.converted.fastq -S ./Consensus_L5b_20B-q_vs_SPADESancMR1gfp_-r/02_reference_alignment/5_20B_isolate_b.stage1.sam --un ./Consensus_L5b_20B-q_vs_SPADESancMR1gfp_-r/02_reference_alignment/5_20B_isolate_b.stage1.unmatched.fastq
Time loading reference: 00:00:00
Time loading forward index: 00:00:00
Time loading mirror index: 00:00:00
Substitution loop at /packages/bowtie2/2-2.3.3/bin/bowtie2 line 570, <BT> line 2696080.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error running command:
[system] bowtie2 -t -p 1 --local  -L 31 --ma 1 --mp 3 --np 0 --rdg 2,3 --rfg 2,3 --ignore-quals  -k 2000 -i S,1,0.25 --score-min L,1,0.9  --reorder -x ./Consensus_L5b_20B-q_vs_SPADESancMR1gfp_-r/02_reference_alignment/reference -U ./Consensus_L5b_20B-q_vs_SPADESancMR1gfp_-r/01_sequence_conversion/5_20B_isolate_b.converted.fastq -S ./Consensus_L5b_20B-q_vs_SPADESancMR1gfp_-r/02_reference_alignment/5_20B_isolate_b.stage1.sam --un ./Consensus_L5b_20B-q_vs_SPADESancMR1gfp_-r/02_reference_alignment/5_20B_isolate_b.stage1.unmatched.fastq
Result code: 6400
FILE: libbreseq/common.h   LINE: 1477
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Backtrace with 6 stack frames.
breseq() [0x41b238]
breseq() [0x43c268]
breseq() [0x42d209]
breseq() [0x4097f7]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x2aaaab9423d5]
breseq() [0x41af47]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jeffreybarrick** [comment]
Were you able to resolve this issue? It looks like it might be a problem with your `bowtie2` install or having that in your `$PATH`. I'd also suggest updating to the most recent version of _breseq_.

**Comment by jeffreybarrick** [comment]
No test files provided to reproduce problem.
