### ISSUE TITLE
ignore ambiguous (N) bases in reference

### ISSUE THREAD

**Issue by Perugolate** [barricklab/breseq#184]
Is there a way to ignore ambiguity bases in the reference?

**Comment by jeffreybarrick** [comment]
Not directly.

But, something along the lines of one of these approaches might get you where you want to go:

1) Generate an updated/corrected reference sequence using `gdtools APPLY` and an output GenomeDiff file from _breseq_ that you have edited to have just the calls of bases that are ambiguous in the reference (perhaps using `gdtools FILTER`). Then, re-compare your read FASTQ against the corrected reference sequence in a new _breseq_ run.

2) Create a GenomeDiff file with the ambiguous reference base calls (perhaps using `gdtools INTERSECT` or `gdtools FILTER`). Use this file as input to `gdtools SUBTRACT` it from the `output.gd` file from a _breseq_ run to remove those mutations. Then, regenerate HTML output using `gdtools ANNOTATE`.

**Comment by Perugolate** [comment]
Cheers mate
