### ISSUE TITLE
[bam_sort_core] truncated file. Aborting. Fatal error_Segmentation Fault

### ISSUE THREAD

**Issue by Guokun2019** [barricklab/breseq#185]
Hi there,
Am now trying Breseq on mutation call for resequenced genome. After fixing several error, I got stucked here as shown below.

Info. on the packages I used:
R version: 3.5.2 (2018-12-20) -- "Eggshell Igloo"
bowtie2 --version: /home/ymer/anaconda3/bin/bowtie2-align-s version 2.3.4.3 64-bit
samtools --version samtools 1.9
Breseq version: /home/ymer/Documents/breseq-0.33.2-Linux-x86_64/bin/breseq --version: breseq 0.33.2

    ALIGNED READ:12800000
  Summary... 
  Aligned reads:                             12878240
  Read alignments:                           28029069
  Alignments split on indels:                  103513
  Reads with alignments split on indels:        37876
  Split alignments:                           3553042
  Reads with split alignments:                 231231
+++   NOW PROCESSING Preliminary analysis of coverage distribution
[samtools] import ./data/reference.fasta.fai ./03_candidate_junctions/best.sam ./03_candidate_junctions/best.unsorted.bam
[samtools] sort --threads 4 -o ./03_candidate_junctions/best.bam -T ./03_candidate_junctions/best.bam ./03_candidate_junctions/best.unsorted.bam
[bam_sort_core] truncated file. Aborting.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Segmentation Fault
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Backtrace with 10 stack frames.
/home/ymer/Documents/breseq-0.33.2-Linux-x86_64/bin/breseq() [0x43b436]
/home/ymer/Documents/breseq-0.33.2-Linux-x86_64/bin/breseq() [0x43b6d5]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f11bcc68f20]
/home/ymer/Documents/breseq-0.33.2-Linux-x86_64/bin/breseq() [0x65f448]
/home/ymer/Documents/breseq-0.33.2-Linux-x86_64/bin/breseq() [0x65fbb1]
/home/ymer/Documents/breseq-0.33.2-Linux-x86_64/bin/breseq() [0x5fe753]
/home/ymer/Documents/breseq-0.33.2-Linux-x86_64/bin/breseq() [0x42e988]
/home/ymer/Documents/breseq-0.33.2-Linux-x86_64/bin/breseq() [0x40a31e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f11bcc4bb97]
/home/ymer/Documents/breseq-0.33.2-Linux-x86_64/bin/breseq() [0x417ab9]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I ran the analysis with ubuntu in a hard drive with 700 Gb available space.
Hope to get a solution to this error.
Best,
Guokun

**Comment by jeffreybarrick** [comment]
Did you try deleting the entire output directory so that it runs in a clean environment? It seems like the run may have been previously interrupted and generated a bad intermediate file.

**Comment by Guokun2019** [comment]
I ran the analysis on the desktop and deleted the previously generated folders before the run. Will try  to run in a clean folder and see if it helps.
Thanks.
Guokun

**Comment by Guokun2019** [comment]
Hi Jeff,
Things did not get better on the run in with a clean output folder. Similar error occurred.

  Summary... 
  Aligned reads:                             12878240
  Read alignments:                           28029069
  Alignments split on indels:                  103513
  Reads with alignments split on indels:        37876
  Split alignments:                           3553042
  Reads with split alignments:                 231231
+++   NOW PROCESSING Preliminary analysis of coverage distribution
[samtools] import STS25_20190124_OUTPUT/data/reference.fasta.fai STS25_20190124_OUTPUT/03_candidate_junctions/best.sam STS25_20190124_OUTPUT/03_candidate_junctions/best.unsorted.bam
[samtools] sort --threads 4 -o STS25_20190124_OUTPUT/03_candidate_junctions/best.bam -T STS25_20190124_OUTPUT/03_candidate_junctions/best.bam STS25_20190124_OUTPUT/03_candidate_junctions/best.unsorted.bam
[bam_sort_core] truncated file. Aborting.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Segmentation Fault
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Backtrace with 10 stack frames.
Killed

Any additional tips?
Thanks.
Guokun

**Comment by jeffreybarrick** [comment]
Are you able to share the input files so that I can investigate the problem? (Email me at the address in the breseq header and I can provide a shared upload folder.)

**Comment by Guokun2019** [comment]
Thanks Jeff,
Problem seems to be solved. What I changed is placing all files and breseq in a folder under home directory. Then with the debug on space issue with R, I got the output files finally.
Hope these info. helps others as well.
Best,
Guokun
