### ISSUE TITLE
Segmentation fault during read alignment stage

### ISSUE THREAD

**Issue by stevenjdunn** [barricklab/breseq#186]
Hi, 

I'm getting a segmentation fault at the same stage across different alignments when using a genbank file as input. I've installed Breseq via conda in a new environment, and tried reinstalling libc6 `(sudo apt-get install libc6)` which seems to be throwing an exception. Just wanted to check whether anyone else has run into this and knows how to resolve it?

> > Creating read alignment for region: KFKMHJMK_1:4402360.0-4402360.0
> Creating read alignment for region: KFKMHJMK_1:4402363.0-4402363.0
> Creating read alignment for region: KFKMHJMK_1__1__1__KFKMHJMK_1__5046865__-1__0____251__251__0__0:251-252
> Creating read alignment for region: KFKMHJMK_1:1-1
> Creating read alignment for region: KFKMHJMK_1:5046865-5046865
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> Segmentation Fault
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> Backtrace with 13 stack frames.
> breseq() [0x41cb54]
> breseq() [0x438ae7]
> /lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7ff99e61b4b0]
> breseq() [0x54838f]
> breseq() [0x54b7ee]
> breseq() [0x55cab8]
> breseq() [0x55d134]
> breseq() [0x55e65e]
> breseq() [0x563410]
> breseq() [0x430444]
> breseq() [0x40ae05]
> /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7ff99e606830]
> breseq() [0x41c7d1]
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Here's a list of packages active in the environment:

> _r-mutex                  1.0.0               anacondar_1
> absl-py                   0.7.0                 py36_1000    conda-forge
> astor                     0.7.1                      py_0    conda-forge
> blas                      1.0                         mkl
> bowtie2                   2.3.4.3          py36he860b03_1    bioconda
> breseq                    0.33.0               ha92aebf_0    bioconda
> bzip2                     1.0.6             h14c3975_1002    conda-forge
> c-ares                    1.15.0            h14c3975_1001    conda-forge
> ca-certificates           2018.11.29           ha4d7672_0    conda-forge
> cairo                     1.14.12              he6fea26_5    conda-forge
> certifi                   2018.11.29            py36_1000    conda-forge
> fontconfig                2.13.1            h2176d3f_1000    conda-forge
> freetype                  2.9.1             h3cfcefd_1004    conda-forge
> gast                      0.2.2                      py_0    conda-forge
> gettext                   0.19.8.1          h9745a5d_1001    conda-forge
> glib                      2.55.0               h464dc38_2    conda-forge
> graphite2                 1.3.13            hf484d3e_1000    conda-forge
> grpcio                    1.16.1           py36hf8bcb03_1
> gsl                       2.1                           2    conda-forge
> harfbuzz                  1.9.0                h08d66d9_0    conda-forge
> icu                       58.2              hf484d3e_1000    conda-forge
> intel-openmp              2019.1                      144
> jpeg                      9c                h14c3975_1001    conda-forge
> krb5                      1.16.3            h05b26f9_1001    conda-forge
> libcurl                   7.64.0               h541490c_2    conda-forge
> libedit                   3.1.20170329      hf8c457e_1001    conda-forge
> libffi                    3.2.1             hf484d3e_1005    conda-forge
> libgcc                    7.2.0                h69d50b8_2    conda-forge
> libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
> libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
> libiconv                  1.15              h14c3975_1004    conda-forge
> libpng                    1.6.34               ha92aebf_2    conda-forge
> libprotobuf               3.7.0                hdbcaa40_0    conda-forge
> libssh2                   1.8.0             h90d6eec_1004    conda-forge
> libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
> libtiff                   4.0.9             h648cc4a_1002    conda-forge
> libuuid                   2.32.1            h14c3975_1000    conda-forge
> libxcb                    1.13              h14c3975_1002    conda-forge
> libxml2                   2.9.8             h143f9aa_1005    conda-forge
> markdown                  2.6.11                     py_0    conda-forge
> mkl                       2019.1                      144
> mkl_fft                   1.0.10           py36h14c3975_1    conda-forge
> mkl_random                1.0.2            py36h637b7d7_2    conda-forge
> ncurses                   6.1               hf484d3e_1002    conda-forge
> numpy                     1.16.2           py36h7e9f1db_0
> numpy-base                1.16.2           py36hde5b4d6_0
> openssl                   1.1.1b               h14c3975_1    conda-forge
> pango                     1.40.14           h53a7087_1002    conda-forge
> pcre                      8.39                          0    conda-forge
> perl                      5.26.2            h14c3975_1002    conda-forge
> pip                       19.0.3                   py36_0    conda-forge
> pixman                    0.34.0            h14c3975_1003    conda-forge
> protobuf                  3.7.0            py36hf484d3e_0    conda-forge
> pthread-stubs             0.4               h14c3975_1001    conda-forge
> python                    3.6.7             h381d211_1004    conda-forge
> r-base                    3.2.2                         0    r
> readline                  7.0               hf8c457e_1001    conda-forge
> setuptools                40.8.0                   py36_0    conda-forge
> six                       1.12.0                py36_1000    conda-forge
> sqlite                    3.26.0            h67949de_1001    conda-forge
> tbb                       2019.4               h6bb024c_0    conda-forge
> tensorboard               1.10.0                   py36_0    conda-forge
> tensorflow                1.10.0                   py36_0    conda-forge
> termcolor                 1.1.0                      py_2    conda-forge
> tk                        8.6.9             h84994c4_1000    conda-forge
> werkzeug                  0.14.1                     py_0    conda-forge
> wheel                     0.33.1                   py36_0    conda-forge
> xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
> xorg-libice               1.0.9             h14c3975_1004    conda-forge
> xorg-libsm                1.2.3             h4937e3b_1000    conda-forge
> xorg-libx11               1.6.7             h14c3975_1000    conda-forge
> xorg-libxau               1.0.9                h14c3975_0    conda-forge
> xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
> xorg-libxext              1.3.3             h14c3975_1004    conda-forge
> xorg-libxrender           0.9.10            h14c3975_1002    conda-forge
> xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
> xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
> xorg-xproto               7.0.31            h14c3975_1007    conda-forge
> xz                        5.2.4             h14c3975_1001    conda-forge
> zlib                      1.2.11            h14c3975_1004    conda-forge

I'm aligning Illumina reads trimmed using Trimmomatic to completed genbank files generated from Prokka annotation of hybrid assemblies (Nanopore/Illumina). When I use the fasta file it completes okay.

Thanks!

**Comment by jeffreybarrick** [comment]
It looks like the conda version of _breseq_ is v0.33.0? Can you see if installing the latest version (v0.33.2) fixes this problem? If it persists, I can take a look if you contact me via the email address in the header and provide some example input files to reproduce the problem. Thanks.

**Comment by stevenjdunn** [comment]
Yep, that did the trick! Thanks for your help, I really appreciate the swift reply.
