### ISSUE TITLE
Err: Please rename the duplicates so that they have unique locus_tags & names

### ISSUE THREAD

**Issue by Dbhave** [barricklab/breseq#188]
I am getting the following error when I try to run my MG1655 sample raw data using the MG1655 reference genome. I am not having trouble when I run my DH10B samples using DH10B reference genome. Could someone help me understand this issue of renaming duplicates? I have downloaded the latest reference genome for MG1655.

This is the error I receive:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Repeat feature must have only one location: b0322
Please rename the duplicates so that they have unique locus_tags & names, e.g., gene_1 and gene_2
FILE: reference_sequence.cpp   LINE: 699
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Any help will be appreciated.

**Comment by jeffreybarrick** [comment]
Your reference sequence has two annotated "repeat_region", "transposon", or similar features with the same id of "b0322". _breseq_ requires all features to have unique IDs.

What was the source of your reference genome file? Feel free to upload it and I can point out the issue in the file. Alternatively, you might try downloading a fresh MG1655 sequence from GenBank, which should not have this duplicate issue.

**Comment by Dbhave** [comment]
Hi Jeffrey,

I have downloaded the reference quite recently, about four weeks ago. Your help is much appreciated.
Here is the file I downloaded on 19th of March:

[MG1655_Ref_GCA_000005845.2_ASM584v2.gbff.zip](https://github.com/barricklab/breseq/files/3090465/MG1655_Ref_GCA_000005845.2_ASM584v2.gbff.zip)

**Comment by jeffreybarrick** [comment]
To follow up on this. I believe there is an error in this GenBank file. The section here has five different features that all have the same `/locus_tag="b0322"`.
  
```
    gene            339793..340089
                     /gene="yahH"
                     /locus_tag="b0322"
                     /gene_synonym="ECK0320"
                     /db_xref="ASAP:ABE-0001104"
                     /db_xref="ECOCYC:G0-10550"
                     /db_xref="EcoGene:EG13592"
     CDS             339793..340089
                     /gene="yahH"
                     /locus_tag="b0322"
                     /gene_synonym="ECK0320"
                     /codon_start=1
                     /transl_table=11
                     /product="putative uncharacterized protein YahH"
                     /protein_id="AYC08176.1"
                     /db_xref="UniProtKB/Swiss-Prot:Q2EEQ3"
                     /db_xref="ASAP:ABE-0001104"
                     /db_xref="ECOCYC:G0-10550"
                     /db_xref="EcoGene:EG13592"
                     /translation="MAQESVGLISVAHQAFVTIAGCGVNALSGLRMAQESVGLISVAH
                     QAFATTAGCGVDALSGLRVARESVGLISVAHQAFVTIAGCGVNALSGLRVAREL"
     repeat_region   complement(339809..339837)
                     /note="REPv23b"
                     /rpt_type=other
     repeat_region   339851..339884
                     /gene="yahH"
                     /locus_tag="b0322"
                     /gene_synonym="ECK0320"
                     /note="REP23c"
                     /rpt_type=other
     repeat_region   complement(339902..339930)
                     /note="REPv23d"
                     /rpt_type=other
     repeat_region   339944..339977
                     /gene="yahH"
                     /locus_tag="b0322"
                     /gene_synonym="ECK0320"
                     /note="REP23e"
                     /rpt_type=other
     repeat_region   complement(339995..340023)
                     /note="REPv23f"
                     /rpt_type=other
     repeat_region   340037..340070
                     /gene="yahH"
                     /locus_tag="b0322"
                     /gene_synonym="ECK0320"
                     /note="REP23g"
                     /rpt_type=other
```
Removing the `/locus_tag="b0322"` line from all three of the `repeat_region` items will allow _breseq_ to load this file as a reference.

**Comment by Dbhave** [comment]
Thanks this works!
