### ISSUE TITLE
Segmentation fault during th creation of coverage plot

### ISSUE THREAD

**Issue by mdrishti** [barricklab/breseq#189]
Hi,

I am using breseq-0.33.0 and ran the following command against an annotated assembly (with more than 100 contigs):
breseq -r NC_016810.1.full.gb -n breseqRes temp.fastq -j 6 -o test_breseq_WT

While the program is building covergae plots, I received this error:

Creating coverage plot for region: NODE_9_length_155_cov_74.410256:137-155
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Segmentation Fault
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Backtrace with 13 stack frames.
breseq() [0x41cb54]
breseq() [0x438ae7]
/lib64/libc.so.6(+0x36280) [0x7fcaf3325280]
breseq() [0x54838f]
breseq() [0x54b7ee]
breseq() [0x55cab8]
breseq() [0x55d134]
breseq() [0x55e65e]
breseq() [0x563410]
breseq() [0x430444]
breseq() [0x40ae05]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x7fcaf33113d5]
breseq() [0x41c7d1]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I get the output (output.gd), but with no html files. I am wondering if the process for getting the mutations is complete by the time the program reaches "Creating coverage plot". If yes, then I can rely on the "output.gd" file. If not, then could the developers of "breseq" suggest something to resolve this issue? Is this an issue with my input files (I suspect the assembly gbk file) or something else?

**Comment by jeffreybarrick** [comment]
Please update to the newest version of breseq (v0.33.2). I'm fairly certain this issue is resolved in that version.
