### ISSUE TITLE
Failure Polymorphism Stats

### ISSUE THREAD

**Issue by mattbawn** [barricklab/breseq#190]
Hi 

I am using `breseq 0.33.2` and am trying to look for polymorphisms using the `-p` flag.
The pipeline had previously successfully run without this flag.

the error file states:

`+++   NOW PROCESSING Polymorphism statistics
[system] R --vanilla total_length=4685848 in_file=./08_mutation_identification/polymorphism_statistics_input.tab out_file=./08_mutation_identification/polymorphism_statistics_output.tab qual_file=./08_mutation_identification/error_counts.tab < /usr/local/bin/../share/breseq/polymorphism_statistics.r > ./08_mutation_identification/polymorphism_statistics_output.log
breseq: reference_sequence.cpp:3473: void breseq::cReferenceSequences::polymorphism_statistics(breseq::Settings&, breseq::Summary&): Assertion `line_list.size() > j' failed. `

looking at the previous [breseq issue](https://github.com/barricklab/breseq/issues/83) This is a sample of the output.tab:

``` 
ks_quality_p_value	fisher_strand_p_value	bias_p_value	bias_e_value
0.954772	0.126562	0.376205	1762840
1	3.72225e-08	6.73963e-07	3.15809
1	0.591628	0.90216	4227380
1	5.19402e-17	1.99951e-15	9.36941e-09
1	0.000458899	0.00398631	18679.2
1	2.54854e-14	8.23196e-13	3.85737e-06
1	9.9803e-57	1.29691e-54	6.07711e-48
0.972287	0.500194	0.836911	3921640
1	1.61796e-11	4.182e-10	0.00195962
1	1.11564e-24	6.2646e-23	2.9355e-16
1	1.7484e-37	1.49728e-35	7.01603e-29
1	9.36888e-34	7.21877e-32	3.38261e-25
1	1	1	4685850
1	0.654712	0.932022	4367310
1	8.62397e-26	5.06336e-24	2.37261e-17
1	1.18899e-27	7.49023e-26	3.50981e-19 ```

**Comment by mattbawn** [comment]
Hi

Just checking anyone has seen this comment?

**Comment by jeffreybarrick** [comment]
Can you share your input files? Email me at the _breseq_ header email address and I can take a look.

**Comment by jeffreybarrick** [comment]
Hi Matt, I see the FASTQ files. Can you also share your exact reference file and the command line you used to run _breseq_? Thanks

**Comment by mattbawn** [comment]
Hi Jeff, I've just emailed them to you. Thanks

**Comment by mattbawn** [comment]
Hi Jeff,

I think the issue may have been that my reads had something wrong with the first line of my read files. Sorry for that. It seems to be running now. I'll close the issue.

**Comment by jeffreybarrick** [comment]
OK. If it's something _breseq_ could have detected and given you better feedback, let me know.
