### ISSUE TITLE
Increased coverage fails to detect deletion

### ISSUE THREAD

**Issue by imchelo** [barricklab/breseq#193]
Hi,
When I sequenced an *E. coli* population (from experimental evolution) at **186x** mean coverage, breseq detected a deletion from MC evidence (see graph attached). But I have increased coverage to **247x** and now the output only gives two SNPs in that region. Strangely, checking alignments in the region with IGV (see graph attached) shows clearly that coverage decreases well below the threshold in **both** cases in that region, so I don't think the "extra" sequencing is giving any new information. PS: the exact same breseq command was used in both cases. 

![Deletion](https://user-images.githubusercontent.com/51453504/59047957-d1482800-887c-11e9-8d75-c358e88885bf.png)

![IGV_compare](https://user-images.githubusercontent.com/51453504/59048575-086b0900-887e-11e9-859d-ec00d4f7fbc5.png)

**Comment by jeffreybarrick** [comment]
Deletions (and amplifications) present some as-yet unsolved challenges for polymorphism prediction mode.

The coverage must reach **_zero_** for at least one position within a region to predict MC evidence. It looks like the increased coverage prevents that. Possibly, this means there is a small subpopulation without the deletion, or we sometimes also see this if there is a hint of another DNA sample without the deletion making it into this read set.

So, _breseq_ switches to not predicting that as a deletion and instead finds some SNPs there. The frequency of these SNPs is not correct, b/c it is based on the remaining coverage of reads there. (That is, it is the frequency within the subpopulation that does not have the deletion.)

**Comment by imchelo** [comment]
Yes, it is very likely that the deletion has not yet had the opportunity to fix in the population.  And, in fact, there are some positions with zero counts in the alignments with lower coverage but not in those with higher coverage.
Thanks
