### ISSUE TITLE
FATAL ERROR Could not open reference file

### ISSUE THREAD

**Issue by trangthuypham** [barricklab/breseq#194]
Hi, I am trying to install and run Breseq on my NGS data. However, this is what I did and got 

Last login: Thu Jun  6 21:13:45 on ttys000
TPhams-MacBook-Pro:~ tpham$ export PATH=$PATH:/Applications/bowtie2-2.3.5.1-macos-x86_64
TPhams-MacBook-Pro:~ tpham$ export PATH=$PATH:/Applications/R
TPhams-MacBook-Pro:~ tpham$ /Applications/breseq-0.33.2-MacOSX-10.9+/bin/breseq -r ChAd-Genome2.gbk ChAd-Genome-Clone-3_S1_L001_R1_001.fastq ChAd-Genome-Clone-3_S1_L001_R2_001.fastq -o clone3_breseq
================================================================================
breseq 0.33.2  revision caddc01d3be9   http://barricklab.org/breseq

Active Developers: Barrick JE, Deatherage DE
Contact:           <jeffrey.e.barrick@gmail.com>

breseq is free software; you can redistribute it and/or modify it under the
terms the GNU General Public License as published by the Free Software 
Foundation; either version 2, or (at your option) any later version.

Copyright (c) 2008-2010 Michigan State University
Copyright (c) 2011-2017 The University of Texas at Austin

If you use breseq in your research, please cite:

  Deatherage, D.E., Barrick, J.E. (2014) Identification of mutations
  in laboratory-evolved microbes from next-generation sequencing
  data using breseq. Methods Mol. Biol. 1151: 165–188.

If you use structural variation (junction) predictions, please cite:

  Barrick, J.E., Colburn, G., Deatherage D.E., Traverse, C.C.,
  Strand, M.D., Borges, J.J., Knoester, D.B., Reba, A., Meyer, A.G. 
  (2014) Identifying structural variation in haploid microbial genomes 
  from short-read resequencing data using breseq. BMC Genomics 15:1039.
================================================================================
---> bowtie2  :: version 2.3.5.1 [/Applications/bowtie2-2.3.5.1-macos-x86_64/bowtie2]
---> R        :: version 3.6.0 [/usr/local/bin/R]
+++   NOW PROCESSING Read and reference sequence file input
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Could not open reference file: ChAd-Genome2.gbk
FILE: reference_sequence.cpp   LINE: 807
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Backtrace with 6 stack frames.
0   breseq                              0x000000010a261c15 _ZN6breseq16my_error_handlerEbbbPKcS1_iRKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE + 1253
1   breseq                              0x000000010a4c1e0c _ZN6breseq19cReferenceSequences15PrivateLoadFileERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 380
2   breseq                              0x000000010a4c11bc _ZN6breseq19cReferenceSequences9LoadFilesERKNSt3__16vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS6_IS8_EEEE + 140
3   breseq                              0x000000010a278ea5 _Z21breseq_default_actioniPPc + 1525
4   breseq                              0x000000010a287f66 main + 1718
5   libdyld.dylib                       0x000000010a72a235 start + 1
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
TPhams-MacBook-Pro:~ tpham$ 

Any suggestion on how to solve the problem? Thank you!
Trang

**Comment by dannagifford** [comment]
Check the filename and path of your reference genome "ChAd-Genome2.gbk". Perhaps try specifying the full path.

**Comment by trangthuypham** [comment]
Hi,

Thank you for getting back to me. I was able to run it (and yes the issue
was the path to the reference and data files).

Best,
Trang
------------------------------------------------------------
Trang Pham, PhD.
Research Associate
Turnstone Biologics
401 Smyth Road, Ottawa, ON K1H 8L1
Email: trang.pham@turnstonebio.com
Mobile: 613-617-4541
