### ISSUE TITLE
gdtools ANNOTATE error

### ISSUE THREAD

**Issue by mattbawn** [barricklab/breseq#195]
Hi Jeff,

Im trying to annotate the .gd file using the command:
 `gdtools ANNOTATE -o int-10.test.tsv -r /ei/projects/69d09388-0618-43cf-9b9d-4fc1faa731da/data/raw/References/AM933172_pS1.gb data/output.gd 
`

however this gives me:

```
*** Begin ANNOTATE/COMPARE ***

    Reading input reference sequence files
        /ei/projects/69d09388-0618-43cf-9b9d-4fc1faa731da/data/raw/References/AM933172_pS1.gb

    Reading input GD file: data/output.gd

    Tabulating frequencies of mutations across all files

    Annotating mutations
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
SEQ_ID not found: AM933172
FILE: libbreseq/reference_sequence.h   LINE: 978
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Backtrace with 7 stack frames.
gdtools() [0x4927d3]
gdtools() [0x4a7d64]
gdtools() [0x59f945]
gdtools() [0x486cc0]
gdtools() [0x4538a1]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x7f52313213d5]
gdtools() [0x45eaf7]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Can you give me a clue what I'm doing wrong please? 

Thanks,

Matt

**Comment by jeffreybarrick** [comment]
It seems like you are comparing to a reference genome file that does not contain a sequence named `AM933172` which was there as a reference when _breseq_ was used to predict mutations present in your GenomeDiff file. You use the file under the output named `data/reference.gff3` if you do not have your original reference file as that is the same, just changed into the more parsable format.

**Comment by mattbawn** [comment]
Great. Thank you for the help.
