### ISSUE TITLE
deletion_propagation_coverage ERROR

### ISSUE THREAD

**Issue by luciagrami** [barricklab/breseq#200]
Hello, I am getting this error but only with some of the samples I am running that is why I think this is not solved like some similar issues already posted (installation issues).
Can you help me with this?

Error in if (is.nan(deletion_propagation_coverage) || (deletion_propagation_coverage <  : 
  missing value where TRUE/FALSE needed
Execution halted
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error running command:
[system] R --vanilla < /usr/local/breseq-0.31.0/bin/../share/breseq//coverage_distribution.r > 2_S12/03_candidate_junctions/78.unique_only_coverage_distribution.tab.r.log distribution_file=2_S12/03_candidate_junctions/78.unique_only_coverage_distribution.tab plot_file=2_S12/03_candidate_junctions/78.coverage.pdf deletion_propagation_pr_cutoff=0.00589256
Result code: 256

**Comment by jeffreybarrick** [comment]
I'll be happy to investigate if you can provide a copy of your input FASTQ and reference files from one of the failed runs and the command line you used to call _breseq_ to investigate.

Please contact me via email at the address in the _breseq_ header, and I can share a folder where you can upload any large files.

**Comment by jeffreybarrick** [comment]
I just noticed you are using an older _breseq_ version (v0.31.0). We fixed some bugs since then in working with reference genomes that are assemblies, like yours.

I was able to successfully run _breseq_ on the data you sent using the newest version (v0.33.2), so I think upgrading should fix this for you!

**Comment by luciagrami** [comment]
Ok i Will try that. Thanks a lot!
