### ISSUE TITLE
Segmentation Error during read alignment stage

### ISSUE THREAD

**Issue by jvera888** [barricklab/breseq#201]
Hi,
  I'm running Breseq v0.33.2 and getting the following error during the initial alignment step to a core genome produced using the Spine tool (250 contigs).  The sample reads are Illumina 250bp paired-end trimmed using Trimmomatic.
  When I manually run the first Breseq Bowtie2 command I don't get any errors, so I'm not sure what could be causing the problem.  I will send you the relevant files if needed if you link me your preferred email.

Here's the error:
================================================================================
breseq 0.33.2  revision caddc01d3be9   http://barricklab.org/breseq

Active Developers: Barrick JE, Deatherage DE
Contact:           <jeffrey.e.barrick@gmail.com>

breseq is free software; you can redistribute it and/or modify it under the
terms the GNU General Public License as published by the Free Software 
Foundation; either version 2, or (at your option) any later version.

Copyright (c) 2008-2010 Michigan State University
Copyright (c) 2011-2017 The University of Texas at Austin

If you use breseq in your research, please cite:

  Deatherage, D.E., Barrick, J.E. (2014) Identification of mutations
  in laboratory-evolved microbes from next-generation sequencing
  data using breseq. Methods Mol. Biol. 1151: 165–188.

If you use structural variation (junction) predictions, please cite:

  Barrick, J.E., Colburn, G., Deatherage D.E., Traverse, C.C.,
  Strand, M.D., Borges, J.J., Knoester, D.B., Reba, A., Meyer, A.G. 
  (2014) Identifying structural variation in haploid microbial genomes 
  from short-read resequencing data using breseq. BMC Genomics 15:1039.
================================================================================
+++   NOW PROCESSING Read and reference sequence file input
  READ FILE::A12_GTAGAGGA-GCGTAAGA_L002_R1_trimmed
    Converting/filtering FASTQ file...
    Original base quality format: SANGER New format: SANGER
    Original reads: 1516694 bases: 217752639
    Filtered reads: none
    Analyzed reads: 1516694 bases: 217752639
  READ FILE::A12_GTAGAGGA-GCGTAAGA_L002_R2_trimmed
    Converting/filtering FASTQ file...
    Original base quality format: SANGER New format: SANGER
    Original reads: 1516694 bases: 179680949
    Filtered reads:       2 bases:       196 (≥90.0% same base)
    Analyzed reads: 1516692 bases: 179680753
  ::TOTAL::
    Original reads: 3033388 bases: 397433588
    Analyzed reads: 3033386 bases: 397433392
  REFERENCE: backbone_0001_length_17251
  LENGTH: 17251
  REFERENCE: backbone_0002_length_23547
  LENGTH: 23547
  REFERENCE: backbone_0003_length_14094
  LENGTH: 14094
  REFERENCE: backbone_0004_length_3156
  LENGTH: 3156
  REFERENCE: backbone_0005_length_108
  LENGTH: 108
  REFERENCE: backbone_0006_length_589
  LENGTH: 589
  REFERENCE: backbone_0007_length_536
  LENGTH: 536
  REFERENCE: backbone_0008_length_10096
  LENGTH: 10096
  REFERENCE: backbone_0009_length_27306
  LENGTH: 27306
  REFERENCE: backbone_0010_length_22520
  LENGTH: 22520
  REFERENCE: backbone_0011_length_3657
  LENGTH: 3657
  REFERENCE: backbone_0012_length_26992
  LENGTH: 26992
  REFERENCE: backbone_0013_length_14541
  LENGTH: 14541
  REFERENCE: backbone_0014_length_5372
  LENGTH: 5372
  REFERENCE: backbone_0015_length_34116
  LENGTH: 34116
  REFERENCE: backbone_0016_length_33513
  LENGTH: 33513
  REFERENCE: backbone_0017_length_24924
  LENGTH: 24924
  REFERENCE: backbone_0018_length_9073
  LENGTH: 9073
  REFERENCE: backbone_0019_length_23661
  LENGTH: 23661
  REFERENCE: backbone_0020_length_17480
  LENGTH: 17480
  REFERENCE: backbone_0021_length_3078
  LENGTH: 3078
  REFERENCE: backbone_0022_length_1252
  LENGTH: 1252
  REFERENCE: backbone_0023_length_44405
  LENGTH: 44405
  REFERENCE: backbone_0024_length_16990
  LENGTH: 16990
  REFERENCE: backbone_0025_length_7013
  LENGTH: 7013
  REFERENCE: backbone_0026_length_98070
  LENGTH: 98070
  REFERENCE: backbone_0027_length_289
  LENGTH: 289
  REFERENCE: backbone_0028_length_57901
  LENGTH: 57901
  REFERENCE: backbone_0029_length_35122
  LENGTH: 35122
  REFERENCE: backbone_0030_length_64914
  LENGTH: 64914
  REFERENCE: backbone_0031_length_18709
  LENGTH: 18709
  REFERENCE: backbone_0032_length_77235
  LENGTH: 77235
  REFERENCE: backbone_0033_length_28397
  LENGTH: 28397
  REFERENCE: backbone_0034_length_8412
  LENGTH: 8412
  REFERENCE: backbone_0035_length_6422
  LENGTH: 6422
  REFERENCE: backbone_0036_length_1878
  LENGTH: 1878
  REFERENCE: backbone_0037_length_3014
  LENGTH: 3014
  REFERENCE: backbone_0038_length_265
  LENGTH: 265
  REFERENCE: backbone_0039_length_610
  LENGTH: 610
  REFERENCE: backbone_0040_length_16886
  LENGTH: 16886
  REFERENCE: backbone_0041_length_23882
  LENGTH: 23882
  REFERENCE: backbone_0042_length_32834
  LENGTH: 32834
  REFERENCE: backbone_0043_length_186
  LENGTH: 186
  REFERENCE: backbone_0044_length_136
  LENGTH: 136
  REFERENCE: backbone_0045_length_12881
  LENGTH: 12881
  REFERENCE: backbone_0046_length_29477
  LENGTH: 29477
  REFERENCE: backbone_0047_length_7000
  LENGTH: 7000
  REFERENCE: backbone_0048_length_51939
  LENGTH: 51939
  REFERENCE: backbone_0049_length_308
  LENGTH: 308
  REFERENCE: backbone_0050_length_3231
  LENGTH: 3231
  REFERENCE: backbone_0051_length_20952
  LENGTH: 20952
  REFERENCE: backbone_0052_length_37275
  LENGTH: 37275
  REFERENCE: backbone_0053_length_25722
  LENGTH: 25722
  REFERENCE: backbone_0054_length_9824
  LENGTH: 9824
  REFERENCE: backbone_0055_length_536
  LENGTH: 536
  REFERENCE: backbone_0056_length_7923
  LENGTH: 7923
  REFERENCE: backbone_0057_length_40011
  LENGTH: 40011
  REFERENCE: backbone_0058_length_82545
  LENGTH: 82545
  REFERENCE: backbone_0059_length_15345
  LENGTH: 15345
  REFERENCE: backbone_0060_length_10037
  LENGTH: 10037
  REFERENCE: backbone_0061_length_4613
  LENGTH: 4613
  REFERENCE: backbone_0062_length_74763
  LENGTH: 74763
  REFERENCE: backbone_0063_length_39680
  LENGTH: 39680
  REFERENCE: backbone_0064_length_76654
  LENGTH: 76654
  REFERENCE: backbone_0065_length_17319
  LENGTH: 17319
  REFERENCE: backbone_0066_length_932
  LENGTH: 932
  REFERENCE: backbone_0067_length_15988
  LENGTH: 15988
  REFERENCE: backbone_0068_length_1072
  LENGTH: 1072
  REFERENCE: backbone_0069_length_1021
  LENGTH: 1021
  REFERENCE: backbone_0070_length_11027
  LENGTH: 11027
  REFERENCE: backbone_0071_length_8715
  LENGTH: 8715
  REFERENCE: backbone_0072_length_17366
  LENGTH: 17366
  REFERENCE: backbone_0073_length_1489
  LENGTH: 1489
  REFERENCE: backbone_0074_length_13136
  LENGTH: 13136
  REFERENCE: backbone_0075_length_5487
  LENGTH: 5487
  REFERENCE: backbone_0076_length_7280
  LENGTH: 7280
  REFERENCE: backbone_0077_length_12182
  LENGTH: 12182
  REFERENCE: backbone_0078_length_28602
  LENGTH: 28602
  REFERENCE: backbone_0079_length_159
  LENGTH: 159
  REFERENCE: backbone_0080_length_31268
  LENGTH: 31268
  REFERENCE: backbone_0081_length_2840
  LENGTH: 2840
  REFERENCE: backbone_0082_length_9845
  LENGTH: 9845
  REFERENCE: backbone_0083_length_25516
  LENGTH: 25516
  REFERENCE: backbone_0084_length_35470
  LENGTH: 35470
  REFERENCE: backbone_0085_length_10672
  LENGTH: 10672
  REFERENCE: backbone_0086_length_399
  LENGTH: 399
  REFERENCE: backbone_0087_length_701
  LENGTH: 701
  REFERENCE: backbone_0088_length_209
  LENGTH: 209
  REFERENCE: backbone_0089_length_161
  LENGTH: 161
  REFERENCE: backbone_0090_length_9900
  LENGTH: 9900
  REFERENCE: backbone_0091_length_2560
  LENGTH: 2560
  REFERENCE: backbone_0092_length_2208
  LENGTH: 2208
  REFERENCE: backbone_0093_length_9987
  LENGTH: 9987
  REFERENCE: backbone_0094_length_2436
  LENGTH: 2436
  REFERENCE: backbone_0095_length_5304
  LENGTH: 5304
  REFERENCE: backbone_0096_length_1283
  LENGTH: 1283
  REFERENCE: backbone_0097_length_589
  LENGTH: 589
  REFERENCE: backbone_0098_length_31153
  LENGTH: 31153
  REFERENCE: backbone_0099_length_15992
  LENGTH: 15992
  REFERENCE: backbone_0100_length_7031
  LENGTH: 7031
  REFERENCE: backbone_0101_length_2952
  LENGTH: 2952
  REFERENCE: backbone_0102_length_11216
  LENGTH: 11216
  REFERENCE: backbone_0103_length_2782
  LENGTH: 2782
  REFERENCE: backbone_0104_length_2304
  LENGTH: 2304
  REFERENCE: backbone_0105_length_1044
  LENGTH: 1044
  REFERENCE: backbone_0106_length_726
  LENGTH: 726
  REFERENCE: backbone_0107_length_7568
  LENGTH: 7568
  REFERENCE: backbone_0108_length_1181
  LENGTH: 1181
  REFERENCE: backbone_0109_length_1935
  LENGTH: 1935
  REFERENCE: backbone_0110_length_25365
  LENGTH: 25365
  REFERENCE: backbone_0111_length_8341
  LENGTH: 8341
  REFERENCE: backbone_0112_length_49180
  LENGTH: 49180
  REFERENCE: backbone_0113_length_13446
  LENGTH: 13446
  REFERENCE: backbone_0114_length_19859
  LENGTH: 19859
  REFERENCE: backbone_0115_length_917
  LENGTH: 917
  REFERENCE: backbone_0116_length_18377
  LENGTH: 18377
  REFERENCE: backbone_0117_length_13272
  LENGTH: 13272
  REFERENCE: backbone_0118_length_13580
  LENGTH: 13580
  REFERENCE: backbone_0119_length_47565
  LENGTH: 47565
  REFERENCE: backbone_0120_length_18785
  LENGTH: 18785
  REFERENCE: backbone_0121_length_227
  LENGTH: 227
  REFERENCE: backbone_0122_length_3060
  LENGTH: 3060
  REFERENCE: backbone_0123_length_1268
  LENGTH: 1268
  REFERENCE: backbone_0124_length_11876
  LENGTH: 11876
  REFERENCE: backbone_0125_length_30362
  LENGTH: 30362
  REFERENCE: backbone_0126_length_1854
  LENGTH: 1854
  REFERENCE: backbone_0127_length_10141
  LENGTH: 10141
  REFERENCE: backbone_0128_length_30333
  LENGTH: 30333
  REFERENCE: backbone_0129_length_615
  LENGTH: 615
  REFERENCE: backbone_0130_length_5980
  LENGTH: 5980
  REFERENCE: backbone_0131_length_9610
  LENGTH: 9610
  REFERENCE: backbone_0132_length_134
  LENGTH: 134
  REFERENCE: backbone_0133_length_2012
  LENGTH: 2012
  REFERENCE: backbone_0134_length_19080
  LENGTH: 19080
  REFERENCE: backbone_0135_length_143
  LENGTH: 143
  REFERENCE: backbone_0136_length_17900
  LENGTH: 17900
  REFERENCE: backbone_0137_length_20058
  LENGTH: 20058
  REFERENCE: backbone_0138_length_63331
  LENGTH: 63331
  REFERENCE: backbone_0139_length_5195
  LENGTH: 5195
  REFERENCE: backbone_0140_length_145427
  LENGTH: 145427
  REFERENCE: backbone_0141_length_14254
  LENGTH: 14254
  REFERENCE: backbone_0142_length_75687
  LENGTH: 75687
  REFERENCE: backbone_0143_length_63399
  LENGTH: 63399
  REFERENCE: backbone_0144_length_7516
  LENGTH: 7516
  REFERENCE: backbone_0145_length_14705
  LENGTH: 14705
  REFERENCE: backbone_0146_length_50114
  LENGTH: 50114
  REFERENCE: backbone_0147_length_88626
  LENGTH: 88626
  REFERENCE: backbone_0148_length_4190
  LENGTH: 4190
  REFERENCE: backbone_0149_length_12952
  LENGTH: 12952
  REFERENCE: backbone_0150_length_685
  LENGTH: 685
  REFERENCE: backbone_0151_length_47065
  LENGTH: 47065
  REFERENCE: backbone_0152_length_3024
  LENGTH: 3024
  REFERENCE: backbone_0153_length_26068
  LENGTH: 26068
  REFERENCE: backbone_0154_length_2113
  LENGTH: 2113
  REFERENCE: backbone_0155_length_6921
  LENGTH: 6921
  REFERENCE: backbone_0156_length_65793
  LENGTH: 65793
  REFERENCE: backbone_0157_length_11988
  LENGTH: 11988
  REFERENCE: backbone_0158_length_150573
  LENGTH: 150573
  REFERENCE: backbone_0159_length_6050
  LENGTH: 6050
  REFERENCE: backbone_0160_length_58353
  LENGTH: 58353
  REFERENCE: backbone_0161_length_56173
  LENGTH: 56173
  REFERENCE: backbone_0162_length_12070
  LENGTH: 12070
  REFERENCE: backbone_0163_length_5995
  LENGTH: 5995
  REFERENCE: backbone_0164_length_482
  LENGTH: 482
  REFERENCE: backbone_0165_length_21134
  LENGTH: 21134
  REFERENCE: backbone_0166_length_108
  LENGTH: 108
  REFERENCE: backbone_0167_length_37863
  LENGTH: 37863
  REFERENCE: backbone_0168_length_5590
  LENGTH: 5590
  REFERENCE: backbone_0169_length_118
  LENGTH: 118
  REFERENCE: backbone_0170_length_4204
  LENGTH: 4204
  REFERENCE: backbone_0171_length_5658
  LENGTH: 5658
  REFERENCE: backbone_0172_length_9119
  LENGTH: 9119
  REFERENCE: backbone_0173_length_12263
  LENGTH: 12263
  REFERENCE: backbone_0174_length_8146
  LENGTH: 8146
  REFERENCE: backbone_0175_length_9036
  LENGTH: 9036
  REFERENCE: backbone_0176_length_12916
  LENGTH: 12916
  REFERENCE: backbone_0177_length_31614
  LENGTH: 31614
  REFERENCE: backbone_0178_length_53602
  LENGTH: 53602
  REFERENCE: backbone_0179_length_25049
  LENGTH: 25049
  REFERENCE: backbone_0180_length_5339
  LENGTH: 5339
  REFERENCE: backbone_0181_length_3011
  LENGTH: 3011
  REFERENCE: backbone_0182_length_2665
  LENGTH: 2665
  REFERENCE: backbone_0183_length_8573
  LENGTH: 8573
  REFERENCE: backbone_0184_length_1495
  LENGTH: 1495
  REFERENCE: backbone_0185_length_2725
  LENGTH: 2725
  REFERENCE: backbone_0186_length_4264
  LENGTH: 4264
  REFERENCE: backbone_0187_length_26226
  LENGTH: 26226
  REFERENCE: backbone_0188_length_2810
  LENGTH: 2810
  REFERENCE: backbone_0189_length_2364
  LENGTH: 2364
  REFERENCE: backbone_0190_length_24577
  LENGTH: 24577
  REFERENCE: backbone_0191_length_4293
  LENGTH: 4293
  REFERENCE: backbone_0192_length_930
  LENGTH: 930
  REFERENCE: backbone_0193_length_1620
  LENGTH: 1620
  REFERENCE: backbone_0194_length_866
  LENGTH: 866
  REFERENCE: backbone_0195_length_843
  LENGTH: 843
  REFERENCE: backbone_0196_length_6289
  LENGTH: 6289
  REFERENCE: backbone_0197_length_1292
  LENGTH: 1292
  REFERENCE: backbone_0198_length_26986
  LENGTH: 26986
  REFERENCE: backbone_0199_length_113092
  LENGTH: 113092
  REFERENCE: backbone_0200_length_1190
  LENGTH: 1190
  REFERENCE: backbone_0201_length_7566
  LENGTH: 7566
  REFERENCE: backbone_0202_length_46726
  LENGTH: 46726
  REFERENCE: backbone_0203_length_2075
  LENGTH: 2075
  REFERENCE: backbone_0204_length_155861
  LENGTH: 155861
  REFERENCE: backbone_0205_length_2897
  LENGTH: 2897
  REFERENCE: backbone_0206_length_13387
  LENGTH: 13387
  REFERENCE: backbone_0207_length_1782
  LENGTH: 1782
  REFERENCE: backbone_0208_length_7183
  LENGTH: 7183
  REFERENCE: backbone_0209_length_10534
  LENGTH: 10534
  REFERENCE: backbone_0210_length_28856
  LENGTH: 28856
  REFERENCE: backbone_0211_length_76001
  LENGTH: 76001
  REFERENCE: backbone_0212_length_30215
  LENGTH: 30215
  REFERENCE: backbone_0213_length_1154
  LENGTH: 1154
  REFERENCE: backbone_0214_length_12972
  LENGTH: 12972
  REFERENCE: backbone_0215_length_101590
  LENGTH: 101590
  REFERENCE: backbone_0216_length_10987
  LENGTH: 10987
  REFERENCE: backbone_0217_length_10018
  LENGTH: 10018
  REFERENCE: backbone_0218_length_3027
  LENGTH: 3027
  REFERENCE: backbone_0219_length_251
  LENGTH: 251
  REFERENCE: backbone_0220_length_59851
  LENGTH: 59851
  REFERENCE: backbone_0221_length_2544
  LENGTH: 2544
  REFERENCE: backbone_0222_length_13846
  LENGTH: 13846
  REFERENCE: backbone_0223_length_2407
  LENGTH: 2407
  REFERENCE: backbone_0224_length_19636
  LENGTH: 19636
  REFERENCE: backbone_0225_length_15828
  LENGTH: 15828
  REFERENCE: backbone_0226_length_7741
  LENGTH: 7741
  REFERENCE: backbone_0227_length_16870
  LENGTH: 16870
  REFERENCE: backbone_0228_length_8682
  LENGTH: 8682
  REFERENCE: backbone_0229_length_70408
  LENGTH: 70408
  REFERENCE: backbone_0230_length_4374
  LENGTH: 4374
  REFERENCE: backbone_0231_length_44138
  LENGTH: 44138
  REFERENCE: backbone_0232_length_60932
  LENGTH: 60932
  REFERENCE: backbone_0233_length_4474
  LENGTH: 4474
  REFERENCE: backbone_0234_length_6338
  LENGTH: 6338
  REFERENCE: backbone_0235_length_1536
  LENGTH: 1536
  REFERENCE: backbone_0236_length_3355
  LENGTH: 3355
  REFERENCE: backbone_0237_length_29931
  LENGTH: 29931
  REFERENCE: backbone_0238_length_75014
  LENGTH: 75014
  REFERENCE: backbone_0239_length_75876
  LENGTH: 75876
  REFERENCE: backbone_0240_length_18228
  LENGTH: 18228
  REFERENCE: backbone_0241_length_38181
  LENGTH: 38181
  REFERENCE: backbone_0242_length_62550
  LENGTH: 62550
  REFERENCE: backbone_0243_length_39725
  LENGTH: 39725
  REFERENCE: backbone_0244_length_59041
  LENGTH: 59041
  REFERENCE: backbone_0245_length_748
  LENGTH: 748
  REFERENCE: backbone_0246_length_12511
  LENGTH: 12511
  REFERENCE: backbone_0247_length_15058
  LENGTH: 15058
  REFERENCE: backbone_0248_length_16895
  LENGTH: 16895
  REFERENCE: backbone_0249_length_18137
  LENGTH: 18137
  REFERENCE: backbone_0250_length_4260
  LENGTH: 4260
+++   NOW PROCESSING Read alignment to reference genome
[system] bowtie2-build -q /data/pseudomonas/sequencing_run_16_pl74_CFtypeStrains_Archaea/pipeline_runs/PA_CoreGenome1/Sample_A12_GTAGAGGA-GCGTAAGA_L002/breseq_Paeruginosa_CoreGenome1//data/reference.fasta /data/pseudomonas/sequencing_run_16_pl74_CFtypeStrains_Archaea/pipeline_runs/PA_CoreGenome1/Sample_A12_GTAGAGGA-GCGTAAGA_L002/breseq_Paeruginosa_CoreGenome1//02_reference_alignment/reference
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Segmentation Fault
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Segmentation fault (core dumped)

**Comment by jeffreybarrick** [comment]
Yes, please share files and the command line you used to the email in the _breseq_ header, and I'll take a look.

**Comment by jeffreybarrick** [comment]
I'm not getting any problems using the data you sent and `bowtie2` version 2.3.4.1.

Can you let me know what version of `bowtie2` you are using in case that is related?

(It should be at the top of the output right after the _breseq_ header.)

**Comment by jeffreybarrick** [comment]
Data runs fine in our tests with same versions. Appears to be an issue with the HPC used.
