### ISSUE TITLE
Compile failure under Centos 7-7/gcc 4.8.5-39

### ISSUE THREAD

**Issue by biosas** [barricklab/breseq#207]
Using the latest 0.34.0 release of breseq

./configure was happy, but when I 

make

The error of 
------------------------------
In file included from ./libbreseq/storable.h:25:0,
                 from ./libbreseq/settings.h:24,
                 from libbreseq/fastq.h:23,
                 from libbreseq/alignment.h:25,
                 from libbreseq/pileup.h:23,
                 from libbreseq/alignment_output.h:23,
                 from breseq_cmdline.cpp:24:
./libbreseq/json.hpp:67:10: error: #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
         #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
          ^
make[1]: *** [breseq_cmdline.o] Error 1
make[1]: Leaving directory `/home/rdowner/breseq-0.34.0/src/c/breseq'
make: *** [all-recursive] Error 1

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 
-----------------------------------

The docs say 4.8.5-36 is supported, yet with the upgrade to Centos/Redhat 7.7 we have a version string change of gcc.

Can this be corrected on my end or have I done something dumb?

Thanks and this is a wonderful tool you have developed!

RD

**Comment by jeffreybarrick** [comment]
It's possible the `json.hpp` is being a bit too strict on which GCC version will compile.

Could you try to find the line that looks like this in `src/c/breseq/libbreseq/json.hpp`:
```    
#if (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__) < 40900
```
and change it to
```    
#if (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__) < 40805
```
...so it will let you try to compile, and let me know if it works?

The other option is to use a more recent version of GCC.

**Comment by biosas** [comment]
Looks like a perfect compile with that solution to json.hpp.

running tests now, but that solved the compile problem for Centos and Redhat  7.7  new version of gcc.

Thank you!



Glass keyboard, typos at no extra cost 
(other than your confusion) !

**Comment by jeffreybarrick** [comment]
Thanks! A few other people had also been having this problem. I'll update the code so this goes forward in the next version.
