### ISSUE TITLE
check for header-genome-diff file earlier 

### ISSUE THREAD

**Issue by danieldeatherage** [barricklab/breseq#220]
if header-genome-diff is specified on command line, the listed .gd file isn't accessed until output processing. If header-genome-diff is incorrectly, could not open file for reading error is thrown. 

Would be more helpful to throw at start of run than near end.

**Comment by jeffreybarrick** [comment]
Done in 31b6acc7a2cfc0febdb46dc4b7ee6f839f06dbe9
