### ISSUE TITLE
breseq 0.34.1  GD2VCF

### ISSUE THREAD

**Issue by ksw9** [barricklab/breseq#223]
Hi, 
I am hoping to use breseq to output a VCF so I can compare with other VCFs. I installed breseq 0.34.1  with conda, but I'm unable to find the GD2VCF function described in the paper. Would you please point me towards this function? 

Thank you!

**Comment by jeffreybarrick** [comment]
_breseq_ will output a VCF file by default as `output.vcf` in the `data` subdirectory.

If you already have a GD file that you want to convert, GD2VCF is a subcommand of `gdtools`. You can Run it with no options to see a usage message like this:

```
gdtools GD2VCF
```

**Comment by ksw9** [comment]
Excellent, thank you!
