### ISSUE TITLE
gdtools SUBTRACT- frequencies and marginal evidence mutations

### ISSUE THREAD

**Issue by AAvihail** [barricklab/breseq#226]
Hi,

I am using **Breseq 0.29**, and have two questions regarding the gdtools SUBTRACT command:

1. Does SUBTRACT take into account the mutation frequencies? (I read that later versions disregard frequencies, and there's an optional flag to include frequencies, correct?). What's the status in versions 0.29?

2. Does SUBTRACT take into account mutations in the marginal evidence section? Is there a difference in this respect between version the most recent version?

Thanks in advance for your help!
Avigail

**Comment by jeffreybarrick** [comment]
1. I think that there were problems with using `SUBTRACT` with GD files that have mutation frequencies in versions prior to the ones that have the `--frequency-aware` flag. You can experiment to see how it works, but I'd recommend updating your _breseq_ version.

2. `SUBTRACT` and most `gdtools` commands only work on *mutation* entries (three-letter codes like SNP, DEL, INS, SUB, AMP,...) not *evidence* entries (RA, MC, JC, ...). Generally the evidence entries are removed from the output entirely. There are some exceptions where you can get certain commands to work on and preserve evidence by passing an option. If you have a particular use case that needs *evidence* subtracted we might be able to add that to _breseq_.
