### ISSUE TITLE
Understanding Junction Output

### ISSUE THREAD

**Issue by cyrusmallon** [barricklab/breseq#229]
Hi Barrick Lab and Breseq users:

I hope these questions aren't mundane, but I've looked through the breseq literature and issues page on github, yet still cant get a solid understanding of a junction's output. If anyone could provide some direction, I'd be grateful. I am running version 0.34.1. Below are some outputs and specific questions.

--In the output below, it's clear I have an insertion. The actual junction sequence is 43 bp long (+ACT...AGA), yet the mutation is listed as being 122 bp long. **Why doesn't the mutation sequence correspond with the junction sequence? After all, the new junction _is_ the mutation, right?**

--Furthermore, in the two fields for 'reads (cov)', **what is the 'cov' value?** **And in the 'reads (cov)' field with the junction sequences, are the number of reads listed only those reads that span the whole junction?**

![JC_Ins_2a](https://user-images.githubusercontent.com/56315077/72258371-2ff13380-360e-11ea-9bf1-9540c02a3758.PNG)

--In the next output below, I'm not quite sure what type of junction I'm supposed to be seeing. Above all, **why is the mutation sequence enclosed in parentheses followed by the subscript '1→2'?**  My guess is that this might be a repetitive sequence that has been deleted. I say this because when clicking on the  '?' link (last fig show), showing a mix of reads that align to the old reference or the new junction , it's clear that the aforementioned sequence (highlighted in yellow) is duplicated in the aligned reads that are shown. Yet that same sequence, either once or duplicated, is not shown in the new junction and corresponding alignments. 

![JC_del](https://user-images.githubusercontent.com/56315077/72263750-c70fb880-3619-11ea-9a22-b341f115c264.PNG)

![JC_del1a](https://user-images.githubusercontent.com/56315077/72265169-51f1b280-361c-11ea-953d-1efdefd779ff.PNG)

Any help on these questions is greatly appreciated!

**Comment by jeffreybarrick** [comment]
These are good questions. Interpreting JC evidence is tricky.

> --In the output below, it's clear I have an insertion. The actual junction sequence is 43 bp long (+ACT...AGA), yet the mutation is listed as being 122 bp long. Why doesn't the mutation sequence correspond with the junction sequence? After all, the new junction is the mutation, right?

This is an interesting one. If you look at the coordinates in the two reference lines, you will find that they indicate that two things are happening in this prediction. 1st: Some of the reference bases are duplicated. 2nd: There is an insertion of some bases that are not in the reference sequence (the ones clearly visible in the alignment). Together that leads to the 122 bp insertion.

> --Furthermore, in the two fields for 'reads (cov)', what is the 'cov' value? And in the 'reads (cov)' field with the junction sequences, are the number of reads listed only those reads that span the whole junction?

The two-row "reads (cov)" is the coverage at the original locations in the reference genome on each side of the junction. The one-row "reads (cov)" is for the new junction. Both only count reads that fully span the junction.

> --In the next output below, I'm not quite sure what type of junction I'm supposed to be seeing. Above all, why is the mutation sequence enclosed in parentheses followed by the subscript '1→2'? My guess is that this might be a repetitive sequence that has been deleted. I say this because when clicking on the '?' link (last fig show), showing a mix of reads that align to the old reference or the new junction , it's clear that the aforementioned sequence (highlighted in yellow) is duplicated in the aligned reads that are shown. Yet that same sequence, either once or duplicated, is not shown in the new junction and corresponding alignments.

The 1→2 means that the bases in parentheses went from one to two copies (were duplicated). If you look at the junction's coordinates, you will notice that they jump such that bases X222-X246 are included twice, meaning they were duplicated.  They don't show up as looking like columns that don't match the reference in the alignment b/c they are not a novel insertion.
