### ISSUE TITLE
Annotate mobile elements in a completed breseq run

### ISSUE THREAD

**Issue by sleyn** [barricklab/breseq#231]
Hi!

I've completed to analyze bunch of clones with breseq and realized that I was using Fasta file as reference instead of GBK file. As a result I don't have annotations. SNPs and indels I can annotate with GDTOOLS. The biggest problem is mobile elements.

Is this correct that I could not automatically annotate moblie elements from the output?

Thanks in advance!

**Comment by jeffreybarrick** [comment]
Yes, I'm afraid so. Unfortunately, it's not possible to re-do that part of the analysis with a separate _gdtools_ or _breseq_ subcommand from the final results.
