### ISSUE TITLE
gdtools ANNOTATE JSON format request

### ISSUE THREAD

**Issue by vr1087** [barricklab/breseq#232]
Hi Jeff, 

We are looking to transform JSON-formated variant data for database input. The current output that gdtools ANNOTATE produces is suitable for our purposes except that it is missing the sequencing depth for predicted mutations. Unfortunately, I can't check if the `--preserve-evidence` flag does this since it seems to break the command in v0.35.0. 

Can the sequencing depth for predicted mutations be included for JSON format by default? Additionally, does the mentioned flag cause all evidence fields to be included in the JSON output? I would be helpful for downstream analysis to capture this more fine-grained information in our database, but at minimum the sequencing depth should suffice.

Thanks!

**Comment by jeffreybarrick** [comment]
We can definitely work on making sure the JSON output version of a GD file has all of the information you would normally find there. If we fix the `--preserve-evidence` bug, then you should be able to pick it up from the corresponding RA evidence items.

**Comment by jeffreybarrick** [comment]
The `--preserve-evidence` bug is now fixed in b941d1c0c7702d34983ba56ce8f08fe48b888085 and will be in the next release. You'll need to find the RA item for a mutation to get to the coverage info. Does that work for you?
