### ISSUE TITLE
Failed to generate coverage plot

### ISSUE THREAD

**Issue by ramiroricardo** [barricklab/breseq#235]
Hi,

I am running breseq in clonal mode. With version 0.35.0 breseq always fails to generate coverage plots for missing coverage evidence. However, version 0.34.1 generates these plots. Below is an example output of both versions for the same mutation. 

**version 0.35.0**
<img width="839" alt="v0 35 0" src="https://user-images.githubusercontent.com/20688427/77468845-189ca680-6e06-11ea-9d4c-b1a39a648d0a.png">

**version 0.34.1**
<img width="839" alt="v0 34 1" src="https://user-images.githubusercontent.com/20688427/77469037-64e7e680-6e06-11ea-8f46-dc218e3d61c7.png">

**Comment by jeffreybarrick** [comment]
OK. I see this error and can reproduce it on my side. I will investigate.

**Comment by jeffreybarrick** [comment]
Fixed in v0.35.1 which was just posted.
