### ISSUE TITLE
breseq on galaxy

### ISSUE THREAD

**Issue by barichd** [barricklab/breseq#236]
Hello,

I would like to make breseq available to researchers at my institution via the galaxy platform.  Can I install breseq on one of the publicly available Galaxy servers, or do I have to create my own local Galaxy server for breseq?

Thanks.

**Comment by jeffreybarrick** [comment]
We don't place any restrictions in what type of Galaxy server you can install _breseq_ on. So, hopefully you can get installed on one of the public servers. The admin will need to "whitelist" the _breseq_ tool for the HTML output to display correctly in your browser within Galaxy.

https://toolshed.g2.bx.psu.edu/view/iuc/breseq/85c57cc9b558

There is more info on develpment of the Galaxy tool here:

**Comment by jeffreybarrick** [comment]
We don't place any restrictions in what type of Galaxy server you can install breseq on. So, hopefully you can get installed on one of the public servers. The admin will need to "whitelist" the breseq tool for the HTML output to display correctly in your browser within Galaxy.

Here's the toolshed page:
https://toolshed.g2.bx.psu.edu/view/iuc/breseq/85c57cc9b558

There is more info on using _breseq_ within Galaxy here:
https://github.com/barricklab/breseq/issues/209

**Comment by barichd** [comment]
I created an account on the main usegalaxy server, but how do I request to have breseq installed?

**Comment by jeffreybarrick** [comment]
I think you can ask for tools to be installed by posting here: https://help.galaxyproject.org/
