### ISSUE TITLE
breseq with long reads (nanopore)

### ISSUE THREAD

**Issue by francescodc87** [barricklab/breseq#244]
Hi everyone,
I have used breseq with Illumina reads several times now and it works great.
I am recently working with nanopore reads, and running breseq with default parameters is taking a very long time. For top I can see that is stuck with bowtie2-align-s.
I couldn't find anything in the documentation regarding this, and I was wondering if there is anything different when I am handling long reads.
Many thanks,
Francesco

**Comment by jeffreybarrick** [comment]
Hi Franceso,

Unfortunately, very long reads (like from Nanopore) break some of the assumptions of how _breseq_ maps reads and predicts mutations. Entirely different algorithms are more appropriate for using the long reads, like performing de novo assembly, and then comparing the assemblies to predict mutations.

That said, you could probably shoehorn your data into something _breseq_ will be fine using by splitting your reads into ~500 bp chunks. (Of course, this gets rid of the advantages of the long-read data in terms of finding complex structural variants.) I could probably recruit someone to make a script to do this, if you want to see if this would work on your data and can share some example input files with us.

**Comment by francescodc87** [comment]
HI Jeffrey,
thank you very much for your answer.
After looking closer at the breseq documentation, I noticed that breseq uses bowtie2 for the reads alignment, which doesn't work well with long reads. I also noticed that breseq can accept an aligned sam file (--aligned-sam) instead of the raw reads.
Therefore, I am currently aligning the nanopore reads with bwa mem (which I found works very well with long reads) and I want to use the output as input for breseq.
Do you think this approach can be helpful?

At this stage, I am not sure if I am allowed to share this data.

**Comment by francescodc87** [comment]
Thanks Jeffrey,
This should work for my purposes and in order to check for IS insertions I will do a de novo assembly and compare the assemblies.
