### ISSUE TITLE
Fatal error, plasmid reference

### ISSUE THREAD

**Issue by he-hai** [barricklab/breseq#245]
Hi,  

I experienced a error using the new version of breseq (0.35.1, with bowtie 2.4.1 and R 4.0.2). I did the same assembly with the old version (0.31.0, with bowtie 2.2.5 and R 3.2.2), it works fine.  

I assemble the reads to two references, genome and a plasmid. Using the new version, I got a fatal error. I double checked by just run with either the genome or the plasmid as reference. When using genome, it works fine, but I got the error when using plasmid, please see the screenshot below. 

![image](https://user-images.githubusercontent.com/52635520/88455545-6558c280-ce76-11ea-9d8d-6cbb24ed551f.png)

A gene on the plasmid also exists in the genome. Not sure if this is relevant, because it worked with the old version. 

Thank you.

**Comment by jeffreybarrick** [comment]
Hello, thanks for letting us know about this problem.

If you can email me the plasmid file and maybe also the genome reference file at the address in the _breseq_ header, I can take a look at what is going wrong.

**Comment by he-hai** [comment]
> 
> 
> Hello, thanks for letting us know about this problem.
> 
> If you can email me the plasmid file and maybe also the genome reference file at the address in the _breseq_ header, I can take a look at what is going wrong.

Thanks for the fast response. I just solved the problem. 

The plasmid was constructed in Snapgene and was exported to .gb file in Vector NTI(R) format. Now I exported in standard GenBank format, it works fine.  Maybe you could close the this. Thanks. 

(if I remember correctly, I have to export to Vector NTI(R) format before using the older version of both breseq and Snapgene)
