### ISSUE TITLE
Fatal error with reference file

### ISSUE THREAD

**Issue by ppat818** [barricklab/breseq#246]
I have been getting the following error when trying to run *breseq* on my own data. 

**Repeat feature must have only one location: 
Please rename the duplicates so that they have unique locus_tags & names, e.g., gene_1 and gene_2
FILE: reference_sequence.cpp   LINE: 731**

I had downloaded the reference file from NCBI, as described in the breseq tutorial (FN54302-1.gbk). I then tried again with a different reference file that had the repeated "locus_tag" deleted (FN543201e.gbk) and it gave me the same error on the same line. 

Help please. I have attached my reference files in the attached .zip folder.

[CR_Ref.zip](https://github.com/barricklab/breseq/files/5038402/CR_Ref.zip)

**Comment by jeffreybarrick** [comment]
Hi. This appears to be an issue that we have already fixed in a pre-release version. I've just posted a new release version (v0.35.2) that includes the fix. With this version, you should see a warning, but it will continue to execute.

https://github.com/barricklab/breseq/releases/tag/v0.35.2

Let me know if this does not fix your problem!

**Comment by ppat818** [comment]
Thanks for you speedy reply! The new release fixed the reference file issue but now I'm getting this error:

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error running command:
[system] R --vanilla < "/home/manager/miniconda3/bin/../share/breseq/coverage_distribution.r" > "L1_output/03_candidate_junctions/0.unique_only_coverage_distribution.tab.r.log" --args distribution_file="L1_output/03_candidate_junctions/0.unique_only_coverage_distribution.tab" plot_file="L1_output/03_candidate_junctions/0.coverage.pdf" deletion_propagation_pr_cutoff=2.16236e-05
Result code: -1
FILE: libbreseq/common.h   LINE: 1453

Is this an issue that I can fix using some command?

**Comment by jeffreybarrick** [comment]
It may be that you moved some of the files?

Or, it may be related to known problem with the R build that is installed by conda.

In that case, you might try, running this command:
```
conda update -c rdonnellyr -c main --all
```
If that doesn't fix, please paste the output from running this command. (From the same directory you ran _breseq_)
```
R --vanilla < "/home/manager/miniconda3/bin/../share/breseq/coverage_distribution.r" > "L1_output/03_candidate_junctions/0.unique_only_coverage_distribution.tab.r.log" --args distribution_file="L1_output/03_candidate_junctions/0.unique_only_coverage_distribution.tab" plot_file="L1_output/03_candidate_junctions/0.coverage.pdf" deletion_propagation_pr_cutoff=2.16236e-05
```

**Comment by ppat818** [comment]
Updating R didn't work. The second command returned me back to my command line without an output:

`(base) manager@x86_64-conda_cos6-linux-gnu[L1] R --vanilla < "/home/manager/miniconda3/bin/../share/breseq/coverage_distribution.r" > "L1_output/03_candidate_junctions/0.unique_only_coverage_distribution.tab.r.log" --args distribution_file="L1_output/03_candidate_junctions/0.unique_only_coverage_distribution.tab" plot_file="L1_output/03_candidate_junctions/0.coverage.pdf" deletion_propagation_pr_cutoff=2.16236e-05
(base) manager@x86_64-conda_cos6-linux-gnu[L1] `

**Comment by jeffreybarrick** [comment]
Right. It's piping the output to this file `L1_output/03_candidate_junctions/0.unique_only_coverage_distribution.tab.r.log`. 

Post the output of running this command now (or find the file and open it):
```
cat L1_output/03_candidate_junctions/0.unique_only_coverage_distribution.tab.r.log
```

Or rerun this command and the output will go to the terminal:
```
R --vanilla < "/home/manager/miniconda3/bin/../share/breseq/coverage_distribution.r" --args distribution_file="L1_output/03_candidate_junctions/0.unique_only_coverage_distribution.tab" plot_file="L1_output/03_candidate_junctions/0.coverage.pdf" deletion_propagation_pr_cutoff=2.16236e-05
```

Thanks

**Comment by ppat818** [comment]
Here's the file.

[0.unique_only_coverage_distribution.tab.r.log](https://github.com/barricklab/breseq/files/5054100/0.unique_only_coverage_distribution.tab.r.log)

**Comment by jeffreybarrick** [comment]
If this was the output file and there was no error at the terminal, then it seems like this step is working fine.

Maybe try deleting your existing `L1_output/` and running things again from the beginning?

**Comment by ppat818** [comment]
Will try that, thanks!

**Comment by ppat818** [comment]
It worked! Thanks!
