### ISSUE TITLE
breseq aborted

### ISSUE THREAD

**Issue by dabadgarcia** [barricklab/breseq#250]
Hello, 

I'm experiencing a problem when running breseq with my own samples: 

7fb8f01cf000-7fb8f01d0000 rw-p 00000000 00:00 0
7fb8f01e5000-7fb8f01e8000 rw-p 00000000 00:00 0
7fb8f01e8000-7fb8f01ea000 r-xp 00000000 00:00 0                          [vdso]
7fb8f01ea000-7fb8f01eb000 r--p 00021000 fd:00 41943396                   /usr/lib64/ld-2.17.so
7fb8f01eb000-7fb8f01ec000 rw-p 00022000 fd:00 41943396                   /usr/lib64/ld-2.17.so
7fb8f01ec000-7fb8f01ed000 rw-p 00000000 00:00 0
7ffe8b7dc000-7ffe8b7ff000 rw-p 00000000 00:00 0                          [stack]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted

The funny thing is that the tutorial works perfectly fine, but now it is unable to create the html files in the output folder. 

I installed breseq with conda and used this command: 

breseq -r Pseudomonas_aeruginosa_PAO1_JIEO01000001.gbk raw_reads/MS6003_S23_L001_R1_001.fastq.gz raw_reads/MS6003_S23_L001_R2_001.fastq.gz -n MS6003 -o breseq/MS6003 -j 32

Do you have any idea what happened?

Best regards, 

David.

**Comment by jeffreybarrick** [comment]
Hi. This looks like a just discovered bug in v0.35.3. Please upgrade to v0.35.4, which we just released to fix it when that becomes available on conda. As a workaround in the meantime, you can get runs to finish the output step by re-running the same _breseq_ command but changing the `-j 32` to `-j 1` after the crash.

**Comment by dabadgarcia** [comment]
Hi Jeffrey, 

Thanks for your quick reply. 

I changed `-j 32` to `-j 1`, but I got a different error: 

Creating index HTML table...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

Although this time breseq successfully created the index.html file :) 

I will try to upgrade to v0.35.4 and see what happens. 

All the best, 

David.

**Comment by jeffreybarrick** [comment]
Yeah, sorry. We introduced a problem in that version when we multithreaded the output to speed things up. Should be fixed in v0.35.4. That last error you are seeing now with `-j 1` is harmless. It occurs when processing is done and memory is being deallocated.

**Comment by dabadgarcia** [comment]
It works! Thanks a lot!
