### ISSUE TITLE
Genbank files from Prokka cause fatal error in 0.35.4

### ISSUE THREAD

**Issue by stevenjdunn** [barricklab/breseq#252]
Using a genbank file as a reference straight from Prokka causes the following error:

`+++   NOW PROCESSING Read and reference sequence file input
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Seq id  does not contain any valid alphanumeric characters.
FILE: libbreseq/reference_sequence.h   LINE: 1192
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Backtrace with 10 stack frames.
breseq(+0x1d926) [0x55b008d1c926]
breseq(+0x171015) [0x55b008e70015]
breseq(+0x185df9) [0x55b008e84df9]
breseq(+0x186fa5) [0x55b008e85fa5]
breseq(+0x18cfda) [0x55b008e8bfda]
breseq(+0x18d47c) [0x55b008e8c47c]
breseq(+0x494bf) [0x55b008d484bf]
breseq(+0xe652) [0x55b008d0d652]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fbcce6fa840]
breseq(+0x1cac9) [0x55b008d1bac9]`

#242 discusses something similar, and the comments regarding the accession and version fields pointed me in the right direction - this is mentioned in Prokka's manual in regards to Mauve:
>It does not like the ACCESSION and VERSION strings that Prokka produces via the "tbl2asn" tool. The following Unix command will fix them: egrep -v '^(ACCESSION|VERSION)' prokka.gbk > mauve.gbk

Running the suggested command to strip these fields allows Breseq to run with no problems, just thought I'd share this here in case it helps someone.

Thanks for the great bit of software!

**Comment by jeffreybarrick** [comment]
Thanks for the post!

Can you post the header part of one of these GenBank records? I thought I'd relaxed _breseq_ so that it would work with the Prokka default output, but maybe that was't 100% successful.

**Comment by stevenjdunn** [comment]
Sure, sorry for the belated response. Difference is on lines 3 + 4.

Before: 

    ==> Example.gbk <==
    LOCUS       Example            4803312 bp    DNA     linear       13-OCT-2020
    DEFINITION  Genus species strain strain.
    ACCESSION
    VERSION
    KEYWORDS    .
    SOURCE      Genus species
      ORGANISM  Genus species
                Unclassified.
    COMMENT     Annotated using prokka 1.14.6 from
                https://github.com/tseemann/prokka.
    FEATURES             Location/Qualifiers
         source          1..4803312
     
After:

    ==> Example_fix.gbk <==
    LOCUS       Example            4803312 bp    DNA     linear       13-OCT-2020
    DEFINITION  Genus species strain strain.
    KEYWORDS    .
    SOURCE      Genus species
      ORGANISM  Genus species
                Unclassified.
    COMMENT     Annotated using prokka 1.14.6 from
                https://github.com/tseemann/prokka.
    FEATURES             Location/Qualifiers
         source          1..4803312
                         /organism="Genus species"
                         /mol_type="genomic DNA"

**Comment by jeffreybarrick** [comment]
Thanks! _breseq_ was able to check for missing ACCESSION and VERSION lines but not empty ones like this. I've updated things so it should be directly compatible with Prokka reference files in the next release.
