### ISSUE TITLE
Large percent mapped reads discrepancy between two input files

### ISSUE THREAD

**Issue by fisherluke** [barricklab/breseq#253]
Hello,

After successfully running breseq, my summary file indicated that one of my read files mapped 96.3% of reads, while the other only mapped 47.1% to the reference genome. The fastqc quality reports for both files were nearly identical and was wondering what the next step would be for identifying the problem. I would appreciate any help or insight.

Luke

**Comment by jeffreybarrick** [comment]
Do you see that the ends of some reads are not aligning from the 2nd file (when you click on a mutation)? It may be that it is not being trimmed of adaptor sequences. _breseq_ will only map reads for which 90% of their length aligns by default. You could also try setting this threshold to be lower with `--require-match-fraction 0.5` or something like that.

**Comment by fisherluke** [comment]
Thanks for the quick response Professor Barrick, sorry for the delay. Not trimming adaptor sequences seemed to be the issue. I also tried using a different reference sequence which resulted in a far greater percent coverage (~45% to 98%) although the two reference genomes are nearly identical. Just out of curiosity, do you know why this might be the case?

**Comment by jeffreybarrick** [comment]
Glad trimming fixed the problem.

I'm not sure why changing the reference would have changed things.
