### ISSUE TITLE
FATAL ERROR: Provided translation table #0 does not have 64 codons.

### ISSUE THREAD

**Issue by PandengWang** [barricklab/breseq#254]
Thanks for providing this so useful tool!

Below is the error info:

> +++   NOW PROCESSING Output
Creating merged genome diff evidence file...
Predicting mutations from evidence...
----------------------------------> WARNING <-----------------------------------
Large number of differences detected between the sample and the reference sequence (95666 evidence items, suggesting approximately 2.07% sequence divergence). If this is unexpected, check that you are using the closest available reference sequence for this sample (for example, the correct strain of a bacterial species). Mutation prediction can become less accurate with too much divergence from the reference sequence. It may also take a long time to predict mutations and generate output files.
 Preparing junctions...
  Predicting mobile element insertions...
  Predicting large deletions...
  Predicting small indels and substitutions from junctions...
  Predicting small indels and substitutions from alignments...
  Reconciling mutation predictions...
  Making final adjustments to mutations...
  Writing final GD file...
  Writing final VCF file...
Annotating mutations...
>!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Provided translation table #0 does not have 64 codons..
FILE: reference_sequence.cpp   LINE: 2727
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Backtrace with 7 stack frames.
breseq(+0x1d926) [0x55c0064da926]
breseq(+0x190b94) [0x55c00664db94]
breseq(+0x19948e) [0x55c00665648e]
breseq(+0x4e654) [0x55c00650b654]
breseq(+0xe652) [0x55c0064cb652]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x7fb0eddbc505]
breseq(+0x1cac9) [0x55c0064d9ac9]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

The reference genome (CP009273.1, https://www.ncbi.nlm.nih.gov/nuccore/CP009273.1/) I used was downloaded from NCBI in GBK format.
**breseq 0.35.4**
 **bowtie2  :: version 2.4.2 [/mdata/lijl/software/miniconda3/bin/bowtie2]**
**R        :: version 3.5.1 [/mdata/lijl/software/miniconda3/bin/R]**

Do you have any clues for this error?

**BY THE WAY, is it possible to continue to run the pipeline from the break instead of re-run it from the beginning?** 

Thanks!

Pandeng

**Comment by jeffreybarrick** [comment]
Thanks for reporting the problem.

I was able to guess what is happening and make a test case that reproduces the problem. I'm working on fixing it now.

> BY THE WAY, is it possible to continue to run the pipeline from the break instead of re-run it from the beginning?

Yes, _breseq_ checkpoints itself. As long as you run it again with the same options it can pick up close to where it left off.

> Large number of differences detected between the sample and the reference sequence (95666 evidence items, suggesting approximately 2.07% sequence divergence).

That is very, very high sequence divergence! — which is why you found a bug related to a rare edge case. Surely, you can find a better reference file if this is an enterobacterium of some kind?

**Comment by jeffreybarrick** [comment]
This should be fixed in the new release of v0.35.5. Let me know if it isn't.
https://github.com/barricklab/breseq/releases/tag/v0.35.5

**Comment by PandengWang** [comment]
> This should be fixed in the new release of v0.35.5. Let me know if it isn't.
> https://github.com/barricklab/breseq/releases/tag/v0.35.5

Thanks so much!
I'll have a try.
