### ISSUE TITLE
How someone can concatenate the info of syn/non.syn mutations to the predicted mutations file

### ISSUE THREAD

**Issue by loukesio** [barricklab/breseq#256]
Thank you for breseq and all your work,

I find it hard when I take the info from the index.html file from the output to organise my info in R.
For example I want to know if a mutation is a synonymous or non.synonymous and I have to look in .gd file. 
I have tried to concatenate the infos but opening .gd in R is a real pain. 

Do you have any tip for this?

Thank you for your time

**Comment by jeffreybarrick** [comment]
I missed this issue somehow, sorry it has taken so long to respond!

The easiest way to load GD file information into R is to convert the GD file into a tab separated values file using `gdtools ANNOTATE`. The command should look something like thisL

```
gdtools ANNOTATE -f TSV -r reference.gbk -o output.tsv input.gd
```

This file will have a column for the `snp_type` field if I remember correctly.

**Comment by loukesio** [comment]
Thank you for your time :) 
I appreciate
