### ISSUE TITLE
Advice with annotating *.gd file with deletions and SNPs

### ISSUE THREAD

**Issue by lthomp06** [barricklab/breseq#257]
Hello,

Thank you for the very thorough walkthrough of Breseq in Deatherage & Barrick, 2014. I have been following this tutorial in attempt to analyze my own NGS data of heavily mutated lab strains of E. coli.

I am trying to follow the walkthrough to annotate my gd file to allow me to compare two mutants directly, rather than compare each to wild-type separately. Each mutant has 9 gene deletions and 4 point mutations that I already know of, I am looking for other (probably small) differences between them. 
![Screen Shot 2021-01-29 at 10 02 44 AM](https://user-images.githubusercontent.com/73918419/106291047-263a6e00-6219-11eb-8f4d-9ad8160a1f82.png)

 When adding these deletions to the .gd file, I receive many warnings. For example:
----------------------------------> WARNING <-----------------------------------
Coordinate (-244968) requested for get_sequence_1 is < 1.
FILE: ./libbreseq/fasta.h   LINE: 3a
--------------------------------> STACK TRACE <---------------------------------
0x00000001002dcb06 _ZNK6breseq14cFastaSequence25correct_coordinate_boundsERx
0x00000001002bfd5a _ZN6breseq19cReferenceSequences14get_sequence_1ERKNSt3__112basi
0x000000010036ad28 _ZN6breseq11cGenomeDiff18apply_to_sequencesERNS_19cReferenceSeq
0x0000000100270d56 _Z8do_applyiPPc
0x00000001002c74df main

I haven't been able to find information on how to interpret these warnings. If I run breseq with the resulting mutated reference gff, only 1.8% of my reads map the reference genome and the reference genome decreases to 86,151 bp (instead of 4,631,469 bp, deletions account for only 19,617 bp). I assume that this mutated reference file is not valid to use, although I am unsure how to correct this. Any guidance would be greatly appreciated.

**Comment by jeffreybarrick** [comment]
I suspect this is related to how you moved coords from MC lines into DEL lines in the GD file.

For the MC lines you started with (or the numbers in the HTML table), they have the format:
`seq_id<tab>start<tab>end<tab>start_range<tab>end_range`

The DEL lines have the coordinates specified in a different way.
`seq_id<tab>position<tab>size`

(Why, you might well ask? Only the DEL way is compatible with making one mutation that deletes a portion of a circular DNA that overlaps the origin.)

Is this the issue?

[The GD file line specifications are described here](https://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/gd_format.html).

It looks like these are rationally constructed deletions in your reference genome. If you know the sequence of the cassette/scar that is there in the genome, the best thing to do would be to add that sequence in place of the deleted bases at each site so there is no chance of reads mapping there inadvertently mapping elsewhere. This can be accomplished via a SUB or INT entry. It looks like this probably does not matter much for your case though.

**Comment by lthomp06** [comment]
Hello,

Thank you for your advice with breseq! Apologies but I am no pro at command-line programs. I successfully coded the deletions in the correct format that you pointed out and it was very insightful. I am now trying to code in the scar sequence (an FRT site) into each deletion for the most accurate reference sequence.

I have been trying to use the SUB/INT commands to do this, however, I keep getting errors. To code in the FRT sites, should I remove the DEL commands and only use an INT command?

Any insight would be greatly appreciated.
Thank you,

Laura Thompson
Cox Lab | Molecular and Cellular Biology
University of Guelph

________________________________

**Comment by jeffreybarrick** [comment]
I'd have to see your files and know a little bit more to give specific advice.

The INT command will insert ("integrate") a sequence and feature annotations from another input sequence.

If you do not care about carrying over the annotations (which I think is the case), then you may want to make just one SUB for each gene deletion that has coords for the region that was replaced with the FRT site and then has the sequence of the FRT site as the replacement. (You will need to reverse-complement the replacement sequence if the FRT site was on the opposite strand.)
