### ISSUE TITLE
unique fields (tags)

### ISSUE THREAD

**Issue by abrozzi** [barricklab/breseq#258]
Dears,
can you provide the list of unique fields (tags) that are present in the output?

For example parsing a ```.gd``` output I saw that ```SNP``` modification can have these fields (23): 

```
     frequency ,
     gene_name,
     gene_position,
     gene_product,
     gene_strand,
     genes_promoter,
     locus_tag,
     locus_tags_promoter,
     mutation_category,
     position_end,
     position_start,
     ref_seq,
     snp_type,
     aa_new_seq,
     aa_position,
     aa_ref_seq,
     codon_new_seq,
     codon_number,
     codon_position,
     codon_ref_seq,
     genes_overlapping,
     locus_tags_overlapping,
     transl_table
```

I created this list parsing the unique tags (```frequency=```, ```aa_ref=```) from each line of one single output file but I am not sure there might be more...

Can you also provide a list of all unique tags for all the other modifications (```RA```,``` INS```, ```DEL```,...etc...)? 

Finally is there already a script like ```gd2tab_separated_value.py``` ?

Much appreciated!

Bests,
-A

**Comment by jeffreybarrick** [comment]
Yes, there is already a way to convert one or more GenomeDiff files to a TSV and to several other formats using the `gdtools` utility program that comes with _breseq_.

`gdtools ANNOTATE -f TSV -o output.tsv input.gd`

The fields vary a bit from entry to entry and whether you have annotated it with additional fields used in outputting HTML. I don't have a definitive list of all of them. (They are meant to be extensible so others could be added later, as well.)

[The description of GenomeDiff format is here.](https://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/gd_format.html)

It has the required fields listed for each type of entry.

Let us know if you have any other questions or if we can make things easier to accomplish what you are working on.

**Comment by abrozzi** [comment]
Thank you very much Jeffrey!
I will use ```gdtools```. Brilliant. 
In my repo ```microbio``` I started few years ago working on some R parsers for gd files. With your info I can complete that effort.
In our lab we make an extensive usage of ```breseq```, and I take opportunity to reward your work!

With Regards,
-A
