### ISSUE TITLE
bam2aln bwa compatibility issues

### ISSUE THREAD

**Issue by wumuyao1996** [barricklab/breseq#259]
The attached screenshots could probably tell you more than i can.

Our group is really used to the alignment reports generated by breseq for individual mutations found.

I've been trying to use bam2aln for other aligners as well. Namely bwa mem
I've also tried with bwa aln/sampe and had the same issues.

The data is from paired end sequencing of ecoli mg1655.
Another interesting thing is a lot of the alignment lengths in the reports are much longer than the read lengths.

<img width="2452" alt="Screen Shot 2021-02-15 at 9 30 45 PM" src="https://user-images.githubusercontent.com/7231536/108022278-1cfd1f80-6fd5-11eb-944c-ede0b4caa82c.png">
<img width="2438" alt="Screen Shot 2021-02-15 at 9 30 56 PM" src="https://user-images.githubusercontent.com/7231536/108022282-1f5f7980-6fd5-11eb-9690-867c354e2233.png">

Would this be an easy fix? Is there something i'm doing obviously wrong?

**Comment by wumuyao1996** [comment]
The same issue seems to be there when i used bowtie2 to align as well. Is there a step that you guys do in breseq that i'm just not doing?

**Comment by jeffreybarrick** [comment]
The SAM/BAM gets domesticated a bit by _breseq_, but I can't think of a reason that it should break doing what you want to do with bam2aln. Can you post an example of the alignment commands you are running, including to generate the BAM file, and the bam2aln command? (Are you doing paired-end mapping?) I'll see if I can reproduce the problem.

**Comment by wumuyao1996** [comment]
Ok so it s definitely not supposed to look like that. Good to know.
I've tried a few different commands but the set i'm trying to use is the following:

first the alignment with the paired end option:
bwa mem -P NC000913.3.fa Glucose_ALE_6_FLASK_238_Isolate_1_S4_L001_R1_001.fastq Glucose_ALE_6_FLASK_238_Isolate_1_S4_L001_R2_001.fastq > aligned.sam

Then sorted with gatk SortSam. I also tried using the samtools sorting function as well.

gatk SortSam -I="aligned.sam" -O="sortsam_sorted.bam" -SO=coordinate

gatk AddOrReplaceReadGroups -I=sortsam_sorted.bam -SM=20 -LB=lib1 -PL=illumina -PU=unit1 -O=sorted_sam_with_RG_added.bam

Then indexed with samtools
samtools index sorted_sam_with_RG_added.bam

The alignments look normal on IGV.

**Comment by wumuyao1996** [comment]
The bam2aln command is the following:
 breseq bam2aln -b sorted.bam -f NC_000913.3.fa -o aln.html -r NC_000913:1089222-1089222

**Comment by wumuyao1996** [comment]
The bam2aln command is just

breseq bam2aln NV000913.3:

**Comment by wumuyao1996** [comment]
nvm i figured it out. bwa mem wasn't actually registering the read names as read pairs. And the -P i added did not help. It needed to be a lowercase -p

We good. Thanks for the great toolset :D
