### ISSUE TITLE
Breseq not detecting bowtie2

### ISSUE THREAD

**Issue by sv1714** [barricklab/breseq#260]
I needed to install breseq 0.35.5 in a new computer and even though I've installed and added bowtie 2.4.2 to the path, breseq seems unable to detect it and so it errors out. Any help with this would be appreciated!

**Comment by jeffreybarrick** [comment]
You've tested that you can run `bowtie2` from the command line in the same terminal window you are using to run _breseq_?  If that doesn't work, you can `echo $PATH` to check that it is being set up correctly. If it does work, does _breseq_ print out that it doesn't find `bowtie2` or that it finds an invalid version?

**Comment by sv1714** [comment]
Yes, I can run bowtie2 from the same window but when trying to run breseq it doesn't find it (so it shows no version).

**Comment by jeffreybarrick** [comment]
I'm going to need some more clues: type of system, how you installed _breseq_, where/how you installed `bowtie2`, the _breseq_ log saying it didn't find `bowtie2`, ...

**Comment by sv1714** [comment]
this is on a MacOS catalina, breseq was installed through binary download, bowtie2 was also installed in the same way. The error is: 
---> ERROR Required executable "bowtie2" or "bowtie2-build" not found.
---> See http://bowtie-bio.sourceforge.net/bowtie2

but when i run either bowtie2 or bowtie2-build in the same window it seems to not have any issues

**Comment by sv1714** [comment]
Tried removing bowtie2 and breseq and reinstalling and still running into this issue. Any help would be appreciated!

**Comment by jeffreybarrick** [comment]
Did you figure this out?

**Comment by sv1714** [comment]
Yes, I ended up having to copy the bowtie2 files manually into the bin folder and that seemed to allow breseq to find them.

**Comment by jeffreybarrick** [comment]
Ok. Thanks for letting me (and the internet) know the solution! I'm not sure why it's the case. It's possible that b/c this is a binary that something in the new MacOSX security measures is preventing it from running other problems.
