### ISSUE TITLE
How to generate a .gbk file for the Query/Mutant genome?

### ISSUE THREAD

**Issue by sbbioman74** [barricklab/breseq#261]
Hi,
I successfully used the amazing breseq to identify SNPs in multiple mutant _E. coli_ genomes. I can visualize the tabulated SNPs by opening the html files from the "output" directory. But, I want to plot the data in a circular map using tools such as BRIG which needs the .gbk files of the mutant genomes. I already have the .gbk file of the reference genome. I could not locate such file in the "output" directory. I already have the .gbk file of the reference genome. Also, can breseq generate such maps?
I am just a beginner in using command line and also in analyzing genomes. 

Any help is much appreciated. 

Souvik Bhattacharyya,
Postdoctoral fellow,
Harshey Lab,
UT, Austin
Tx

**Comment by jeffreybarrick** [comment]
Hi Souvik,

You can generate a GBK file with the predicted mutations from a _breseq_ run using the `gdtools APPLY` command and the `output.gd` file. A command like this should do the trick. The `output.gd` file is inside of the `output` directory of breseq results. You need to make sure it and `original.gbk` are copied into your current directory for the command to work.

```
gdtools APPLY -f GENBANK -o -r original.gbk output.gd
```

Note that any "unassigned evidence" will not be reflected in the mutant genome. Only full mutations (three-letter codes in the GenomeDiff file) are applied. You may need to manually curate/improve the Genome Diff file to include mutations that _breseq_ can't fully predict on its own from the evidence to get the best results.

I have't tried visualizing this using BRIG. Let us know if it works!
