### ISSUE TITLE
Installation of breseq using Linux

### ISSUE THREAD

**Issue by convincingpseudomn** [barricklab/breseq#264]
So as a fair warning I have never used Linux before and I have no experience using the command line but I have coded with Matlab before.

I am trying to install breseq, I have installed R on Windows and bowtie using Linux already. I am unable to install breseq though, this is what I get: 
![Screenshot 2021-06-11 120731](https://user-images.githubusercontent.com/85756051/121716131-aa491000-caad-11eb-901e-fafff485d3d0.png)

But I have the file loaded into my downloads
![image](https://user-images.githubusercontent.com/85756051/121716252-ce0c5600-caad-11eb-8c90-174f5e55b27f.png)

Where do I go from here?

**Comment by jeffreybarrick** [comment]
The `apt` command is your Linux package manager. It looks for packages to download and install from a special repository. There is not a _breseq_ package in the Linux repository, so this won't work.

If you downloaded _breseq_, you need to follow these instructions to install it:
https://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/installation.html

That said, I'm a bit concerned that your Windows R install and Linux bowtie2 install may not see each other if you continue down that installation path.

So, I would recommend that you install `conda`, which is a package manager that is useful for installing many bioinformatics tools. It also automatically takes care of installing `R` and `bowtie2` in ways that _breseq_ can see!

If you install `miniconda` via the instructions here:
```
https://docs.conda.io/en/latest/miniconda.html
```

Then, you should be able to use this command to install _breseq_:
```
conda install -c bioconda breseq
```

More detailed instructions can be found here:
https://bioconda.github.io/recipes/breseq/README.html

**Comment by convincingpseudomn** [comment]
Thanks, I installed miniconda and set up the channels but I am still running into some trouble
I cannot install wither bowtie2 or breseq using the command line, see below error:
![image](https://user-images.githubusercontent.com/85756051/121745007-c6f73f00-cad1-11eb-818f-0554144e63dd.png)

What should I try next?

**Comment by jeffreybarrick** [comment]
Sorry, I should have specified this: Do you have the ability to install miniconda (and then _breseq_) inside of your **Linux** environment?

**Comment by jeffreybarrick** [comment]
Any luck with this?

**Comment by convincingpseudomn** [comment]
P {margin-top:0;margin-bottom:0;} 



Hi Jeffrey,




Thank you a lot for the suggestion. I was able to get Linux running, but then I had trouble downloading miniconda. I got distracted by some other work but I will let you know this week if I am unable to complete the installation.




I really appreciate you following up with this.




Mellissa Gomez
