### ISSUE TITLE
Error while installing breseq 

### ISSUE THREAD

**Issue by akfourth** [barricklab/breseq#267]
Hi,
I'm trying to install breseq in a system-wide location on Ubuntu 18.04. 

I downloaded the source file, but when I run ./configure, it stops at a point and gives me the following error:

checking for library containing deflateSetHeader... no
configure: error: "libz >=1.2.2.1 is required."

I'm not sure what the issue is . Thanks!

**Comment by jeffreybarrick** [comment]
You need to install libz/zlib on your machine. You should be able to install it using `apt-get` on your system.

Or, if you use conda to install _breseq_ then it should install this dependency for you.

**Comment by akfourth** [comment]
I had tried that by doing 

sudo apt-get install zlib1g

It went through and said this :
zlib1g is already the newest version (1:1.2.11.dfsg-0ubuntu2).

Do I need a different version ?

Thanks!

**Comment by jeffreybarrick** [comment]
Right, you need the _development_ version that includes the headers for compiling from source code.

Try installing package `zlib1g-dev`.

**Comment by akfourth** [comment]
Thanks - that worked !
