### ISSUE TITLE
Annotated .gd Files are written incorrectly when a sample doesn't sequence

### ISSUE THREAD

**Issue by XavaarQ** [barricklab/breseq#271]
There is a writing error in the annotated .gd file when a sample doesn't sequence (aka. all genes are knocked out) that prevents the file from being read properly with the genome-diff package in python

Faulty version:
![write_error](https://user-images.githubusercontent.com/51213691/125447891-8ba80af6-d51c-4ce3-ba66-ac8017f52e4c.png)

Corrected version:
![corrected_version](https://user-images.githubusercontent.com/51213691/125447893-c95b5207-f491-4834-b0a8-1083ea18c4aa.png)

The annotated .gd and normal .gd files from this sample can be found in this archive.
[FaultySample.zip](https://github.com/barricklab/breseq/files/6808633/FaultySample.zip)

**Comment by jeffreybarrick** [comment]
Thanks for reporting this! It's fixed in the repository now and will be included in the next update.
