### ISSUE TITLE
windows (wsl) installation issue

### ISSUE THREAD

**Issue by phelannraul** [barricklab/breseq#284]
Hi! 
I am trying to install breseq on windows using WSL (Ubuntu).
I have used the Binary Download method.
After the steps,  I ran the  "./run_tests.sh" command to check the installation, it successfully showed "Test Passed".

However, once I do the test drive run, the "$ breseq -r NC_012967.gbk SRR030257_1.fastq SRR030257_2.fastq"  shows "Command 'breseq' not found. "

Kindly help me solve this issue of command breseq not found.
Thank you

PS: I have never used Linux before!

**Comment by jeffreybarrick** [comment]
Hi @phelannraul,

You need to set up your shell's `$PATH` to include the location of the `breseq` executable file. I'm sure you can find out how to do that on Ubuntu specifically by Googling around.

Here is a very comprehensive explanation of what is going on: https://astrobiomike.github.io/unix/modifying_your_path
