### ISSUE TITLE
Feature Request - add AD,DP to GD COMPARE output

### ISSUE THREAD

**Issue by kullrich** [barricklab/breseq#287]
Hi, this is just a feature request.

Would it be possible to add an two additional columns in the GD format, which would be the AD,DP field from the VCF format.

This would be great, since after running a GD COMPARE, I would need to parse again all individual VCF files to extract this information. Unfortunately I need next to the frequency (AF) also the AD and DP field to do some statistics in a time-course analysis.

Thank you in anticipation

Best regards

Kristian

**Comment by kullrich** [comment]
Of course I have to more clearly state, that in the individual GD files, the coverage is of course present (minor_cov, new_cov, ref_cov, total_cov), however, after running GD COMPARE, I can not find that information anymore in the TABLE/TSV output.

Best regards

Kristian

**Comment by kullrich** [comment]
So far, what I understand from the cpp code is, that I would need to add a new function which looks similar to `tabulate_mutation_frequencies_from_multiple_gds` to `src/c/breseq/libbreseq/genome_diff.h`, `src/c/breseq/gdtools_cmdline.cpp` and `src/c/breseq/genome_diff.cpp`. So something like `tabulate_mutation_depth_from_multiple_gds`.

Again, thank you in anticipation to help out with that feature request

Best regards
Kristian

**Comment by jeffreybarrick** [comment]
Hi @kullrich!

Yes, your strategy would work.

If I were going to add this, I would go ahead and do it inside of the existing `tabulate_mutation_depth_from_multiple_gds` function. (Perhaps there could be a parameter as to whether to add these extra fields that is passed to the function.)

First, you need to define a new key in place of `freq_key` and use that to add the new per-sample fields, putting in whatever the default value is where these lines are. (The value if that mutation is not present in the sample.)

```
      string freq_key = "frequency_" + title_list[i];
      (*this_mut)[freq_key] = "0";
```

Then, you would assign the actual value for a sample in this part of the function, from here...
```
// we found the exact same mutation
```
...to the end of the loops. This is after all of the checks are done to be sure that the mutations are identical before putting the info on the same link.

**Comment by kullrich** [comment]
Dear @jeffreybarrick,
for me the question is still where to get the AD and DP from.

E.g. in the function `cGenomeDiff::write_vcf` the AD and DP is calculated on the fly and not put into a mut[AD] or mut[DP]:
```
    double freq = 1.0;
    if (mut.entry_exists(FREQUENCY)) {
        freq = from_string<double>(mut[FREQUENCY]);
    }
    
    // Allele frequency
    string AF = formatted_double(freq, 4).to_string();
    info_entries.push_back("AF=" + AF);
    
    double new_read_count(0.0), total_read_count(0.0);
    if (read_counts_for_entry(mut, new_read_count, total_read_count)) {
      info_entries.push_back("AD=" + to_string<double>(new_read_count));
      info_entries.push_back("DP=" + to_string<double>(total_read_count));
    }
```

However, in the `cGenomeDiff::tabulate_mutation_frequencies_from_multiple_gds` function, the "frequency" is taken from the GD file. But in the GD file the "TOTAL_COV" and "MINOR_COV" is just there for the `gd_entry_type RA`. So I am a bit puzzled if I would need to directly write the AD and DP next to the "frequency" in the sample specifc GD files also for "non-RA" types to be able to touch them afterwards directly.

Using the verbose option I can see the "FREQUENCY" field for the "Master" and "Check_Mut" and of course they have no AD and DP fields nor the TOTAL_COV and MINOR_COV fields.

```
cout << ">> Master Mutation" << endl<< this_mut->as_string() << endl;
cout << ">" << title_list[i] << endl << check_mut->as_string() << endl;
```

```
>> Master Mutation
SNP	1152	.	NC_012660.1	6486284	A	frequency=2.39862442e-01
>> Master Mutation
DEL	3978	.	NC_012660.1	6486290	9	frequency=5.75263663e-02
>> Master Mutation
SNP	517	.	NC_012660.1	6486290	T	frequency=2.00346947e-01
>> Master Mutation
SNP	4716	.	NC_012660.1	6486293	C	frequency=1.00970268e-01
```
Maybe I need to use or write a function as e.g. `gd_list[i].mutation_deleted(*this_mut)` to extract AD and DP?

Thank you for your help

Best regards

Kristian

**Comment by kullrich** [comment]
Is it correct that I would need to carry forward the TOTAL_COV and MINOR_OCV from RA lines?

At the moment the function looks like this:

- bool added add_AD_DP

```
void cGenomeDiff::tabulate_mutation_frequencies_from_multiple_gds(
                                                         cGenomeDiff& master_gd, 
                                                         vector<cGenomeDiff>& gd_list, 
                                                         vector<string> &title_list,
                                                         bool phylogeny_id_aware,
                                                         bool add_AD_DP,
                                                         bool verbose
                                                         )
{  
  // Create a list of unique titles, which may require some renaming
  // so that every one has a unique key in the resulting Genome Diff entries
  set<string> used_titles; // for reassigning duplicate names
  title_list.resize(0);
  
  for (vector<cGenomeDiff>::iterator it = gd_list.begin(); it != gd_list.end(); it++) {
    
    // Assign unique names to every file and warn if names were changed.
    string this_title = it->get_title();
    uint32_t counter=0;
    while (used_titles.find(this_title) != used_titles.end() ) {
      this_title = it->get_title() + "_" + to_string(++counter);
    }
    
    if (this_title != it->get_title()) {
      WARN("Duplicate title changed from '" + it->get_title() + "' to '" + this_title + "'\nFor genome diff file with path: " + it->get_file_path());
      it->set_title(this_title);
    }
    
    title_list.push_back(this_title);
    used_titles.insert(this_title);
  }
  
  // Need to keep evidence lists that have MC and UN items around for assigning question marks
  vector<diff_entry_list_t> mut_lists;
  for (vector<cGenomeDiff>::iterator it = gd_list.begin(); it != gd_list.end(); it++) {
    mut_lists.push_back(it->mutation_list());
  }

  
  diff_entry_list_t de_list = master_gd.mutation_list();

  if (verbose) cout << "Tabulating frequencies for mutation..." << endl;
  
  for (diff_entry_list_t::iterator it = de_list.begin(); it != de_list.end(); it++) { 
    
    diff_entry_ptr_t& this_mut = *it;
    
    if (!phylogeny_id_aware) {
      this_mut->erase("phylogeny_id");
      this_mut->erase("population_id");
    }
    
    if (verbose) cout << ">> Master Mutation" << endl<< this_mut->as_string() << endl;
    
    // for each genome diff compared
    for (uint32_t i=0; i<mut_lists.size(); i++) { 
      
      string freq_key = "frequency_" + title_list[i];
      (*this_mut)[freq_key] = "0";
      
      if (add_AD_DP) {
        string AD_key = "AD_" + title_list[i];
        (*this_mut)[AD_key] = "0";
        
        string DP_key = "DP_" + title_list[i];
        (*this_mut)[DP_key] = "0";
      }
      
      diff_entry_list_t& mut_list = mut_lists[i];
      
      if (mut_list.size() == 0) 
        continue; 
    
      // for top mutation in this genomedff (they are sorted by position)
      diff_entry_ptr_t check_mut = mut_list.front();
      
      if (verbose)
        cout << ">" << title_list[i] << endl << check_mut->as_string() << endl;
      
      // Prevent keeping things separate based on phylogeny id
      if (!phylogeny_id_aware) {
        check_mut->erase("phylogeny_id");
        check_mut->erase("population_id");
      }
      
      // we found the exact same mutation
      if ( (check_mut.get() != NULL) && (*check_mut == *this_mut) ) {
        
        if (check_mut->count(FREQUENCY)) {
          (*this_mut)[freq_key] = (*check_mut)[FREQUENCY];
          if (add_AD_DP) {
            (*this_mut)[AD_key] = (*check_mut)[MINOR_COV];
            (*this_mut)[DP_key] = (*check_mut)[TOTAL_COV];
          }
        } else {
          (*this_mut)[freq_key] = "1";
        }
        
        // remove the item
        mut_list.pop_front();
        continue;
      }
      
      // we didn't find the mutation, so we might need to consider it deleted or unknown...
      if (gd_list[i].mutation_deleted(*this_mut)) {
        (*this_mut)[freq_key] = "D";
        continue;
      }
      
      if (gd_list[i].mutation_unknown_or_missing_coverage(*this_mut)) {
        (*this_mut)[freq_key] = "?";
        continue;
      }
    }
  }

}
```

**Comment by jeffreybarrick** [comment]
Oh, yes... that's right. You will need to find the corresponding `RA` entry (or entries) to retrieve the coverage information.

You can access the list of evidence supporting a mutation by using this function 
```
diff_entry_list_t cGenomeDiff::in_evidence_list(const cDiffEntry& item) const;
```

So, in the context here, I think you'd get the list like this.
```
diff_entry_list_t this_mut_evidence_list =  this->in_evidence_list(this_mut);
```

For a single base change there will be just one `RA` list item. For a multibase substitution or deletion there will be one for each base if it is small. You could iterate through those, but it's probably best to just look at the first one (b/c the AD/DP depths will be very similar for all of them).

```
if (this_mut_evidence_list.size() > 0) && (this_mut_evidence_list[0]._type == RA) {
   cDiffEntry ra = *(this_mut_evidence_list[0]);
   // Add part where you look at ra[TOTAL_COV] and ra[NEW_COV] to infer the AD/DP
   // You'll need to split them from the "forward/reverse" string format and add. Sorry it's so complicated!
}
```
