### ISSUE TITLE
Fatal error during analysis

### ISSUE THREAD

**Issue by khoriba** [barricklab/breseq#288]
Hi,
I had fatal error during phase of "Creating read alignment for region ...". The command used is as follows. The error output is also described.

$ breseq -r REF.fna -r REF.gff3 INPUT.fastq

....

Warning message:
1: png (out_file, height = 6, width = 11, units = "in", res = 72, at:
    Unable to load shared library'/home/miniconda3/envs/base/lib/R/library/grDevices/libs//cairo.so':
   libjpeg.so.8: Unable to open shared object file: no such file or directory
2: png (out_file, height = 6, width = 11, units = "in", res = 72, at:
   failed to load cairo DLL
Creating coverage plot for region: REF: 4618082-4618243

...

Creating read alignment for region: REF:647671-647671
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Segmentation Fault
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Backtrace with 13 stack frames.
breseq() [0x41cb54]
breseq() [0x438ae7]
/lib64/libc.so.6(+0x36450) [0x7faefdc4b450]
breseq() [0x54838f]
breseq() [0x54b7ee]
breseq() [0x55cab8]
breseq() [0x55d134]
breseq() [0x55e65e]
breseq() [0x563410]
breseq() [0x430444]
breseq() [0x40ae05]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x7faefdc37555]
breseq() [0x41c7d1]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jeffreybarrick** [comment]
Bioconda sometimes installs or gets stuck with a version of R that does not have graphics support. I think that's your problem. Try the approach in #269 to update or get it to install a different R.

@danieldeatherage: I think you encountered this recently and also have a solution?

**Comment by jeffreybarrick** [comment]
@khoriba Any luck or need some more guidance to resolve this?

**Comment by khoriba** [comment]
Sorry for the late reply. I'm currently wrestling with this issue, but I haven't been able to resolve it. Is it a problem that I am a user rather than an administrator?

**Comment by jeffreybarrick** [comment]
It might be. 

I would try creating a fresh/clean conda environment and installing there. You should be able to do this as a user without any problems.

The commands would be something like this to create an environment named breseq-env
```
conda create -n breseq-env
conda activate breseq-env
conda install breseq
```

Further information on using environments (which are useful for preventing conflicts from installing different things together) can be found here: https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

**Comment by khoriba** [comment]
Thank you, 
I made a new environment for breseq. Then I think I got the full html reports.
After `conda install breseq`, I needed an update for bowtie2. 
In addition, the following warning was output in the run.

```
Warning message:
1: png (out_file, height = 6, width = 11, units = "in", res = 200, at:
    Unable to load shared library'/home/miniconda3/envs/breseq-env/lib/R/library/grDevices/libs//cairo.so':
   libjpeg.so.8: Unable to open shared object file: no such file or directory
2: png (out_file, height = 6, width = 11, units = "in", res = 200, at:
   failed to load cairo DLL
Creating coverage plot for region: NC_000913.3: 15481-16739
```

However, the output report was very good.

**Comment by jeffreybarrick** [comment]
Ok... It seems there is still something up with your R install not having graphics support, so maybe it may not make the coverage graphs that are normally linked from the summary.html page or DEL evidence items properly.

I'm going to leave this issue open until I have a chance to look at the bioconda recipe to see if there is something I can change there to make sure it installs a correct R and bowtie2.

**Comment by khoriba** [comment]
The coverage graph is attached for reference. I can see also the error rates graph. The link was working.
![0 unique_coverage](https://user-images.githubusercontent.com/45022668/135107981-05ccbbd0-31eb-4f83-a2d0-e27ada5f6e65.jpg)

**Comment by jeffreybarrick** [comment]
OK. Great!
