### ISSUE TITLE
I can't Run Breseq (I got a problem with R)

### ISSUE THREAD

**Issue by BatistaB** [barricklab/breseq#290]
Hello,

I'm a new user of Linux and I want to learn how to use breseq in my intern project. So, I install a WSL in my windows machine and after it I have installed Bioconda, Bowtie2 and R. I download Breseq from Bioconda.

Ok, I have been try to do the Tutorial (test drive) from website, but when I try to run ...

![image](https://user-images.githubusercontent.com/91222473/134413140-b0349f51-2d60-451b-9326-25b724fdcd50.png)

I don't know how can I solve this. I'm a very newbie in Linux. So can someone help me please? 

Thanks a lot.

**Comment by BatistaB** [comment]
I try to run in google colab, and It worked out \o

**Comment by jeffreybarrick** [comment]
So, you got it to run?

The first error indicates that there was a problem installing R via conda. You could Google around about ways to force it to (re)install a newer/different version of R and try that. It looks like you may have installed the Windows version of R and are trying to run it in the Linux environment, so it is the wrong kind of executable.

**Comment by BatistaB** [comment]
I
