### ISSUE TITLE
std::bad_alloc

### ISSUE THREAD

**Issue by khoriba** [barricklab/breseq#292]
Hi,
My analysis on breseq  (0.36.0)  was stopped in the step of making html report by the following error.
```
...
Creating evidence file: SNP_5778.html
Creating read alignment for region: NZ_KB944666.1:843349.0-843349.0
Creating evidence file: SNP_5779.html
Creating read alignment for region: NZ_KB944666.1:843352.0-843352.0
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
Can this problem be solved?
Is there a way to rescue this failed process?

**Comment by jeffreybarrick** [comment]
Can you share the read and reference files and the command you used to run _breseq_ with me? 

Email me at the address in the _breseq_ header and I can share a folder for you to upload the large files. Without the input files, I won't be able to diagnose what is going on. It seems there must be a bug around some edge case in creating the HTML alignments.

The machine-readable output files (ex: `output/output.gd`) for this run should still be complete/fine at the point in the pipeline where it died.

**Comment by khoriba** [comment]
Thank you for your reply. I can share my fastq and ref data.
Unfortunately, I can not found your email address for breseq. where is it ?
I'm sorry....

**Comment by jeffreybarrick** [comment]
When you run _breseq_ at the command line it is in the header.

**Comment by khoriba** [comment]
I found it. I sent an email to you. Thank you!

**Comment by jeffreybarrick** [comment]
Issue could not be reproduced. Closing for now.
