### ISSUE TITLE
ERROR Could not determine version of installed executable "R".

### ISSUE THREAD

**Issue by ppat818** [barricklab/breseq#299]
Hi

I installed breseq on a new Windows computer (using Ubuntu LTS) through Bioconda. This is the error I keep getting:

```
---> bowtie2  :: version 2.2.5 [/mnt/c/Users/User/anaconda3/bin/bowtie2]
---> ERROR Could not determine version of installed executable "R".
---> For found executable installed at [/mnt/c/Users/User/anaconda3/bin/R]
---> Command "R --version" returned:
/mnt/c/Users/User/anaconda3/lib/R/bin/exec/R: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
```

I have tried uninstalling and reinstalling and updating but I still keep getting the same error. Any suggestions?

**Comment by jeffreybarrick** [comment]
Unfortunately, the R that is automatically installed by Bioconda is sometimes broken on some systems.

Running this command has worked for others:
```
conda update r-base
```

See #269, #284, and #290 for some other ideas for how to get conda to fix its R install.

This is also a possible fix:
https://github.com/bioconda/bioconda-recipes/issues/13439

**Comment by ppat818** [comment]
I tried those fixes and they didn't work. I then installed Linux on VM thinking I may have more luck this way (breseq has worked fine for me on a linux VM before) but I had the same error message thrown back. I did some googling about the libreadline.so.6 error and tried linking existing files (https://askubuntu.com/questions/1168787/libreadline-so-6-issue-in-ubuntu-18-04) but that now gives me an error for something called libncurses.so.5

`---> bowtie2  :: version 2.2.5 [/mnt/c/Users/User/anaconda3/bin/bowtie2]
---> ERROR Could not determine version of installed executable "R".
---> For found executable installed at [/mnt/c/Users/User/anaconda3/bin/R]
---> Command "R --version" returned:
/mnt/c/Users/User/anaconda3/lib/R/bin/exec/R: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory`

Do you have any other suggestions?

**Comment by jeffreybarrick** [comment]
I'd suggest these steps:

0) Try running `conda update --all `. This sometimes can fix problems, esp. if you have been doing things with different platforms.

Assuming that doesn't work:

1) Deactivate any conda environments

2) Install R outside of conda via one of the downloads at https://www.r-project.org/

3) Make sure this version of R will supersede any conda installs of R when you run R from the shell by locating it:
```
which R
```

4) Create and activate a clean conda environment and install breseq as usual.

5) Verify that the R executable that you manually installed will still be called from the shell with this activated. (i.e., its location appears earlier in your `$PATH`.
```
which R
```

6) If the second location is different, give the location where you installed R higher preference by editing your shell init files to place it earlier in the `$PATH`.

** If this doesn't work, then I would try installing R, bowtie2, and _breseq_ all manually and putting them in your $PATH by following the directions in the manual.

**Comment by GuillaumePherecydes** [comment]
Hi,
As @jeffreybarrick said works for me (Ubuntu WSL and conda) with these steps.

1. Deactivate any conda environments
2. Uninstall breseq environnement and packages
3. Install R outside conda by following these instructions [https://cran.r-project.org/bin/linux/ubuntu/]
4. Check if the version of R in the latest with `which R` (4.1.3 for me)
5. Create and activate a clean conda environment for breseq
6. Install breseq in this environnement with `conda install breseq r-base=4.1.3`
7. Check if conda proposes to download the good version of r-base `r-base             conda-forge/linux-64::r-base-4.1.3-h06d3f91_1`
8. if OK, `Proceed ([y]/n)? y`
9. Enjoy breseq

`breseq 0.36.1
---> bowtie2  :: version 2.4.5 [/home/.../anaconda3/envs/breseq/bin/bowtie2]
---> R        :: version 4.1.3 [/home/.../anaconda3/envs/breseq/bin/R]`

**Comment by ppat818** [comment]
Thank you @jeffreybarrick and @JustdukeP, 

Installing R separately as you suggested eventually worked. 

I ended up having to remove Miniconda and WSL from my machine entirely, reinstalling and then installing R separately as suggested. And then installing breseq using conda as normal.

**Comment by jeffreybarrick** [comment]
Great! Thanks for letting us know.
