### ISSUE TITLE
Breseq suitable for Basidiomycetes

### ISSUE THREAD

**Issue by termithorbor** [barricklab/breseq#300]
Hi,

is the Breseq pipeline also suitable for the detection of mutations in Basidiomycetes which have a genome size of ~ 46 MB?

Thanks in advance.

**Comment by jeffreybarrick** [comment]
If it's haploid (one of the assumptions of _breseq_), then it could be worth a try, though you may have to be patient in giving it a long time to finish.

One complication you may encounter is that if the reference genome has a lot of repetitive regions, this can sometimes cause many false-positive or irrelevant junction predictions. (For example, telomeres cause messy output when analyzing _S. cerevisiae_). You might try running it the first time, at least, with `--no-junction-prediction` to see if it is doing an OK job on point mutations.
