### ISSUE TITLE
Directly process .tab to final .html output?

### ISSUE THREAD

**Issue by wichne** [barricklab/breseq#302]
Hi,
I am running breseq on an algal genome that is quite large. Some of the contigs have been processed through the 08_mutant_identification step. Since the process is still running, is there a way to just run one or more of the .tab files through to final output without having to wait for the rest of the contigs to finish processing?

thanks,
Bill

**Comment by jeffreybarrick** [comment]
Hi Bill, 

I'm not able to think of a way to let one contig jump ahead to the output step.

If you want to get a preliminary idea of what the output might look like with a quicker run, you might try limiting the number of input reads that are used with this option:

```
  -l,--limit-fold-coverage <arg>   Analyze a subset of the input FASTQ
                                   sequencing reads with enough bases to provide
                                   this theoretical coverage of the reference
                                   sequences. A value between 60 and 120 will
                                   usually speed up the analysis with no loss in
                                   sensitivity for clonal samples. The actual
                                   coverage achieved will be somewhat less
                                   because not all reads will map (DEFAULT=OFF)
```
