### ISSUE TITLE
How to merge multiple mutations in the same position in a time series?

### ISSUE THREAD

**Issue by loukesio** [barricklab/breseq#303]
Dear all, 

I am running at the moment breseq at the time-series genomics data that comes from the following paper https://www.pnas.org/doi/abs/10.1073/pnas.1708371115. This is whole-genome population data.

There are multiple positions, like the figure, where various mutations in the same position have been identified. 
In the figure, you see a snapshot of the HTML output file.

In my understanding and forgive me if I am wrong, at time point 4 in Sample129 (aka Sample129_0_4_p), 89.4 % of the 
population carries a CG mutation. Am I right?
If this is true, is there a script to make my time series look like 89.4% carries a CG mutation?

<img width="885" alt="Screenshot 2022-03-14 at 17 10 05" src="https://user-images.githubusercontent.com/13181494/158214220-b72f8629-c0db-4b86-900d-b03fa46d0235.png">

Thank you for your time and please excuse for my naive question

**Comment by jeffreybarrick** [comment]
Closing old issue. Re-open if still active.
