### ISSUE TITLE
terminate called after throwing an instance of 'std::invalid_argument'

### ISSUE THREAD

**Issue by 898289687** [barricklab/breseq#307]
Hi, 
I encountered an issue when I was using Breseq to analyze genome sequencing data. 
I tried to use the old version of Bowtie2 to do analysis based on the answers from previous posts. But it doesn't work. 
Here is my errors I got,
---> bowtie2  :: version 2.4.1 [/software/software/Bowtie2/2.4.1-GCC-9.3.0/bin/bowtie2]
---> R        :: version 4.0.0 [/software/software/R/4.0.0-foss-2020a/bin/R]
--- ALREADY COMPLETE Read and reference sequence file input
--- ALREADY COMPLETE Read alignment to reference genome
--- ALREADY COMPLETE Preprocessing alignments for candidate junction identification
--- ALREADY COMPLETE Preliminary analysis of coverage distribution
--- ALREADY COMPLETE Identifying junction candidates
--- ALREADY COMPLETE Re-alignment to junction candidates
--- ALREADY COMPLETE Resolving best read alignments
terminate called after throwing an instance of 'std::invalid_argument'
  what():  parse error - unexpected end of input
/var/spool/slurmd/job23988239/slurm_script: line 14: 22036 Aborted 

I can't get the summary html and other result data.
my code is 
time breseq -j 1 -r chr1.gbk -r chr2.gbk -r chr3.gbk -r chr4.gbk -r chr5.gbk -r chr6.gbk -r chr7.gbk -r chr8.gbk -r chr9.gbk -r chr10.gbk -r chr11.gbk -r chr12.gbk -r chr13.gbk -r chr14.gbk -r chr15.gbk -r chr16.gbk dMal-g-DNA_1.fq.gz dMal-g-DNA_2.fq.gz -o /home/p285977/dmal_genome/dmal_Ref113chr

breseq version : breseq/0.35.4-foss-2020a-R-4.0.0
Bowtie2 version I tried:  
        Bowtie2/2.2.8-foss-2018a
        Bowtie2/2.3.4.3-foss-2018a
        Bowtie2/2.4.1-GCC-9.3.0
        Bowtie2/2.4.4-GCC-9.3.0
Does anyone help me with this issue? Thanks in advance.

**Comment by jeffreybarrick** [comment]
Please see if the issue occurs with the current version of _breseq_ v0.36.1.
https://github.com/barricklab/breseq/releases
Be sure to start the run with the new version in a clean output folder.

**Comment by 898289687** [comment]
Thanks for your quick reply. I will try the updated version.

**Comment by 898289687** [comment]
After I used updated version of breseq,  I still got the same error, as following:
"terminate called after throwing an instance of 'std::invalid_argument'
  what():  parse error - unexpected end of input
/var/spool/slurmd/job24175430/slurm_script: line 14:  2694 Aborted "

----> breseq :: verion breseq/0.36.1-foss-2021b
---> bowtie2  :: version 2.4.4 [/software/software/Bowtie2/2.4.4-GCC-11.2.0/bin/bowtie2]
---> R        :: version 4.1.2 [/software/software/R/4.1.2-foss-2021b/bin/R]

Could you know why?

> Please see if the issue occurs with the current version of _breseq_ v0.36.1. https://github.com/barricklab/breseq/releases Be sure to start the run with the new version in a clean output folder.

**Comment by 898289687** [comment]
Yes, sure. That would be really nice.

Best regards
Xiaohuan Zhang

发件人: Jeffrey ***@***.***>
发送时间: Thursday, May 19, 2022 3:26 PM
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [barricklab/breseq] terminate called after throwing an instance of 'std::invalid_argument' (Issue #307)


Are you able to share this dataset with me to see if I can reproduce the error? If so, please contact me at the email address in the breseq header. I can provide you with access to a shared folder for uploading large FASTQ and reference files, if that is helpful.

―

**Comment by jeffreybarrick** [comment]
You'll need to send me an email outside of the GitHub reply system so I have your address.

**Comment by 898289687** [comment]
I sent it, please have a look

**Comment by 898289687** [comment]
Hi Jeff
I uploaded my data in another directory with larger storage. I got the results. No any error popped up.
Thanks  a loooot!

Best
Xiaohuan

**Comment by jeffreybarrick** [comment]
Great!
