### ISSUE TITLE
How to make a TSV format for compare.

### ISSUE THREAD

**Issue by khoriba** [barricklab/breseq#308]
Hi,

I have twenty genome diff files for comparison.  My aim is to make a TSV table that contains SNPs with an amino acid change in a coding regions. 
To code` $ gbtools COMPARE -f HTML ` make a table close to what I wanted, but this is HTML format.
To code ` $ gbtools COMPARE -f TSV `  make a table, but it is not like HTML version.
Do you have any good advise?

Best regards

**Comment by jeffreybarrick** [comment]
If you want the formatted output like that in the HTML, the easiest thing is probably to open that in a web browser and copy the table into MS Word or MS Excel. It should paste as a formatted table.

The same information (and more) is in the TSV/CSV output, but you would need to use CONCATENATE or something like that in Excel (or other spreadsheet program) to put together the `aa_ref_seq` and `aa_new_seq` fields with an arrow between them.
