### ISSUE TITLE
Meaning of arrows at the output file

### ISSUE THREAD

**Issue by galtoledano** [barricklab/breseq#311]
I'm using breseq in clonal mode.
An arrow appears in the gene section of the output file.
What is the meaning of these arrows, and how should they be interpreted in a case of intergenic mutation?
Thank you in advance

**Comment by jeffreybarrick** [comment]
The arrows give the direction (strandedness) of the gene on the genome. 

So for this intergenic mutation:
``` 
bor ← / ← lambdap78
```
The mutation (occurring where the / is between genes) is upstream of the bor gene and downstream of the lambdap78 gene.
