### ISSUE TITLE
breseq randomly hangs

### ISSUE THREAD

**Issue by vr1087** [barricklab/breseq#313]
Hi Jeff. I run breseq on thousands of samples. On occasion, the breseq command will randomly hang. It doesn't happen for the same datasets and the parameters are constant. Relaunching the command fixes the hanging issue. It's hard to tell if the root cause is specific to our runtime environment or to breseq's source code. I've taken a peek inside a docker container of a hanged breseq command and I observed breseq had been using one thread with a completely empty output folder. Honestly, I can't imagine this is possible for you to debug. So, this issue is mostly for reference, but do you have any insight on this? I've seen this happen with breseq-0.35.1 and the latest 0.37.0.  

Edit: I see the hanging issue also occurs with the gdtoolds command, too. I was using the APPLY subcommand.

**Comment by jeffreybarrick** [comment]
Hi Vini, 

Yeah... I'm not sure about this. My guess is that it is something to do with your runtime environment, but if you notice any patterns that could be debugged, let me know.
