### ISSUE TITLE
Update version at bioconda to 0.37

### ISSUE THREAD

**Issue by wwarriner** [barricklab/breseq#316]
It looks like bioconda may be behind the latest release of breseq, i.e. 0.36.1 rather than 0.37.0. Could we get that updated?

Hope I'm putting this in the correct place. Let me know if this should be posted on the bioconda github issue tracker instead.

Thank you!

**Comment by jeffreybarrick** [comment]
Thanks for reporting this! It looks like we broke the conda autoupdate by misnaming a download in v0.36.1. I've posted a pull request there that should make v0.37.0 (and future versions) available once they process it.

https://github.com/bioconda/bioconda-recipes/pull/36276
