### ISSUE TITLE
Variant prediction in regions with overlapping unique and repeat coverage

### ISSUE THREAD

**Issue by vr1087** [barricklab/breseq#318]
How does breseq handle variant calling in regions that has both repeat and unique read coverage? Does breseq exclude all regions that have repeat coverage, even if there is overlapping unique coverage as well? An example of that is shown in the coverage plot below [1500, 2500].

![image](https://user-images.githubusercontent.com/7674836/185757664-aeb9529b-c536-401e-bdb4-d4fb0d36aac3.png)

**Comment by jeffreybarrick** [comment]
It will call variants from the uniquely mapped reads (and ignore the repeat-mapped reads) in these regions.

**Comment by vr1087** [comment]
Excellent, thanks for the response.
