### ISSUE TITLE
annotation error

### ISSUE THREAD

**Issue by he-hai** [barricklab/breseq#321]
Hi, I just found breseq gave me a wrong annotation in a mutation: it annotated TTA -> CTG to be L to M change. But it should still be L. Is this an error? Wondering why this happens. 

I used v 0.31.0  revision 69e7c3c0fa11, please see the screenshot. Thank you. 
![image](https://user-images.githubusercontent.com/52635520/188426518-412bd582-d637-4e2b-93bb-024e423e2f4f.png)

**Comment by jeffreybarrick** [comment]
I'm almost 100% certain that this was fixed a long time ago. Please update to the current _breseq_ version and see if the error persists. New versions put a dagger by the codon changes for cases where two mutations affect the same codon.
