### ISSUE TITLE
FATAL ERROR 

### ISSUE THREAD

**Issue by airbender97** [barricklab/breseq#324]
Hello,

I have a problem while doing a test drive. 

"Could not open reference file"

![Ekran Alıntısı](https://user-images.githubusercontent.com/113200358/190188816-de1c0adf-82b6-4c09-be05-39ca0d6c3f98.PNG)

**Comment by jeffreybarrick** [comment]
This error indicates that the file `NC_012967.gbk` is not found at the path you gave for it with the `-r` option. Check that it has the correct name and is present in your current directory using `'ls`.
