### ISSUE TITLE
Conda downloads older version 

### ISSUE THREAD

**Issue by antanij** [barricklab/breseq#326]
I am experiencing a Fatal error "Covariate 'quality' exceeded enforced maximum". I see that [it has been fixed in the latest version v0.37.1](https://github.com/barricklab/breseq/releases/tag/v0.37.1), released 8 days ago.  

I created a new environment and performed `conda install breseq`. However, it seems that an older version has been downloaded as I get the same Fatal error.

Is there a specific way to download the latest version or do we just have to wait until it is integrated in bioconda? How long does it typically take?

**Comment by jeffreybarrick** [comment]
I'm not sure what the frequency is for the automatic updates, but I manually posted a pull request to do this...

You can monitor it here: https://github.com/bioconda/bioconda-recipes/pull/37219

**Comment by jeffreybarrick** [comment]
It's available now

**Comment by antanij** [comment]
Thank you!
