### ISSUE TITLE
FASTQ sequence record does not begin with @NAME line

### ISSUE THREAD

**Issue by Barrington-wustl** [barricklab/breseq#327]
im stumped and cant find anyone else that is having this issue can anyone figure out why im getting the error 

FASTQ sequence record does not begin with @NAME line

here is the line of code 

(breseq) marshall@DESKTOP-JF4E1DQ:~$ breseq -r PAO1/PAO1.gbk Illumina_DNA_Reads_Trimmed/s46/prokka_output_s46/PROKKA_08162022.gbk Illumina_DNA_Reads_Trimmed/s46/unicycler_output_s46/spades_assembly/read_correction/corrected/AMT0207_8_S46
_R1_001.fastq.00.0_0.cor.fastq.gz Illumina_DNA_Reads_Trimmed/s46/unicycler_output_s46/spades_assembly/read_correction/corrected/AMT0207_8_S46_R2_001.fastq.00.0_0.cor.fastq.gz -j 16 -o Illumina_DNA_Reads_Trimmed/s46/breseq_PAO1_output_s46
 -n PAO1_v_S46 --consensus-minimum-total-coverage-each-strand
================================================================================
breseq 0.37.0     http://barricklab.org/breseq

Active Developers: Barrick JE, Deatherage DE
Contact:           <jeffrey.e.barrick@gmail.com>

breseq is free software; you can redistribute it and/or modify it under the
terms the GNU General Public License as published by the Free Software
Foundation; either version 2, or (at your option) any later version.

Copyright (c) 2008-2010 Michigan State University
Copyright (c) 2011-2022 The University of Texas at Austin

If you use breseq in your research, please cite:

  Deatherage, D.E., Barrick, J.E. (2014) Identification of mutations
  in laboratory-evolved microbes from next-generation sequencing
  data using breseq. Methods Mol. Biol. 1151: 165–188.

If you use structural variation (junction) predictions, please cite:

  Barrick, J.E., Colburn, G., Deatherage D.E., Traverse, C.C.,
  Strand, M.D., Borges, J.J., Knoester, D.B., Reba, A., Meyer, A.G.
  (2014) Identifying structural variation in haploid microbial genomes
  from short-read resequencing data using breseq. BMC Genomics 15:1039.
================================================================================
---> bowtie2  :: version 2.2.5 [/home/marshall/anaconda3/envs/breseq/bin/bowtie2]
---> bowtie2  :: NOTE :: breseq output may vary slightly depending on your bowtie2 version
---> bowtie2  :: NOTE :: and occasionally bowtie2 versions may have bugs that cause crashes.
---> bowtie2  :: NOTE :: bowtie2 version 2.4.5 is recommended with this breseq version.
---> R        :: version 4.2.1 [/home/marshall/anaconda3/envs/breseq/bin/R]
+++   NOW PROCESSING Read and reference sequence file input
  READ FILE::PROKKA_08162022.gbk
    Converting/filtering FASTQ file...
FASTQ sequence record does not begin with @NAME line.
File Illumina_DNA_Reads_Trimmed/s46/prokka_output_s46/PROKKA_08162022.gbk
Line: 1

**Comment by jeffreybarrick** [comment]
You need an `-r` before each reference file. _breseq_ is interpreting `Illumina_DNA_Reads_Trimmed/s46/prokka_output_s46/PROKKA_08162022.gbk ` as an input FASTQ read file since it doesn't have this before it.

You also need a number after this argument `--consensus-minimum-total-coverage-each-strand`, so it likely would give you another error after this one (unless that's just a pasting typo).

Try this command line:
```
breseq -r PAO1/PAO1.gbk -r Illumina_DNA_Reads_Trimmed/s46/prokka_output_s46/PROKKA_08162022.gbk Illumina_DNA_Reads_Trimmed/s46/unicycler_output_s46/spades_assembly/read_correction/corrected/AMT0207_8_S46
_R1_001.fastq.00.0_0.cor.fastq.gz Illumina_DNA_Reads_Trimmed/s46/unicycler_output_s46/spades_assembly/read_correction/corrected/AMT0207_8_S46_R2_001.fastq.00.0_0.cor.fastq.gz -j 16 -o Illumina_DNA_Reads_Trimmed/s46/breseq_PAO1_output_s46
-n PAO1_v_S46 --consensus-minimum-total-coverage-each-strand 10
```

In general, it's best to put the unnamed arguments (the FASTQ's) at the end of the line after the named arguments:
```
breseq -r PAO1/PAO1.gbk -r Illumina_DNA_Reads_Trimmed/s46/prokka_output_s46/PROKKA_08162022.gbk  -j 16 -o Illumina_DNA_Reads_Trimmed/s46/breseq_PAO1_output_s46
-n PAO1_v_S46 --consensus-minimum-total-coverage-each-strand 10 Illumina_DNA_Reads_Trimmed/s46/unicycler_output_s46/spades_assembly/read_correction/corrected/AMT0207_8_S46
_R1_001.fastq.00.0_0.cor.fastq.gz Illumina_DNA_Reads_Trimmed/s46/unicycler_output_s46/spades_assembly/read_correction/corrected/AMT0207_8_S46_R2_001.fastq.00.0_0.cor.fastq.gz
```

**Comment by Barrington-wustl** [comment]
thank you for the quick response and tips on where to put the unnamed arguments 

few clarifications 

Illumina_DNA_Reads_Trimmed/s46/prokka_output_s46/PROKKA_08162022.gbk shouldn't be the reference. -r PAO1/PAO1.gbk is the reference .  PROKKA_08162022.gbk is a long read that's been annotated by prokka.  AMT0207_8_S46_R1_001.fastq.00.0_0.cor.fastq.gz and AMT0207_8_S46_R2_001.fastq.00.0_0.cor.fastq.gz are short reads from the same sample as the long read.

**Comment by jeffreybarrick** [comment]
WARNING: _breseq_ is not suitable for analyzing long-read sequencing data, so don't use that input! It breaks assumptions about how it aligns reads to the reference genome.

The next release of _breseq_ will probably let you process long reads (we have a working prototype that we are testing), but it will be by virtually chopping them into digestible short reads, so you won't get the advantages of detecting large-scale structural variation. For that, you should probably _de novo_ assemble the long reads and then use a program for whole genome comparisons to compare the resulting contigs to the reference genome.

**Comment by Barrington-wustl** [comment]
okay thank you so much
