### ISSUE TITLE
Feature request: access empirical error distribution command as standalone

### ISSUE THREAD

**Issue by osilander** [barricklab/breseq#330]
Hi,
I'm wondering that the input file(s) are for calculating and plotting the empirical error distribution? I'm very interested in being able to access that part of the pipeline as a standalone command. Is that possible already?

**Comment by jeffreybarrick** [comment]
Hi @osilander,

Not really, unfortunately. There is a hidden `breseq ERROR_COUNT` subroutine that was around for testing, but it hasn't been used in some time and it seems to be broken when I tried using it now (unexplained seg faults). I don't have time to investigate more right now.

Maybe you could pass your data as an aligned SAM file to the main pipeline (1--aligned-sam1), which skips the alignment steps, turn off output production `--brief-html-output`, and then grab the intermediate files?

The data that is graphed is kept in these files:
``` 
07_error_calibration/error_rates.tab
07_error_calibration/error_counts.tab
```

I think these files are not deleted at the end of a run by default, but you can add the `--keep-intermediates` flag if it isn't there, and then they definitely won't be deleted.

**Comment by osilander** [comment]
Thanks. Tried this for short read bacterial data set and it worked great. Trying an ONT dataset on a draft genome and keep getting differences in the nucleotide and CIGAR lines even after picard_clean. I'll keep working on it.

**Comment by jeffreybarrick** [comment]
One limitation of _breseq_'s error analysis algorithm to keep in mind if you are trying to look at indel error rates in Nanopore data: _breseq_ will only count instances of **single-base** deletions or insertions. If there are two or more bases in the indel, it won't be counted.
