### ISSUE TITLE
NA frequency for a JC-based variant. What does it mean?

### ISSUE THREAD

**Issue by vr1087** [barricklab/breseq#337]
While casting mutation frequency strings to a floats, our variant database transformer broke when it encountered an 'NA' string. This was for a large_subsitution mutation based on JC evidence only. I see in the source code that JC can have an NA annotation for the frequency. I have two questions:

- Is the NA string in the output intentional or a bug?
- How should we interpret an NA frequency? 

https://github.com/barricklab/breseq/blob/b3d4eda7d7caa10ebd56fbe65eabdc928898d922/src/c/breseq/output.cpp#L342-L346

using: `breseq  version 0.37.0  revision 25ce8c36ad2f`

**Comment by jeffreybarrick** [comment]
It's intentional: the `NA` frequency occurs when both sides of the new junction map to repeat/redundant regions in the reference genome. Because we can't trust the read counts for those to be accurate this makes the denominator in the frequency calculation zero. Is this the case for your junction?

**Comment by vr1087** [comment]
I'll have to generate the full html output to find out. Thanks, for the quick response!
