### ISSUE TITLE
no output.html file

### ISSUE THREAD

**Issue by SoGUILL** [barricklab/breseq#339]
Hello,
 I have installed Breseq on my mac to do polymorphism analysis. Everything seems to work fine. But I don't have the output.html file. I only have the independent files for each observed modification. How can I get this output.html file ?
 Thank you for your help!

**Comment by jeffreybarrick** [comment]
If you have no `output.html` then there was an error near the end of the run. Check the output to the terminal or a log file if you are running it on a cluster. Most likely there is something missing with your install of R that prevents it from being able to generate plots. It's also possible your computer ran out of hard drive space in the middle of the run. Let us know that the error is and also details about how you installed _breseq_ and R.

**Comment by SoGUILL** [comment]
Thank you for your feedback. There is no mention of an execution error. The log file is empty (there is just the execution command). I have all the html files independently. I just need to compile these files into an output.html file. I installed Breseq via Conda : "conda install breseq".  I have a Mac book Pro macOS Monterey version 12.5. The version of R is R4.2.2 GUI 1.79 Big on ARM build (R-4.2.2-arm64.pkg). Thank for your help

**Comment by jeffreybarrick** [comment]
There should be some output to the terminal when you run _breseq_. That would have been where the error showed up. Can you check for that, or run the same command in the same directory and share the terminal output?

**Comment by SoGUILL** [comment]
Hello, I have a message that appears at the end of the execution at each of my attempts that I had not seen. 
zsh: killed     breseq -r GCF_000756125.1_ASM75612v1_genomic.gbk BP125_S36_R1_001.fastq  -p
So the program stops before the end. In the output folder, I have log.txt, output.gd, output.vcf and summary.json files + calibration and evidence folders. I also get this message when I test your  dataset (SRR030257). Is there a memory problem? I have a fairly powerful Mac with 32GB of memory / 1TB of flash storage (700GB available). Thanks a lot

**Comment by evolvomics** [comment]
That's odd. It is an error that usually occurs when resources are running out, but that shouldn't be the case. I see some reports that this kind of thing can happen after MacOS updates on M1 macs, and that the solution is to re-install conda. Maybe that will work?

https://github.com/tensorflow/tensorboard/issues/5658

**Comment by fraseraj** [comment]
Hi, I have exactly the same issue as soGUILL and also installed using Conda, though using Linux. Memory shouldn't be an issue as I'm connected to a cluster. I've also removed and reinstalled the newest version of Conda, this didn't help. Thanks for your help .

**Comment by jeffreybarrick** [comment]
It is also being killed by the system? Is it also at the output step specifically?

Here are a few things I can think to check:

1) Is there a different (old) version of _breseq_ installed in your `$PATH` that is being called instead of the one installed through Conda? Use `which breseq`.

2) Does the architecture of the _breseq_ executable match your system? Use `arch` and `file <path to breseq executable>`, for example.

3) Are you running in a cluster environment (like a head node) that limits resources/time given to jobs, and it might be killing your process?

**Comment by fraseraj** [comment]
Hi, thanks for your help. I've reviewed all the suggestions you provided and don't think any of them are causing the issue.

I’ve managed to get Breseq running for some of my isolates, but for others, the run doesn’t complete. I’m left with no output summary, and like the previous user, the log only shows the command that was executed.

I’ve tried installing Breseq via Conda, Docker, and binary download, but the issue persists. The input fastq files for the failing runs don't seem to have any obvious differences compared to the fastq files where the run completes successfully, and I’m using the same reference for all isolates.

This is the error message I get in the terminal:

**Creating coverage plot for region: NODE_26:1-68069
sh: 1: cannot create /breseq_repeats_output/ECFDCSP34/output/evidence/1.r.log: Directory nonexistent
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error running command:
[system] R --vanilla < "/NGStools/breseq-0.38.1-Linux-x86_64/bin/../share/breseq/plot_coverage.r" > "/breseq_repeats_output/ECFDCSP34/output/evidence/1.r.log" --args in_file="/breseq_repeats_output/ECFDCSP34/output/evidence/1_14.coverage.tab" out_file="/breseq_repeats_output/ECFDCSP34/output/evidence/NODE_17.overview.png" pdf_output=0 total_only=0 window_start=1 window_end=103956 avg_coverage=0.0 fixed_coverage_scale=0
Result code: 512
FILE: libbreseq/common.h   LINE: 1411
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Backtrace with 14 stack frames.
breseq() [0x43f736]
breseq() [0x442f81]
breseq() [0x49dbec]
breseq() [0x5bd90f]
breseq() [0x5bfcb6]
breseq() [0x5bfeb9]
/lib/x86_64-linux-gnu/libc.so.6(+0x942e7) [0x7f45a4e9a2e7]
breseq() [0x5c0f71]
breseq() [0x5c1133]
breseq() [0x5bfdb3]
breseq() [0x43ee7f]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xe6363) [0x7f45a5223363]
/lib/x86_64-linux-gnu/libc.so.6(+0x8f18a) [0x7f45a4e9518a]
/lib/x86_64-linux-gnu/libc.so.6(__clone+0x44) [0x7f45a4f23af4]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
terminate called without an active exception
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Segmentation Fault
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Backtrace with 20 stack frames.
breseq() [0x43f736]
breseq() [0x43fa95]
/lib/x86_64-linux-gnu/libc.so.6(+0x3c4b0) [0x7f45a4e424b0]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x174) [0x7f45a4e28919]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa4ee6) [0x7f45a51e1ee6]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb6e9c) [0x7f45a51f3e9c]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb6f07) [0x7f45a51f3f07]
breseq() [0x640639]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ebe5) [0x7f45a4e44be5]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ed20) [0x7f45a4e44d20]
breseq() [0x43f962]
breseq() [0x442f81]
breseq() [0x49dbec]
breseq() [0x5bd90f]
breseq() [0x5bfcb6]
breseq() [0x5bfeb9]
/lib/x86_64-linux-gnu/libc.so.6(+0x942e7) [0x7f45a4e9a2e7]
breseq() [0x5c0f71]
breseq() [0x5c1133]
breseq() [0x5bfdb3]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**
