### ISSUE TITLE
run stalling, but no specific error message

### ISSUE THREAD

**Issue by jhastie** [barricklab/breseq#340]
Hello, 

I've installed using conda and I successfully get the output from breseq -h. However, when I try to run samples I'm getting the following output without results. No specific error message is supplied. Three folders are produced (01_sequence_conversion, data, and output), but the only file produced is the log.txt file that contains the input code. 

================================================================================
---> bowtie2  :: version 2.5.0 [/opt/conda/envs/env_breseq2/bin/bowtie2]
---> bowtie2  :: NOTE :: breseq output may vary slightly depending on your bowtie2 version
---> bowtie2  :: NOTE :: and occasionally bowtie2 versions may have bugs that cause crashes.
---> bowtie2  :: NOTE :: bowtie2 version 2.4.5 is recommended with this breseq version.
---> R        :: version 4.2.2 [/opt/conda/envs/env_breseq2/bin/R]
+++   NOW PROCESSING Read and reference sequence file input
Backtrace with 8 stack frames.
breseq(+0x44cf4) [0x5561acafacf4]
breseq(+0x19198f) [0x5561acc4798f]
breseq(+0x19ec04) [0x5561acc54c04]
breseq(+0x19ee64) [0x5561acc54e64]
breseq(+0x6e460) [0x5561acb24460]
breseq(+0x36cc4) [0x5561acaeccc4]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f2b5e91abf7]
breseq(+0x40559) [0x5561acaf6559]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Thanks!
Jessica

**Comment by jeffreybarrick** [comment]
That's odd. The reference sequence file you provided seems to be causing a hard crash. If you can email that to me at the address in the _breseq_ command-line header, I can take a look.

**Comment by jeffreybarrick** [comment]
Problem was encountered on a virtual workstation. It seems to have been some kind of misinterpretation of the encoding of the input text files. Reboots and reinstalls using mamba seem to have solved the issue.
