### ISSUE TITLE
what is causing this error? "libc++abi: terminating with uncaught exception of type std::domain_error"

### ISSUE THREAD

**Issue by zahraa992** [barricklab/breseq#342]
Hiya,

I'm totally new to breseq :') and I very much want to learn it. I'm facing this error whenever I run the reference alignment, my sequences are good, so I don't think they are causing the issue because my PI was able to get a nice table for the SNPs and mutations using them. Breseq and bowtie2 are both in the bin file of miniconda 3, so I don't think its a PATH problem either, what do you think is causing this error :( I would very much appreciate your help.

this is my run (or pipeline? totally new to these terms xD : 
breseq -n analyses6 -r DSM639_reference.gbff -j 3 "/users/user/library/cloudstorage/onedrive/year 2/WGS/*Illumina\ reads/*.fastq" &> analyses6.out &

below is the output I get whenever I run cat nohup.out command: 
================================================================================
breseq 0.37.1     http://barricklab.org/breseq

Active Developers: Barrick JE, Deatherage DE
Contact:           <jeffrey.e.barrick@gmail.com>

breseq is free software; you can redistribute it and/or modify it under the
terms the GNU General Public License as published by the Free Software 
Foundation; either version 2, or (at your option) any later version.

Copyright (c) 2008-2010 Michigan State University
Copyright (c) 2011-2022 The University of Texas at Austin

If you use breseq in your research, please cite:

  Deatherage, D.E., Barrick, J.E. (2014) Identification of mutations
  in laboratory-evolved microbes from next-generation sequencing
  data using breseq. Methods Mol. Biol. 1151: 165–188.

If you use structural variation (junction) predictions, please cite:

  Barrick, J.E., Colburn, G., Deatherage D.E., Traverse, C.C.,
  Strand, M.D., Borges, J.J., Knoester, D.B., Reba, A., Meyer, A.G. 
  (2014) Identifying structural variation in haploid microbial genomes 
  from short-read resequencing data using breseq. BMC Genomics 15:1039.
================================================================================
---> bowtie2  :: version 2.5.1 [/Users/user/miniconda3/envs/file/bin/bowtie2]
---> bowtie2  :: NOTE :: breseq output may vary slightly depending on your bowtie2 version
---> bowtie2  :: NOTE :: and occasionally bowtie2 versions may have bugs that cause crashes.
---> bowtie2  :: NOTE :: bowtie2 version 2.4.5 is recommended with this breseq version.
---> R        :: version 4.2.2 [/Users/user/miniconda3/envs/file/bin/R]
+++   NOW PROCESSING Read and reference sequence file input
  READ FILE::Illumina reads
    Converting/filtering FASTQ file...
    Original base quality format: ILLUMINA_1.3+ New format: SANGER
    Original reads: 0 bases: 0
    Filtered reads: none
    Analyzed reads: 0 bases: 0
  READ FILE::Iluumina reads
    Converting/filtering FASTQ file...
    Original base quality format: ILLUMINA_1.3+ New format: SANGER
    Original reads: 0 bases: 0
    Filtered reads: none
    Analyzed reads: 0 bases: 0
  READ FILE::illumina reads
    Converting/filtering FASTQ file...
    Original base quality format: ILLUMINA_1.3+ New format: SANGER
    Original reads: 0 bases: 0
    Filtered reads: none
    Analyzed reads: 0 bases: 0
  ::TOTAL::
    Original reads: 0 bases: 0
    Analyzed reads: 0 bases: 0
[samtools] faidx ./data/reference.fasta
  REFERENCE: NZ_CP046615
  LENGTH: 2225130
libc++abi: terminating with uncaught exception of type std::domain_error: type must be number, but is null

**Comment by jeffreybarrick** [comment]
There's something up with with the part of your command that is specifying the FASTQ files:
`"/users/user/library/cloudstorage/onedrive/year 2/WGS/Illumina\ reads/.fastq"`
Is that actually what you typed? It's processing the same file "Illumina reads" file (or maybe folder) three times and finding that these are empty files with no reads.

Maybe it should be this?
`"/users/user/library/cloudstorage/onedrive/year 2/WGS/Illumina reads/*.fastq"`

I would try running it with providing the full path to one FASTQ file and see if that works
