### ISSUE TITLE
Use GD tools apply to generate several distinct updated references with similar frequency variants from polymorphism mode

### ISSUE THREAD

**Issue by spleonard1** [barricklab/breseq#343]
Is it possible to use gdtools to generate distinct updated references from predicted mutations with similar frequencies identified in polymorphism mode? For example, I have a set of ~36 fasta sequences as a reference, and  for several of them there are sets of mutations at near identical frequencies that likely represent distinct alleles (this makes sense with how these were made). I would like to make an updated reference that has applied the mutations of similar frequency independently. 

I figure I can use gd tools filter to make separate gd files to then apply to my reference. Is that the best way? Thanks!

**Comment by jeffreybarrick** [comment]
That should work. I think `gdtools APPLY` will complain or not allow you to apply mutations that have frequencies < 1. If so, just delete all the `frequency=` parts of the lines.

**Comment by spleonard1** [comment]
awesome, thanks!
