### ISSUE TITLE
0.37.1 binary throws "unable to execute bin/breseq: Bad CPU type in executable" on Intel Mac

### ISSUE THREAD

**Issue by mdt1024** [barricklab/breseq#344]
However, when I download the 2020 version 0.35.3 it works without an issue, meaning that it can run 'bin/breseq' and run_tests.sh completes without any issues.  Output below:

```
~/tmp % cd breseq-0.37.1-MacOSX-10.9+
~/tmp/breseq-0.37.1-MacOSX-10.9+ % bin/breseq
zsh: bad CPU type in executable: bin/breseq
~/tmp/breseq-0.37.1-MacOSX-10.9+ % cd ../breseq-0.35.3-MacOSX-10.9+
~/tmp/breseq-0.35.3-MacOSX-10.9+ % bin/breseq
================================================================================
breseq 0.35.3  revision 3fdbc18adb50   http://barricklab.org/breseq
[USAGE cont'd...]
```

Was the 0.37.1 binary compiled only for Apple silicon?

Mac used in the above is a 2020 Model A2251 2.3 GHz Intel i7.

**Comment by jeffreybarrick** [comment]
Yes, you've diagnosed the problem correctly. This is our bad for not labeling things accurately and paying attention to this.

The newer v0.38.0 candidate release is a universal binary that should run on Intel or Apple Silicon macs, so going forward this has been addressed. 

If you can install _breseq_ through bioconda, 0.37.1 should work fine on an Intel Mac when installed that way.
