### ISSUE TITLE
Terminal width of 80

### ISSUE THREAD

**Issue by swplotner** [barricklab/breseq#348]
when breseq start with a narrow terminal, the following is observable, it outputs the copyright stuff and then hangs on outputting the options. 

During the hang, the process is at 100% CPU utilization and won't stop. Doing an strace on the PID reveals nothing hence, no system calls... I attached to the process with gdb and did a single step and that reveals:

0x0000000000470ffc in breseq::AnyOption::word_wrap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int) ()

has anyone else observed this?

If I change my terminal to 132 width everything works great invoking breseq, it shows the copyright stuff and the options correctly.

**Comment by jeffreybarrick** [comment]
Oh jeez. I can reproduce this and will fix it ASAP. I think this explains why my update for Bioconda is failing tests. Thanks!

**Comment by swplotner** [comment]
I have done a simple "hack" to test this by changing the line:
		terminal_width = (ws.ws_col==0) ? 80 : ws.ws_col;
to 
		terminal_width = 132;
in the src/c/breseq/anyoption.cpp and recompiled the code and the hang disappears.

**Comment by jeffreybarrick** [comment]
Fixed in current version on Bioconda
