### ISSUE TITLE
Cannot read reference alignment

### ISSUE THREAD

**Issue by filifed** [barricklab/breseq#353]
Time loading reference: 00:00:00
Time loading forward index: 00:00:01
Time loading mirror index: 00:00:00
Hi everyone,

I was running alignments of 12 packs of read with the same three sequences. For 3 of them, everything went fine. For the other 9 though, I get this error:

Multiseed full-index search: 03:07:40
9154199 reads; of these:
  9154199 (100.00%) were unpaired; of these:
    352616 (3.85%) aligned 0 times
    8566739 (93.58%) aligned exactly 1 time
    234844 (2.57%) aligned >1 times
96.15% overall alignment rate
Time searching: 03:07:42
Overall time: 03:07:42
[system] bowtie2 -t --no-unal -p 24 -L 20 --ma 1 --mp 3 --np 0 --rdg 2,3 --rfg 2,3 --ignore-quals --local -i S,1,0.25 --score-min L,6,0.2 -k 2000 --reorder -x "PpCCS3/02_reference_alignment/reference" -U "PpCCS3/02_reference_alignment/CCS3_EKDN230023138-1A_HF5T2DSX7_L2_2.fq.stage1.unmatched.fastq" -S "PpCCS3/02_reference_alignment/CCS3_EKDN230023138-1A_HF5T2DSX7_L2_2.fq.stage2.matched.sam"
stat: Bad file descriptor
Warning: Could not open read file "PpCCS3/02_reference_alignment/CCS3_EKDN230023138-1A_HF5T2DSX7_L2_2.fq.stage1.unmatched.fastq" for reading; skipping...
Error: No input read files were valid
(ERR): bowtie2-align exited with value 1
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error running command:
[system] bowtie2 -t --no-unal -p 24 -L 20 --ma 1 --mp 3 --np 0 --rdg 2,3 --rfg 2,3 --ignore-quals --local -i S,1,0.25 --score-min L,6,0.2 -k 2000 --reorder -x "PpCCS3/02_reference_alignment/reference" -U "PpCCS3/02_reference_alignment/CCS3_EKDN230023138-1A_HF5T2DSX7_L2_2.fq.stage1.unmatched.fastq" -S "PpCCS3/02_reference_alignment/CCS3_EKDN230023138-1A_HF5T2DSX7_L2_2.fq.stage2.matched.sam"
Result code: 256
FILE: libbreseq/common.h   LINE: 1411
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Backtrace with 7 stack frames.
breseq(+0x44cf4) [0x557d8dfa4cf4]
breseq(+0x4a4f1) [0x557d8dfaa4f1]

I have very little experience with coding/running scripts but I will still like to get some help

Best,
Filippo
breseq(+0x6d585) [0x557d8dfcd585]
breseq(+0x36cc4) [0x557d8df96cc4]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fa365c29d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fa365c29e40]
breseq(+0x40559) [0x557d8dfa0559]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jeffreybarrick** [comment]
My guess is that you are running out of hard drive space during running _breseq_ and it is not able to create the input file for bowtie2. Delete the entire output directory and try rerunning one of the jobs after you free up some space to see if this is the issue.
