### ISSUE TITLE
gdtools INTERSECT based on gene_name

### ISSUE THREAD

**Issue by osekulovic** [barricklab/breseq#355]
I have gd files from several breseq comparisons (single reference file). I would like to intersect for common variants, however variants do not share the exact same positions. In other words, is it possible to find common variants based on gene_name or gene_product rather than position? I'm less interested if the exact same mutation is present in two datasets but I want to know if the same gene is mutated regardless if the same position/allele is mutated.

Thank you!

**Comment by jeffreybarrick** [comment]
Here's something that may work for you.

To begin, you will need to have annotated GD files with information on how mutations affect genes. These can be found at `output/evidence/annotated.gd`  within the main _breseq_ output directory. Or, you can regenerate them from the main `output/output.gd` file using `gdtools ANNOTATE`.

Then, you can use `gdtools FILTER` to remove all mutations that don't have a matching gene name. For example, this gets rid of all mutations that do not have a `gene_name` field of `pykF`.

```
gdtools FILTER -c 'gene_name!=pykF' -o <sample>.filtered.gd  <sample>.gd
```

If you are also interested in mutations in the adjacent intergenic region (maybe they are promoter mutations), you can modify the command to have two conditions, and it will remove all for which BOTH conditions are true. Here's an example, building on the last one:

```
gdtools FILTER -c 'gene_name!=pykF' -c 'gene_name!=ydhZ/pykF' -o <sample>.filtered.gd  <sample>.gd
```

You could then to a `gdtools COMPARE` on those files to make an HTML, CSV, etc. output file incorporating information across all samples. If you want to make a list of unique variants, you could also use `gdtools MERGE` to put them all in one GD file.

Feel free to ask followup questions as these `gdtools` commands are not documented or tested as well as the main _breseq_ code. We add/fix them as we or others use them.

**Comment by osekulovic** [comment]
Oh I see! I ran my genome of interest on 3 different reference genomes, but I should reverse my approach and run `breseq` of all three references against my genome of interest, so only one reference. Thank you - I will try that.
