### ISSUE TITLE
Problem in understanding breseq output (26-bp)2→1

### ISSUE THREAD

**Issue by Subhajeet1997** [barricklab/breseq#358]
![image](https://github.com/barricklab/breseq/assets/83592029/962150e6-a83e-4f29-8358-a5352f2a4420)
what this (26-bp)2→1 actually means?

**Comment by jeffreybarrick** [comment]
There was a tandem repeat of 2x26 base pairs in the reference (26 bp then the same 26 bp again right after it). In the sample, only one copy of the repeat is detected (one was deleted). 

So, it's a 26-bp deletion, but _breseq_ gives you some extra info that a tandem repeat was involved.
