### ISSUE TITLE
Generating new consensus sequence with variants

### ISSUE THREAD

**Issue by james-weger** [barricklab/breseq#360]
Hello,

Thanks for creating this useful tool. I'd like to call variants in a mixed viral population and have breseq apply the variants above a certain threshold to a new .gbk or .fasta file. Is this possible with breseq currently?

thanks in advance

**Comment by jeffreybarrick** [comment]
Sure, maybe with a little intervention.

If you run _breseq_ in `--polymorphism` mode, you will have an `output.gd` file in the `output` directory. 

You can then use the `gdtools FILTER` command to filter it to just the mutations you want to keep. The command would be something along the lines of this (but change the 0.8 to whatever your threshold would be).

```
gdtools FILTER -c frequency>=0.8 -o filtered.gd output.gd
```

Here's where some manual intervention is needed. You will need to edit `filtered.gd` and either remove the parts of the lines that are `frequency=XXX` or set them to be `frequency=1` for the next step to work. (You are converting the polymorphic calls to consensus ones.) A search and replace should be able to get the job done.

Then, you can use `gdtools APPLY` to generate the updated genome

```
gdtools APPLY -o updated.gbk -r reference.gbk filtered.gd
```

Use the command line `--help` for these commands to see the parameters. I didn't test what I wrote, but it should be able to help you make any needed correction.

**Comment by james-weger** [comment]
Thank you! I just had to update the FILTER step to

gdtools FILTER -c "frequency <= 0.5" -o filtered.gd output.gd

and it worked. I appreciate your help!

Humbly,
James
-- 
James Weger-Lucarelli, PhD
Assistant Professor
Dept. of Biomedical Sciences and Pathobiology
College of Veterinary Medicine
Virginia Tech
Fralin Life Sciences Building
3
<https://maps.google.com/?q=1981+Kraft+Drive,+Room+2033+Blacksburg,+VA+24061&entry=gmail&source=g>60
W Campus Dr.
Blacksburg, VA 24061
<https://maps.google.com/?q=1981+Kraft+Drive,+Room+2033+Blacksburg,+VA+24061&entry=gmail&source=g>
(540) 231-6594

https <https://www.thewegerlucarellilab.com/>://w
<https://www.thewegerlucarellilab.com/>ww.thewegerlucarellilab.com
<https://www.thewegerlucarellilab.com/>/
<https://www.thewegerlucarellilab.com/>
