### ISSUE TITLE
How to Calculate the Frequency of IS Insertion Events

### ISSUE THREAD

**Issue by miniluphy** [barricklab/breseq#362]
Hello,

While analyzing the second-generation sequencing data of the microbial popultaion, I observed an insertion event in the virB9 gene using the IGV tool (Fig. 1). This finding was subsequently validated through Sanger sequencing. During the analysis using the breseq tool (v0.38.1 Polymorphism Mode), the output.html in "Unassigned new junction evidence," indicating two insertion pieces of evidence for the virB9 gene, with mutation frequencies of 88.2% and 68.5%, respectively (Fig. 2). May I inquire whether it is appropriate to simply average these two values (78.35%) as the overall frequency of this insertion mutation? Also, could you provide guidance on how to statistically determine the frequency of this IS insertion event based on second-generation sequencing data?

Thank you.
![Fig 1 IGV](https://github.com/barricklab/breseq/assets/68535103/65c05043-d7c0-43a3-bd4d-93aba81720d4)
![Fig  2 breseq-unassigned new junction evidence](https://github.com/barricklab/breseq/assets/68535103/b693e976-e218-49af-a432-ee0a157e2541)

**Comment by jeffreybarrick** [comment]
You can use equation (2) in this paper: https://doi.org/10.3389/fgene.2014.00468
The variant counts in your example are 269 and 87. The reference counts are 36 and 40.

If you had IS elements annotated in your reference genome, _breseq_ would probably be able to join up the two JC evidence items and predict it as a MOB with the calculated frequency for you.

You would need to annotate IS elements in your reference genome file as described here, but it's well worth the effort.

https://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/refseq_format.html#adding-is-element-annotations
