### ISSUE TITLE
ERROR: Seq ID not found in reference sequence files provided for entry

### ISSUE THREAD

**Issue by BrinleyL** [barricklab/breseq#369]
I tried to annotate a vcf file(VCFv4.2) from the sequencing center, so I converted them to .gd file using "gdtools VCF2GD" command. Then,  I used command like "gdtools COMPARE -r myreference.gbk myvcf.gd". But it produced errors and said it cannot find the seq-id in reference file. I tried "VALIDATE" command. It also produced errors: "ERROR: Seq ID not found in reference sequence files provided for entry". I checked my files and find seq-id was right there. Not sure why it doesn’t work. Below are first few lines of my files. The package version is 0.38.2. Thank you.

**myvcf.gd:**
<img width="831" alt="Screenshot 2024-04-04 at 3 10 47 PM" src="https://github.com/barricklab/breseq/assets/53031875/3b2c75b9-f169-441a-b04a-6451f1a49144">
**myreference.gbk**:
<img width="556" alt="Screenshot 2024-04-04 at 3 11 29 PM" src="https://github.com/barricklab/breseq/assets/53031875/a57f5618-3b06-4bf2-bbba-e2915db2f2c8">
**errors from VALIDATE**:
<img width="837" alt="Screenshot 2024-04-04 at 3 13 52 PM" src="https://github.com/barricklab/breseq/assets/53031875/b0537515-01f3-4c8d-a52d-c599e575d41d">

**Comment by jeffreybarrick** [comment]
The mismatch is likely between the use of `CP000431.1` by whatever program generated the original VCF file and just `CP000431` by _breseq_. Try doing a find/replace with a text file to convert all occurrences to `CP000431`. 

_breseq_loads the seq_id from GenBank files with this preference:
The sequence ID is assigned with this order of preference LOCUS > ACCESSION > VERSION

**Comment by jeffreybarrick** [comment]
Yeah.... unfortunately, it doesn't march through the choices in that order until it finds a match. It searches in that order and stops and assigns it when one of those is present. The `--genbank-field-for-seq-id` option is only available for the main _breseq_ command... not all the `gdtools` command variants. 

Either of these could be implemented, of course, if someone wanted to add them to the code, but it's probably easiest to just do a search-and-replace on a file generated by a different program/pipeline or maybe you can edit the LOCUS line of the GenBank to use CP000431.1 if it fits/validates when used as an input by _breseq_.

**Comment by BrinleyL** [comment]
Hi @jeffreybarrick 

Thank you for your clarification! I just edited my reference file at Locus and it works! I provided multiple .gd files with input and the output file showed different percentage for the sample column. Could you tell me what those percentages mean (a figure is attached below)? Thanks.
<img width="596" alt="Screenshot 2024-04-09 at 11 11 28 AM" src="https://github.com/barricklab/breseq/assets/53031875/0b61c1c7-db40-4a02-8ac5-b910ba597f72">

**Comment by jeffreybarrick** [comment]
Great!

The 100% means the mutation (names in the row) is present in that sample (named in the column). Blank cells mean 0% (the mutation is not present in that sample).

For some types of analyses (of mixed samples), there can be predictions that are between 0% and 100%, but this does not seem to apply to your input files.

**Comment by BrinleyL** [comment]
Thank you, Jeffrey! I feel clear now.
