### ISSUE TITLE
bowtie2 versions

### ISSUE THREAD

**Issue by gabypetrungaro** [barricklab/breseq#373]
Hi,
when running breseq 0.38.2, I get a warning about the bowtie2 version (see below). However, apparently the recommended version of bowtie2 (2.4.5) is older that the one it is using (version 2.5.3), right?. Why would breseq recommend to use an older version of bowtie2?

Thanks and best,
Gabriela.

================================================================================
breseq 0.38.2     http://barricklab.org/breseq

Active Developers: Barrick JE, Deatherage DE
Contact:           <jeffrey.e.barrick@gmail.com>

breseq is free software; you can redistribute it and/or modify it under the
terms the GNU General Public License as published by the Free Software 
Foundation; either version 2, or (at your option) any later version.

Copyright (c) 2008-2010 Michigan State University
Copyright (c) 2011-2022 The University of Texas at Austin

If you use breseq in your research, please cite:

  Deatherage, D.E., Barrick, J.E. (2014) Identification of mutations
  in laboratory-evolved microbes from next-generation sequencing
  data using breseq. Methods Mol. Biol. 1151: 165–188.

If you use structural variation (junction) predictions, please cite:

  Barrick, J.E., Colburn, G., Deatherage D.E., Traverse, C.C.,
  Strand, M.D., Borges, J.J., Knoester, D.B., Reba, A., Meyer, A.G. 
  (2014) Identifying structural variation in haploid microbial genomes 
  from short-read resequencing data using breseq. BMC Genomics 15:1039.
================================================================================
---> bowtie2  :: version 2.5.3 [/home/gpetrung/conda_env_breseq038/bin/bowtie2]
---> bowtie2  :: NOTE :: breseq output may vary slightly depending on your bowtie2 version
---> bowtie2  :: NOTE :: and occasionally bowtie2 versions may have bugs that cause crashes.
---> bowtie2  :: NOTE :: bowtie2 version 2.4.5 is recommended with this breseq version.
---> R        :: version 4.3.2 [/home/gpetrung/conda_env_breseq038/bin/R]

**Comment by jeffreybarrick** [comment]
Most likely newer bowtie2 versions are fine.

Version 2.5.3 is suggested because it's been tested with _breseq_ and occasionally updates introduce bugs or changes in programs that disrupt compatibility.

**Comment by gabypetrungaro** [comment]
thanks, version 2.5.3 is the one used (suggested was 2.4.5, thus the question)
