### ISSUE TITLE
Zsh: illegal hardware instruction

### ISSUE THREAD

**Issue by Ensalada-Caesar** [barricklab/breseq#375]
I'm on a 2022 Mac Studio Desktop with a Mac M1 Max chip and 32 Gigs of memory.

I've followed the recommended installation instructions using bioconda to install the breseq package and followed the instructions of creating a virtual environment in conda using python version 3.9

$ conda create -n breseq python=3.9

I downloaded and unzipped the files for Tutorial 1: Clonal Samples and made sure the directory was in the proper location and that the files REL606.gbk and SRR098034.fastq could be found by the ls command.

When I attempted to perform the first code of Tutorial 1:

$ breseq -l 60 -j 8 -o ZDB83_output -r REL606.gbk SRR098034.fastq

I receive the following error:
![Screenshot 2024-07-17 at 1 19 54 PM](https://github.com/user-attachments/assets/9bc1f3ca-6083-4a84-8862-1b41a3b15011)

The program terminates and the only generated output are empty files and a log.txt file that just has the input code in it. No .html or .csv file is generated.

I searched up the zsh: illegal hardware instruction error, and the most I've found is issues with the M1 chip in my computer.

Any and all help is appreciated. Thank you.

**Comment by jeffreybarrick** [comment]
This error is usually related to an executable having been built for a different architecture than the one on a machine (for example if you transfer files from an old computer to a new one). In this case, your Conda may be installing the x86 version of breseq versus one compiled for Mac Silicon.

Try setting up Conda again from the start using the miniconda package for Apple M1 and see if that works:
https://docs.anaconda.com/miniconda/

**Comment by jeffreybarrick** [comment]
Aha! I was able to reproduce this error if I used the SRA version of the read file. I bet this is the culprit.

Be sure you download the FASTQ version from the ENA website. 

![Screenshot 2024-07-17 at 5 00 07 PM](https://github.com/user-attachments/assets/ee9bb64d-6b33-4416-b9a3-2f72be1ef8bf)
