### ISSUE TITLE
zsh: trace trap

### ISSUE THREAD

**Issue by Ensalada-Caesar** [barricklab/breseq#376]
Hi Dr. Barrick,

I reported last week on Case#375 about the issue with zsh: hardware limitation.

I followed your instructions and downloaded a new version of conda through Miniconda, making sure to use the Apple M1 pkg installer and confirming it was being used.

I also confirmed that I was downloading the correct fastq file and not the SRA version.

However, I am getting a new zsh error now.

zsh: trace trap

Please help at your convenience. Thank you

**Comment by jeffreybarrick** [comment]
Can you email me at the address in the _breseq_ header so we can find a way for you to make your exact input files and command line available to me so that I can see if I can reproduce the issue?

**Comment by jeffreybarrick** [comment]
You could also try installing an earlier version of _breseq_ in your Conda environment to see if that changes things. For example:

```
conda install breseq=0.38.1
```

**Comment by jeffreybarrick** [comment]
Did this work? Another possibility is that you are running out of hard drive space, which can lead to errors when files get unexpectedly truncated.

**Comment by ThomasHindre** [comment]
Hi Dr Barrick,
I have the same zsh: trace trap issue.
I used mamba/bioconda to install breseq on an Apple M2. It seems to work with full acces to -h function of breseq after installation.
I then followed "test drive" from the GitHub wiki. breseq wrote new directories in the test_drive folder but quickly stopped with the following error: 
+++   NOW PROCESSING Read and reference sequence file input
zsh: trace trap  breseq -r NC_012967.gbk SRR030257_1.fastq SRR030257_2.fastq

I saw that the non-recommended Bowtie2 2.5.4 came with the breseq installation but did not find the way to downgrade to bowtie2 2.4.5 nor to breseq 0.38.1. Both were not reachable when using Bioconda channel.

Please help at your convenience. Many thanks

**Comment by jeffreybarrick** [comment]
Hi all,

This runtime error seems like it is related to a recent update for arm64 compilation in the bioconda recipe.

https://github.com/bioconda/bioconda-recipes/pull/49129

I am able to install and successfully run the previous bioconda version of _breseq_ fine on my M3 machine:

```
mamba create -n breseq breseq=0.38.3
```

or in an existing conda environment
```
mamba install breseq=0.38.3
```

Please use this workaround until we sort out what happened with the most recent bioconda recipe.

**Comment by ziweizhong** [comment]
I am getting this same issue on my M2 mac with breseq 0.39.0. I tried to install a previous version of breseq as suggested above (0.38.3), but there is no 0.38.3 available from the current channels and when I checked the bioconda repository, there is indeed no osx-arm64 version of breseq. 

Any other suggestions on workarounds for ARM based OSX machines?

**Comment by ThomasHindre** [comment]
Faced with the same inability to install breseq 0.38.3 via the bioconda repository, I finally managed to install version 0.39.0 using one of the Do-It-Yourself methods.

**Comment by jeffreybarrick** [comment]
I think this problem must have been related to an update to the bioconda bowtie2 package to allow for ARM64 compilation. I was able to reproduce the problem a few weeks ago on my M3 Mac, but now things seem to be working fine with a normal bioconda install of any version. Possibly this is b/c it took a while for that change to propagate, including on individual machines if old versions were cached on your machine.

Can someone verify whether this is fixed for them or still a problem by following these steps?

1. Make sure you have the newest MacOSX (v14.6.1)

2. Clean out your conda cache, so we are sure your system is getting all latest package descriptions:
```
conda clean -a
```
3. Install

4. Run _breseq_ on any dataset.
to be sure no cached packages are being used.

**Comment by jeffreybarrick** [comment]
Oops spoke too soon. Problem still there... and appears to be happening within _breseq_. Will investigate further.

**Comment by jeffreybarrick** [comment]
Ok. Let's see if we have a handle on this now...

At least on my system, when I use the default commands to install _breseq_ through Conda it installs executables compiled for `x86_64` versus the native `arm64` architecture.

```bash
which breseq
# /Users/jbarrick/miniconda3/envs/breseq-0.39.0-test/bin/breseq
file /Users/jbarrick/miniconda3/envs/breseq-0.39.0-test/bin/breseq 
# /Users/jbarrick/miniconda3/envs/breseq-0.39.0-test/bin/breseq: Mach-O 64-bit executable x86_64
```

Apparently, there was a recent shift in how _breseq_ was built by the Bioconda recipe or some other part of this ecosystem that makes the non-native x86_64 compiled executable cause a runtime crash on a Mac with Apple Silicon (M1, M2, etc.).

__The fix that does work for me__ is to force Bioconda to install the new `osx-arm64` architecture version of _breseq_ (and also associated programs like bowtie2) using this command:

```bash
CONDA_SUBDIR=osx-arm64 mamba create -n breseq-arm64 breseq 
```

You can verify that the installation is using the correct architecture using commands like this:
```bash
conda activate  breseq-arm64
which breseq
#/Users/jbarrick/miniconda3/envs/breseq-arm64/bin/breseq
file /Users/jbarrick/miniconda3/envs/breseq-arm64/bin/breseq
#/Users/jbarrick/miniconda3/envs/breseq-arm64/bin/breseq: Mach-O 64-bit executable arm64
```

You could also update/install/configure your Conda to use `osx-arm64` as the default platform:
```
conda config --set subdir osx-arm64
```
After doing this a normal install should be of the correct platform.

Just be aware that this could cause problems with some other packages not being available that are available for `osx-64`.

**Comment by ThomasHindre** [comment]
I did test CONDA_SUBDIR=osx-arm64 mamba create -n breseq-arm64 breseq on my M2 machine.
It succeeded installing the osx-arm64 architecture version as reported by "which breseq".
However I still have the same zsh: trace trap issue.
But maybe that's just me (I'm not an expert!).

**Comment by jeffreybarrick** [comment]
Thanks for checking... I will continue to investigate.

**Comment by Basidiobolus** [comment]
Probably the same issue... 
With Mach-O 64-bit executable arm64 and using a gff or genbank file reference, I get an immediate
"

> +++   NOW PROCESSING Read and reference sequence file input
> zsh: trace trap  breseq -o /Users/danielhenk/Desktop/TestDrive_Breseq/Test -r  

 
"


but when I use a fasta reference breseq makes it all the way to...
"
> +++   NOW PROCESSING Resolving best read alignments
>   READ FILE:SRR030257_1
>     READS:10000
> zsh: trace trap  breseq -o /Users/danielhenk/Desktop/TestDrive_Breseq/Test -r 
"

**Comment by jeffreybarrick** [comment]
Here's a temporary workaround that those experiencing issues with Macs that have Apple Silicon (M1, M2, etc., chips).

Create a conda environment that has the programs _breseq_ needs to run installed:
```
conda create -n breseq
conda install bowtie2 r-base r-cairo
```

Download the latest _breseq_ MacOSX release here:
https://github.com/barricklab/breseq/releases/tag/v0.39.0 

Place this in a stable location on your machine. Don't move it later!

Unarchive and navigate into the main directory that has `bin` within it.

For example:
```
cd breseq-0.39.0-MacOSX-10.13+-universal
```

Then, run a command that will set the `$PATH` variable for this Conda environment to point to include the location of the _breseq_ executable:
```
conda activate breseq
conda env config vars set PATH=$PATH:$PWD/bin
conda activate breseq
```

The first time you run _breseq_ and _gdtools_, you will need to open **System Settings** and scroll down on the **Privacy & Security** tab to where there is a notice about a program being blocked for you to select "allow".

**Comment by ab-2996** [comment]
Hi Jeff,

Thanks for troubleshooting this. I tried the manual installation on Mac (M1 Mac Pro), and have the following error:

```
(breseq) andrew@ Bioinformatics % breseq
dyld[16687]: Library not loaded: /opt/local/lib/libz.1.dylib
  Referenced from: <9257E5F8-E4E9-3F1B-AEAC-F09895F15323> /Users/andrew/Bioinformatics/breseq-0.39.0-MacOSX-10.13+-universal/bin/breseq
  Reason: tried: '/opt/local/lib/libz.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libz.1.dylib' (no such file), '/opt/local/lib/libz.1.dylib' (no such file)
zsh: abort      breseq
```

This is within a fresh breseq conda env with only bowtie2, r-base, and r-cairo installed.

**Comment by jeffreybarrick** [comment]
Update!

It seems like the Conda executables for `0.39.0` were corrupted or miscompiled for some unknown reason. They have just been regenerated, and now they are working fine for me with a normal Conda install. 

Try deleting your current Conda _breseq_ or environment with _breseq_ and re-installing.

Feel free to re-open this issue if you are still having problems.

P.S. You may still to use this install command on an Apple Silicon machine to get a native executable that should run more quickly:
```
CONDA_SUBDIR=osx-arm64 mamba create -n breseq breseq 
```
