### ISSUE TITLE
Cloud-based breseq

### ISSUE THREAD

**Issue by tdsone** [barricklab/breseq#379]
Hey, big fan of breseq! We set it up on modal.com to run it basically for free without installing it locally or access to an HPC: https://github.com/tdsone/breseq-on-modal If it helps others, you're free to share it in the docs or this repo.

**Comment by jeffreybarrick** [comment]
Very cool! Thanks for sharing. I've added a description and link of this option to the Install page in the manual.

https://github.com/barricklab/breseq/wiki/Installation

**Comment by tdsone** [comment]
Brilliant!
