### ISSUE TITLE
Multiple non-reference base polymorphisms

### ISSUE THREAD

**Issue by GoogleCodeExporter** [barricklab/breseq#38]
```
Polymorphisms between multiple non-reference bases are not evaluated/displayed 
correctly.
```

Original issue reported on code.google.com by `jeffrey....@gmail.com` on 28 Mar 2012 at 1:48

**Comment by jeffreybarrick** [comment]
Resolved. Change in RA evidence in 0.27 enables two alleles to be non-reference.
