### ISSUE TITLE
illegal hardware instruction in the M1 chip Macbook

### ISSUE THREAD

**Issue by HongAnTechnician** [barricklab/breseq#382]
I downloaded a .gb file from NCBI with "all features" and "show sequences" to use it as a reference genome, it's okay to use it to run breseq in the linux OS. However, when I run the breseq package on my M1 chip macbook, using the same reference genome and same Illumina sequencing reads, it always says "illegal hardware instruction". I'm a beginner, does anyone know how to fix this? Thanks a lot!
![breseq ](https://github.com/user-attachments/assets/d54552fc-f0da-497c-96b0-a1a0d1f40abc)

**Comment by HongAnTechnician** [comment]
And also, if I run breseq BAM2ALN in a M1 chip macbook using the files in the folder "data" generated by breseq running in Linux OS, it says "Cannot open input reference FASTA file (-f): data/reference.fasta". Is because of the problem of my reference genome file? or something about the Mac OS miniconda3?

<img width="907" alt="image" src="https://github.com/user-attachments/assets/6002e24e-fb99-4950-9bcb-69eda5588edf">

**Comment by jeffreybarrick** [comment]
Did you install _breseq_ using conda? 

If so, see #376 where you can find a workaround, while we sort out what is going on with the Conda install.

**Comment by HongAnTechnician** [comment]
> Did you install _breseq_ using conda?
> 
> If so, see #376 where you can find a workaround, while we sort out what is going on with the Conda install.

Thank you so much for your reply! I have tried this solution but seems still cannot work. I'm now just using the Linux OS and it works well.

**Comment by jeffreybarrick** [comment]
Have this fixed now. See #376

**Comment by HongAnTechnician** [comment]
> Have this fixed now. See #376

Re-installed breseq via conda, it works now! Thank you very much :)
