### ISSUE TITLE
Is it possible to call mutations in an assembled genome relative to a reference genome using Breseq?

### ISSUE THREAD

**Issue by mretier** [barricklab/breseq#384]
Hi,
I get de novo assembled E. coli genomes from a sequencing provider that we use in FASTA format.
I'd like to call mutations in those assembled genomes.

Since Breseq now can handle nanopore reads, I figured it might also be capable of calling mutations of just one very long read (the fully assembled genome). I tried running breseq (0.39.0) using a genbank file as reference (as I usually do with Illumina short read sequences) and a fastq file that was generated from the fasta file (assuming all basepair calls to be high quality). When I do this breseq finishes but doesn't align any sequences. The output.html file just indicates that the whole genome has been deleted (see attached screenshot).

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/ccb75cb3-52b3-436d-b058-fd34457b9ff7">

Is what I'm trying to achieve possible in Breseq? If so, how?

Thanks a lot for input.

Michael

**Comment by ira-zibbu** [comment]
Hi Michael,

Unfortunately, *breseq* cannot call mutations from a whole genome assembly; it needs either short or long reads. I can think of three work arounds:

1. Obtain the reads themselves, if possible, and use those in *breseq*. This would be the most ideal solution if you are not looking for large scale structural variants.

2. If you cannot obtain the reads that were used to assemble the genome, you can try to simulate reads from the genome assembly, and use those with *breseq*. [Here are some possible tools for simulation](https://www.nature.com/articles/s41437-022-00577-3). I believe this approach has worked for others with the same problem.

3. Use a whole-genome alignment tool like [MUMmer](https://mummer.sourceforge.net/manual/#snps). I've never used it to call mutations, but I do know it can do so. 

@jeffreybarrick correct me if I am wrong anywhere

**Comment by jeffreybarrick** [comment]
That about covers it. Thanks @ira-zibbu !

There's a hidden sub-command that can also assist with trying **Option 2**. 

You can get the help by running it with no options:

```
breseq SIMULATE-READS
```

Example usage:
```
breseq SIMULATE-READS -r reference.gbk -l 100 -c 80 -o reads.fastq
```

I've used this in a similar situation before with pretty good results. There are limitations if the genome is very divergent or very rearranged, but if it differs by just a few small differences, this can work well.

**Comment by mretier** [comment]
Thanks @ira-zibbu and @jeffreybarrick for the info.
Simulating the reads sounds like a good alternative. 
@jeffreybarrick I tried using your approach like this: 
```
breseq SIMULATE-READS -r de_novo_genome_assembly.fasta -l 100 -c 80 -o reads.fastq
```
This resulted in a fastq with the simulated reads. However, when I then ran breseq
```
breseq -o ./breseq_test -r ./reference.gb ./reads.fastq
```
it resulted in the same outcome as described in my original post.
Do you have an idea what could be going wrong?

**Comment by jeffreybarrick** [comment]
Hmm. I guess there's a reason it's an unreleased secret subcommand... It could be related to how the simulated reads don't have realistic quality scores or are too perfect in some way.

Anyway... glad this worked for you! It should be useful info for someone to come across in the future:
> Simulating reads using another Mason2 worked well together with Breseq, thanks for pointing me in that direction.
Maybe we can add this advice with an example to the _breseq_ docs at some point.
