### ISSUE TITLE
Error on MacOS Sequoia: Library not loaded: /opt/local/lib/libz.1.dylib

### ISSUE THREAD

**Issue by josia-pool** [barricklab/breseq#386]
Hi, I'm having issues running breseq on MacOS, it gives me the following error:
dyld[1574]: Library not loaded: /opt/local/lib/libz.1.dylib
  Referenced from: <9257E5F8-E4E9-3F1B-AEAC-F09895F15323> /Users/jopo/bioinformatics/breseq-0.39.0-MacOSX-10.13+-universal/bin/breseq
Reason: tried: '/opt/local/lib/libz.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libz.1.dylib' (no such file), '/opt/local/lib/libz.1.dylib' (no such file)

I can 'fix' this by adding 'export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/lib' to my path, but this gives issues with other programs.
Is there some way to make breseq try /usr/lib, and avoid exporting it to DYLD_LIBRARY_PATH?

**Comment by jeffreybarrick** [comment]
This is with the downloaded executable?

I'll look into it... the library is supposed to get statically linked so that it will not have to look for libz locally.

In the meantime, I'd recommend installing _breseq_ through Conda.

**Comment by josia-pool** [comment]
> This is with the downloaded executable?
I downloaded the latest release for MacOS, extracted the archive and exported the location to my PATH.
Thanks for looking into it.

**Comment by jeffreybarrick** [comment]
I think I've fixed this issue. Can you try downloading and using the new version?
https://github.com/barricklab/breseq/releases/tag/v0.39.0

**Comment by josia-pool** [comment]
> I think I've fixed this issue. Can you try downloading and using the new version? https://github.com/barricklab/breseq/releases/tag/v0.39.0

It works! Thanks for taking the time to fix it.
