### ISSUE TITLE
Homopolymer filtering with nanopore data

### ISSUE THREAD

**Issue by rowi2024** [barricklab/breseq#387]
Hello,
It is really great that Breseq can now work on Nanopore data!  However, since basecalling has improved with recent upgrades to nanopore chemistries and basecalling models, I wonder if you might consider reducing the filtering of the homopolymer regions (allowing larger homopolymers to be queried for mutations).  Thanks!!

**Comment by jeffreybarrick** [comment]
Yes, this seems reasonable.

If you're running in consensus mode, you should be able to do this with the current _breseq_ version. Add this option in addition to `-x` to relax the default Nanopore filtering:
```
--consensus-reject-indel-homopolymer-length 0
```

However, it looks like you can't currently disable this in polymorphism mode b/c `--polymorphism-no-indels` gets set. 

We can update that in the next version.

Note to self: Also, it looks like the help text for the `-x` option is a little broken. We could add some advice about making sure the base calling is done in high quality mode or adding back these options.

**Comment by rowi2024** [comment]
Thank you so much! That's great!  I will add this and re-run it as soon as my current run of breseq is done:)

**Comment by jeffreybarrick** [comment]
Good luck! Let me know if it doesn't work... these sets of options are not well-tested yet.

**Comment by rowi2024** [comment]
Thank you for the tip!  The --consensus-reject-indel-homopolymer-length 0 option worked perfectly.  Breseq now picks up our homopolymer mutations!

**Comment by jeffreybarrick** [comment]
Gosh, there's actually an even easier way... you can just leave the `-x` option off altogether. All of the other stuff there was to account for the higher error rate during mapping, so it is not necessary. (Just verified this by testing some of our data.)

In future version of _breseq_ the help text will make it clear that the `-x` option should only be used with fast basecalling.
