### ISSUE TITLE
breseq stalled on processing input files and ended with no errors

### ISSUE THREAD

**Issue by valery-shap** [barricklab/breseq#388]
Hello,

I'm using breseq for the first time. Firstly, I installed it (v.0.39.0) using conda on our HPC cluster (linux). I checked the log file of the slurm job and it showed only this text:
`================================================================================
---> bowtie2  :: version 2.5.4 [/home/miniconda3/envs/breseq/bin/bowtie2]
---> bowtie2  :: NOTE :: breseq output may vary slightly depending on your bowtie2 version,
---> bowtie2  :: NOTE :: and occasionally bowtie2 versions may have bugs that cause crashes.
---> bowtie2  :: NOTE :: bowtie2 version 2.4.5 is recommended with this breseq version.
---> R        :: version 4.4.2 [/home/miniconda3/envs/breseq/bin/R]
+++   NOW PROCESSING Read and reference sequence file input
`
this job created three folders:
01_sequence_conversion
data
output

I found the log.txt in the output folder and only breseq command was written there:
`Sun Nov 24 12:35:30 2024
breseq -r file.gbk -n file_name -j 10 -p -o output_folder ok_1.fastq.gz ok_2.fastq.gz
`
The gbk file was created by Prokka and all contigs were used. Reads were generated by Illumina.

The data folder contained two files: reference.fasta and reference.gff3.
After 3-4 hours of stalling this job ended without errors.

Then i found this issue #340 and decided to re-install using mamba. Now I sent this job again using mamba installation, but log files and the structure of folders are the same. So I suppose that re-installation didn't help.

Could you help me?

Upd. 
I run breseq (mamba installation) in a terminal (without slurm) on 4 CPUs with the same command and data, but removed -j flag. And it goes!
Then I repeated the same command (without -j flag) using SLURM and again it is stalling there.

Best regards,
Valery

**Comment by jeffreybarrick** [comment]
This sounds like it might be an issue with your particular HPC setup and the environment the job is running in, but if you want to share the input files (FASTQ and reference) you are using by emailing me at the address in the _breseq_ header, I can take a look to see if they are causing any particular issues.

**Comment by valery-shap** [comment]
Thank you for you reply. 
Yes, it looks like that the main problem is with running using SLURM. I decided to describe it here, because this might be useful for someone which will have the same problem. 
the process ended in the terminal and it ended with the text:
` Creating index HTML table... [system] rm -f "/home/01_sequence_conversion/*.trims"
Error running command:
[system] rm -f "/home/01_sequence_conversion/*.trims"
Result code: -1[system] rm -f "/home/03_candidate_junctions/candidate_junction.fasta"
Error running command:
[system] rm -f "/home/03_candidate_junctions/candidate_junction.fasta"
Result code: -1[system] rm -f "/home/03_candidate_junctions/candidate_junction.fasta.fai"
Error running command:
[system] rm -f "/home/03_candidate_junctions/candidate_junction.fasta.fai"
Result code: -1[system] rm -f "/home/05_alignment_correction/jc_evidence.gd"
Error running command:
[system] rm -f "/home/05_alignment_correction/jc_evidence.gd"
Result code: -1[system] rm -f "/home/06_bam/junction.bam"
Error running command:
[system] rm -f "/home/06_bam/junction.bam"
Result code: -1[system] rm -f "/home/06_bam/junction.bam.bai"
Error running command:
[system] rm -f "/home/06_bam/junction.bam.bai"
Result code: -1+++   SUCCESSFULLY COMPLETED`

It seems that it couldn't remove some files. Is it ok? I have the output folder with html reports.

**Comment by jeffreybarrick** [comment]
If the output is there and complete, it should be fine. If not, let me know and those errors removing files could be made non-stopping warnings.
