### ISSUE TITLE
Visual distinction between syn/non-syn mutations

### ISSUE THREAD

**Issue by GoogleCodeExporter** [barricklab/breseq#63]
```

What version of the product are you using? On what operating system?

0.22

Please provide any additional information below.

index.html lists all the SNPs with their "annotation". For CDS features you 
list the amino acid change eg. M189V. The majority of SNPs will be synonymous 
(eg. P281P), and are of less interest than non-syn ones. However the non-syn 
ones are difficult to find in the big lists.

Could you highlight these in some way to distinguish them from syn ones?

Or even better, create different tables for the different SNP types?
eg. syn, non-syn, intergenic.


```

Original issue reported on code.google.com by `torsten....@gmail.com` on 4 Jan 2013 at 3:40

**Comment by jeffreybarrick** [comment]
SNPs are now automatically colored by type (including synonymous, nonsynonymous, nonsense, and intergenic) in the next release.

**Comment by JaninaLange** [comment]
Dear Jeffrey, 
would you mind telling me which color is synonymous and which one is nonsynonymous? Would be helping, since I am going through my data right now and want to extract the synonymous ones. 
Thanks in advance, 
Best
Janina

**Comment by jeffreybarrick** [comment]
Green is synonymous, blue is nonsynonymous, and red is nonsense.

If you use `gd ANNOTATE` on the output GD file or look in the file `output/evidence/annotated.gd` there is a `snp_type` attribute for each mutation that could be used to extract certain types.
