### ISSUE TITLE
gene/description/product fields in output from gff vs gbk

### ISSUE THREAD

**Issue by Perugolate** [barricklab/breseq#77]
When I use a .gbk file as input the correct gene/description/product fields are displayed in the output. Howver if I use a gff3 .gff file, then the gene/description/product fields are empty in the output. .gbk .gff files were produced using prokka.

**Comment by jeffreybarrick** [comment]
Can you upload/send an example of the prokka GFF format file? There's some variation in where/whether certain annotation information is stored in these files. If the info is there, we can update breseq to pull it in.

**Comment by Perugolate** [comment]
https://www.dropbox.com/s/roikpbg8nrwfrk1/cor_no_tn.gff?dl=0
https://www.dropbox.com/s/scozgexyulzl3e1/cor_no_tn.gbk?dl=0

yeah gff is pain

**Comment by jeffreybarrick** [comment]
Code updated; it'll be in the next release. Thanks for letting us know.
