### ISSUE TITLE
gdtools compare core dump error

### ISSUE THREAD

**Issue by minisciencegirl** [barricklab/breseq#81]
Hi I've encountered the error below when I am trying to compare certain .gd files. It looks like there are different variants being called at the same position. My sneaky suspicion is that this is probably in a highly repetitive region and the read support at each of the location can be equally valid. Is there a way for me to parse out different variants called at the same position using breseq?

Thanks!

Amy

   Tabulating frequencies of mutations across all files
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Identical diff entry items found in file:
Bcc156.gd
1>>
INS	465	8177	NC_011001	809083	GGGG	repeat_length=1	repeat_new_copies=10	repeat_ref_copies=6	repeat_seq=G
2>>
INS	466	6776,6777,6778,6779	NC_011001	809083	GGGG	repeat_length=1	repeat_new_copies=10	repeat_ref_copies=6	repeat_seq=G

FILE: genome_diff.cpp   LINE: 4591
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
gdtools: libbreseq/common.h:92: void breseq::my_assertion_handler(bool, const char*, const char*, int, const std::string&): Assertion `false' failed.
Aborted (core dumped)

**Comment by jeffreybarrick** [comment]
Yes. This seems to be a bug with the same mutation being called in two different ways (from both MA and JC evidence). I've had another user report the same thing and it's on my list of things to fix.

Unfortunately, I don't have an easy workaround for purging the problem lines from existing output.

**Comment by jeffreybarrick** [comment]
This issue is fixed for upcoming v0.27.

**Comment by minisciencegirl** [comment]
Thanks Jeff!
