### ISSUE TITLE
failure when processing polymorphism stats

### ISSUE THREAD

**Issue by vscooper** [barricklab/breseq#83]
Hello, I'm using breseq in a new shared environment for population sequencing using the -p flag. One sample worked well but one failed with the following error. I'd welcome feedback on the likely source.

[system] R --vanilla total_length=6537648 in_file=/mnt/mobydisk/groupshares/vcooper/cooperv/MutatorInvasions-25483460/D8-A5//08_mutation_identification/polymorphism_statistics_input.tab out_file=/mnt/mobydisk/groupshares/vcooper/cooperv/MutatorInvasions-25483460/D8-A5//08_mutation_identification/polymorphism_statistics_output.tab qual_file=/mnt/mobydisk/groupshares/vcooper/cooperv/MutatorInvasions-25483460/D8-A5//08_mutation_identification/error_counts.tab < /data/sam/rhel6/breseq/breseq-0.26.1-Linux-x86_64/bin/../share/breseq//polymorphism_statistics.r > /mnt/mobydisk/groupshares/vcooper/cooperv/MutatorInvasions-25483460/D8-A5//08_mutation_identification/polymorphism_statistics_output.log
Warning message:
In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  embedded nul(s) found in input
breseq: reference_sequence.cpp:2657: void breseq::cReferenceSequences::polymorphism_statistics(breseq::Settings&, breseq::Summary&): Assertion `line_list.size() > j' failed.

**Comment by jeffreybarrick** [comment]
Does this file have any lines in it?

/mnt/mobydisk/groupshares/vcooper/cooperv/MutatorInvasions-25483460/D8-A5//08_mutation_identification/polymorphism_statistics_output.tab 

If so, please attach that file and also this one:

/mnt/mobydisk/groupshares/vcooper/cooperv/MutatorInvasions-25483460/D8-A5//08_mutation_identification/polymorphism_statistics_input.tab 

I assume this is with v0.26.1.

Thanks!

**Comment by vscooper** [comment]
Jeff, no worries, please close this. It turns out that we had scrambled indices so we were mapping to the wrong reference sequences. 

Thanks.

**Comment by jeffreybarrick** [comment]
Great! - will see if we can get breseq to give a more informative warning of this and not just crash in the future.
