### ISSUE TITLE
Does breseq need samtools-0.1.18 ?

### ISSUE THREAD

**Issue by tseemann** [barricklab/breseq#85]
I notice it installs the old samtools into the bin folder.

Does it need the specific old version for correct behaviour or does it work with the 1.x series ok?

**Comment by jeffreybarrick** [comment]
I don't see any reason that it shouldn't work with any 1.x version of Samtools, but I haven't tested this.

It's on the to-do list to completely remove the dependence on the samtools executable in future versions so that there's no longer any danger of clobbering a user's other installed version!

**Comment by tseemann** [comment]
Ok that's good to know.

I've written a Brew formula for it: https://github.com/Homebrew/homebrew-science/pull/3041

I depend on the modern samtools/htslib package and remove your `samtools` binary before installing.

The "failure" of the build is only on Mavericks - something about non US-ASCII characters. Looking into it.

**Comment by alexmyczko** [comment]
current version still ships extern/samtools-1.3.1 while there's 1.10 available

**Comment by jeffreybarrick** [comment]
A compatible version of _samtools_ is included with the _breseq_ source code and compiled into the executable. So, _samtools_ is not needed as a pre-requisite. Since the current version of _samtools_ works for _breseq_'s functionality, I don't think there is any advantage for updating that. 

Do you know of any?

**Comment by alexmyczko** [comment]
well it makes the source tarball huge and build time long, from what i see you only need libbam right?

**Comment by jeffreybarrick** [comment]
Thanks for the feedback.

As far as **tarball size**, are we talking about the ones like `breseq-0.35.0-Source.tar.gz` or the GitHub tarballs that include the entire repository and lots of test data?

I went ahead and tried stripping some unused _samtools_ test data from `extern/samtools-1.3.1` to slim down things a bit. This directory went from something like 17 Mb to 3.4 Mb uncompressed, but saved relatively little in the gzipped version (~3 Mb). I also found that inadvertently the files for building the manual were included in the tarball and removed those. I'll go ahead and include those slimming changes in the next release of the "Source" version.

The compile time of _libbam/samtools_ is pretty quick on my system compared to that of _breseq_ itself. Do you have a different experience?

It's true that _breseq_ could link to _libbam_ if it was installed, but I think the relatively small savings of doing this are outweighed by how the current setup makes it easier for novice users to get things running without having to search for and compile _samtools_. I think the current setup is also more maintainable, as incompatibilities/bugs might be introduced in future _samtools_ releases, etc.

**Comment by alexmyczko** [comment]
3.4 mb uncompressed sounds far better, can't wait for the new tarball then! i'll check the other points and answer asap

**Comment by jeffreybarrick** [comment]
That was the savings in size. The source tar.gz will now be ~13 Mb, basically the same as the binary downloads. Down from 20 Mb. Can you explain to me why shrinking this more matters so much to you? – as long as the test FASTA data and HTML documentation are included, it will never be a small download. If you have some particular application, a version that is just the minimal source could be created.

**Comment by alexmyczko** [comment]
I am kind of offline but will try to explain with details and examples on Monday...

**Comment by tseemann** [comment]
I think the samtools API changed between 1.3 and 1.10
There are some othe projects which also now bundle it rather than upgrade to the new API.
