### ISSUE TITLE
Add a --version flag

### ISSUE THREAD

**Issue by tseemann** [barricklab/breseq#86]
Could you add a GNU-standard `--version` switch?

```
% breseq --version
breseq 0.27.0
```

**Comment by jeffreybarrick** [comment]
Sure. Done in source. Let me know if it's worthwhile to modify the 0.27.0 release to add this for your work with package managers. (Feedback and doing that is appreciated!)

**Comment by tseemann** [comment]
Never change a release, always make a new higher version release.

The reason is that the .tgz file checksum is used to verify the download. If it fails, all hell breaks loose. And lots of people get confused and grumpy :)

**Comment by jeffreybarrick** [comment]
Good point. I'll do things by the book so you can count on those checksums!
