### ISSUE TITLE
Error when processing Polymorphism statistics

### ISSUE THREAD

**Issue by lauguma** [barricklab/breseq#88]
Hello.

I'm using breseq in order to find mutations in a DNA yeast sample. I used --aligned-sam flag because my sequence was in ColorSpace format and I had to align it against the reference genome with another aligner so the input was a sam file.

The program works well until the processing Polymorphism statistics step when it is reported the following error.

+++   NOW PROCESSING Polymorphism statistics
[system] R --vanilla total_length=11592188 in_file=./08_mutation_identification/polymorphism_statistics_input.tab out_file=./08_mutation_identification/polymorphism_statistics_output.tab qual_file=./08_mutation_identification/error_counts.tab < /usr/local/bin/../share/breseq//polymorphism_statistics.r > ./08_mutation_identification/polymorphism_statistics_output.log
breseq: reference_sequence.cpp:2694: void breseq::cReferenceSequences::polymorphism_statistics(breseq::Settings&, breseq::Summary&): Assertion `line_list.size() > j' failed.
Aborted

I also opened the file polymorphism_statistics_output.tab and it is written the next:

log10_base_likelihood
1
0

I've been looking for the possible mistake in my data for a few days but I don't have any idea about what could be wrong. I'd really appreciate all the help that you could give it to me.

Thanks in advance!

**Comment by jeffreybarrick** [comment]
Thanks for reporting the problem. This will be easiest for me to figure out if you can provide me with your input files and command line. Please, email me at the address in the header that comes up when you run *breseq*, and I will then provide you with a private link to upload them to our server.

**Comment by jeffreybarrick** [comment]
I'm not able to reproduce this crash on your data using breseq 0.26.0 or breseq 0.27.1. Which version are you using?

**Comment by jeffreybarrick** [comment]
User reports problem is resolved.
