### ISSUE TITLE
Program freezes after loading reads for "Resoling alignments with junction candidates".

### ISSUE THREAD

**Issue by sekoye** [barricklab/breseq#90]
Hello,

As the subject line indicates, the program seems to hang after loading the read files for this step in breseq. I am using the 0.27.1a Linux binaries. Turning off this feature resolves the issue, any clue as to why this is occurring or can I provide any other information to help you resolve this problem?

Thanks!

**Comment by sekoye** [comment]
I believe the issue was related to the number of contigs I had for the draft reference sequence (around 100). Merging the contigs resolved this issue.

**Comment by jeffreybarrick** [comment]
OK. Glad that worked. It's possible that it would have completed eventually if left processing, but that it was predicting many, many putative junctions between the contigs and taking an unusually long time at this step. If you want me to check into this further, please contact me by email and I can set you up to provide me with your test files to reproduce the problem.
