### ISSUE TITLE
Error during Polymorphism statistics

### ISSUE THREAD

**Issue by ptmckenney** [barricklab/breseq#91]
Hi, I get this error towards the end of the pipeline. Any idea what it means?

Running version 0.26.1 on Linux. I've used the same .gb reference before with no problems. 

+++   NOW PROCESSING Polymorphism statistics
[system] R --vanilla total_length=3151926 in_file=./breseq_EtOH/08_mutation_identification/polymorphism_statistics_input.tab out_file=./breseq_EtOH/08_mutation_identification/polymorphism_statistics_output.tab qual_file=./breseq_EtOH/08_mutation_identification/error_counts.tab < /home/mckennep/Applications/breseq-0.26.1/bin/../share/breseq//polymorphism_statistics.r > ./breseq_EtOH/08_mutation_identification/polymorphism_statistics_output.log
+++   NOW PROCESSING Output
Creating merged genome diff evidence file...
Predicting mutations from evidence...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
start (119846) not less than or equal to end (119827)
FILE: ./libbreseq/reference_sequence.h   LINE: 419
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
breseq: libbreseq/common.h:92: void breseq::my_assertion_handler(bool, const char*, const char*, int, const std::string&): Assertion `false' failed.
Aborted

**Comment by jeffreybarrick** [comment]
Hi, 

There must be an error when predicting mutations in this particular sample. 

If you send me an email at the address in the command-line header, I can arrange to test your reference and read files to figure out exactly what is going on and correct it.

It's possible -- but I think unlikely -- that the bug fixes in the current version (v0.26.2) also fix this problem.

Thanks!

**Comment by ptmckenney** [comment]
Jeffery,

Updating to v0.27.2 seems to have solved it.

Thanks,
Peter.
