### ISSUE TITLE
"Deleted=1" tag in the output.gd file

### ISSUE THREAD

**Issue by ruipspereira** [barricklab/breseq#93]
Dear developers,

I am using breseq 0.26.1 for a few weeks in an ubuntu virtual machine. The analysis I am running consists on detecting mutations in S. cerevisiae strains sequenced with illumina HiSeq, 150 bp x2.
I have sequenced both the wild-type and mutant strains and my plan was using gdtools to subtract the mutations already present in the wild-type strain to get just the mutations novel in my mutant strains.
I also have to mention that my wild-type strain is quite different from the reference genome, i.e., it has around 21,889 SNV and 2,859 INDELS.
I am running breseq with a 100x coverage limit: "breseq -l 100 -j 8 -o sci_output -r GCA_000146045.2_R64_genomic.gbff file1.fq file2.fq"

When I subtract the mutations from the wild-type strain on the mutant strain, I have a lot of false-positives. Upon further inspection I realized that many of these false-positives are not detected as mutations in the wild-type strain, but appear in the output file as RA evidence.
Here are a couple of examples:
RA	23363	.	BK006934	93284	0	A	G	deleted=1	frequency=1	genotype_quality=98.3	new_cov=13/21	quality=98.3	ref_cov=0/0	tot_cov=13/21
RA	23364	.	BK006934	93290	0	C	T	deleted=1	frequency=1	genotype_quality=80.1	new_cov=13/20	quality=80.1	ref_cov=0/0	tot_cov=13/21

I do not understand why breseq is not assuming these evidence as mutations because the alignments look quite clear to me. Is the "deleted=1" the reason these mutations are ignored? How can I change the settings to include these mutations?

Thank you for help and let me know if you need any other information from my side.

[Results.zip](https://github.com/barricklab/breseq/files/269850/Results.zip)

**Comment by jeffreybarrick** [comment]
The deleted=1 tag is added to an evidence entry in the GenomeDiff file when there is a missing coverage item overlapping it. Typically, this is a good thing because it prevents a few spurious reads that map within a truly deleted region from being predicted as a SNP, for example.

I think that you may want to avoid calling "large" deletions altogether in your ancestral sample to prevent the deleted=1 tag from being added. I would try setting --deletion-coverage-seed-cutoff to be a very high value, like ~100. You may need to subtract mutations predicted both this way and the normal way from your sample.

In general _breseq_ will have trouble with some situations when the reference genome is this different from your samples. You might also try running gdtools APPLY on your reference genome based on the output for the ancestral sequence to tty to create an updated reference.

**Comment by ruipspereira** [comment]
Thank you very much for the tips, I will try your suggestion and will let you know how it worked.

Regarding the APPLY command on gdtools, I initially planed to use it as a strategy to create an updated reference genome. However, on breseq version 0.26.1 when I try to apply the mutations from the reference strain to the reference genome I get several errors that result in an aborted run:

>>> Error(s) in GenomeDiff format. FILE: wt.gd <<<
>>ERROR: Specified REF_BASE does not match actual reference base (T) at the specified positon.
>>LINE: 23715
...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Errors in GenomeDiff File. Not safe to continue
FILE: genome_diff.cpp   LINE: 1847
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
gdtools: libbreseq/common.h:92: void breseq::my_assertion_handler(bool, const char*, const char*, int, const std::string&): Assertion `false' failed.

When I try to validate the same file with gdtools, the same errors appear (see files in the zip file).
I can still use these files in gdtools for subtration operations, but I have not investigated in detail why it works for one operation and not the other.

I have tried to solve the problem by trying to use the latest version of breseq to run the same analysis but breseq aborts the operation on the last part of the analysis with the error:

$ breseq -l 100 -j 8 -o ref_s288c -r GCA_000146045.2_R64_genomic.gbff file1.fq file2.fq
...
+++   NOW PROCESSING Output
Creating merged genome diff evidence file...
Predicting mutations from evidence...

>>> Error(s) in GenomeDiff format. FILE:  <<<
>>ERROR: Attempt to add duplicate of this existing entry from line NA:
MOB<tab>3943<tab>49658,49661<tab>BK006938<tab>519726<tab>Ty3 LTR<tab>1<tab>5<tab>del_start=46<tab>ins_start=TGTTGTATCTCAAAATGAGATATGTCAGTATGACAATACGTCACCCTGAAC
Add a 'unique' tag to one if this is intentional.
>>LINE:     0
MOB<tab>3944<tab>49659,49661<tab>BK006938<tab>519726<tab>Ty3 LTR<tab>1<tab>5<tab>del_start=46<tab>ins_start=TGTTGTATCTCAAAATGAGATATGTCAGTATGACAATACGTCACCCTGAAC

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Fatal formatting error in GD file being written: ref_full_s288c/output/output.gd
FILE: genome_diff.cpp   LINE: 2314

**Comment by jeffreybarrick** [comment]
This is all related to _breseq_ improperly predicting the same mutation twice. You must be finding a rare problem with so many differences between these samples and the reference. I'd like to fix this! If you don't mind, can you share your reference files for the breseq run of v0.26.2 that is giving the fatal error with me for testing? Contact me by email (at the address in the breseq CL header), and I can set up a way to transfer the files.

**Comment by jeffreybarrick** [comment]
Bug fixed for next version.
