### ISSUE TITLE
strange counts of POSSIBLE mutations and called_bp with gdtools COUNT

### ISSUE THREAD

**Issue by ramiroricardo** [barricklab/breseq#97]
Dear all,

I have been using breseq to analyse evolved clones of E. coli MG1655. I have sequenced three clones from one population (named 40b, S5 and S8) and I wanted to calculate what is the number of shared mutations and the number of mutations accumulated after the clones diverged. To do this, I was running the gdtools commands below. After this I was going to use the output in the count files to calculate dn/ds as described in your tutorial for clonal samples.

The problem is that there are large differences in the number of POSSIBLE mutations between the shared_mutations.gd file and gd files with the mutations accumulated post divergence for each of the clones, though the counts of observed mutations appear fine. This difference is shown in the number of the POSSIBLE mutations and in the number of called_bp. There are ~60-70kb less called_bp in the files for the clones post-divergence than there are in the shared mutations, but the difference in POSSIBLE mutations is more variable. I guess one of the things that could explain this would be large deletions, but the largest deletion in one of the clones is only 9kb, so this could not be it.

If you have any idea of what might be going on, it would be great if you can let me know. I am sorry if this is just something basic that I am failing to understand.

I have attached the gd files that were used in all commands (see [counts.zip](https://github.com/barricklab/breseq/files/386862/counts.zip)). The counts.xslx file has the combined output of the different runs of the COUNT command and I have highlighted the differences in counts. If there is other information that might help, please let me know.

Also, note that I had previously used "gdtools APPLY" to introduce mutations present in my ancestral that are not in the NCBI reference, so I generated 21YFP_REF.gff3.

Thanks for any help,

Ramiro

```
gdtools INTERSECT -o shared_mutations.gd  clone40b_annotated.gd cloneS5_annotated.gd cloneS8_annotated.gd 

gdtools SUBTRACT -o mutations_postDivergence_40b.gd clone40b_annotated.gd shared_mutations.gd

gdtools SUBTRACT -o mutations_postDivergence_S5.gd cloneS5_annotated.gd shared_mutations.gd

gdtools SUBTRACT -o mutations_postDivergence_S8.gd cloneS8_annotated.gd shared_mutations.gd



gdtools COUNT -b -o shared_mutations.csv -r 21YFP_REF.gff3  shared_mutations.gd

gdtools COUNT -b -o mutations_postDivergence_40b.csv -r 21YFP_REF.gff3  mutations_postDivergence_40b.gd

gdtools COUNT -b -o mutations_postDivergence_S5.csv -r 21YFP_REF.gff3  mutations_postDivergence_S5.gd

gdtools COUNT -b -o mutations_postDivergence_S8.csv -r 21YFP_REF.gff3  mutations_postDivergence_S8.gd
```

**Comment by jeffreybarrick** [comment]
gdtools COUNT excludes bases that are within the coordinates covered by UN (unknown) and MASK (masked) regions when calculating the POSSIBLE mutation columns. The UN regions, in which there is not sufficient coverage of uniquely-mapped reads to call a point mutation or not, are probably different for each of your NGS datasets (as they depend on coverage in a particular sample and read length), and this likely accounts for the differences. If not, let me know that I should dig deeper.

**Comment by ramiroricardo** [comment]
Hi Jeff,

thanks for your quick reply. I had first looked at the summary statistics html output, thinking that if something like that was the problem I should see some variation in length, but I realise now that length refers to the reference and not to the number of bases called. When I run COUNT on the gd file of each of the clones, I do get variation in the number of bases called, so It seems the problem might be what you describe. 

sorry for bothering you with this and thanks for your help,

Ramiro
