### ISSUE TITLE
SNP calls in 0.28

### ISSUE THREAD

**Issue by ptmckenney** [barricklab/breseq#99]
Hi,

We're experiencing some weirdness with the SNP calls since updating to 0.28.1. A lot of the called SNPs that were present in 0.26 and 0.27 are going missing on the same data set run with 0.28.1.  I can open the .bam alignment file from breseq 0.28.1 in IGV and see that the variants are there, but the variant calls are missing from the breseq .gd file. When run with -p, some of these are as high 70%. 

A few of them have moved to the 'marginal call' list. But, for example, I have 3 SNPs in the same gene. The two highest frequency alleles are in the marginal calls and the lowest frequency is in the true calls.

These data are shotgun population sequencing, mapped to a reference at ~1000x coverage. A student in our lab has seen the same thing with individual isolates at 100x coverage, when comparing output from 0.27 to 0.28.

Thanks,
Peter.

**Comment by jeffreybarrick** [comment]
Hi Peter,

Can you share an example dataset and command line for debugging? Contact me at the email in the breseq header, and I can give you access to a shared drive to upload the FASTQ and reference.

Thanks,
--Jeff

**Comment by jeffreybarrick** [comment]
I'm not exactly sure what the issue you are seeing is, but you might try turning off some of the `--polymorphism-* settings` filters to see if the predictions return (by setting them to zero). There were some changes to the defaults in previous versions of _breseq_.

I've also posted a test release `breseq-0.28.2rc3` that fixes an issue with good polymorphisms being thrown out by the MacOS X binary distribution specifically, and possibly if you compiled it from source on certain other systems.

http://barricklab.org/release/breseq/

**Comment by jeffreybarrick** [comment]
Another user reported what I believe is this issue, and it has been fixed in 0.28.2rc5 available at http://barricklab.org/release/breseq. It will be included in the next official release (probably 0.29.0), which will hopefully be happening within a few weeks.
